import type { OperationGuide } from "./operation-guide-types";

/** Basic course workflows; keep source review separate from interactive acceptance. */
export const courseBasicOperationGuides: OperationGuide[] = [
  {
    id: "C126", category: "start", title: "第一次使用課程系統，設定順序是什麼？",
    summary: "先準備店家、教室、教練與課程，再建立方案及實際課表。", answer: "課程範本、實際課次與學員持有方案是三件事，需依序準備。",
    path: "設定 → 店務設定 → 課表排程", keywords: "首次使用 新手 開店 設定順序 開始使用",
    steps: ["先核對店家資料、營業與公休、預約開放及取消截止設定。", "建立教室與教練，設定可教授課程；建立課程範本與適用方案。", "排出實際課次，再替學員指派方案或安排體驗；核對日期、教練、名額與會員入口。"],
    important: "建立課程範本不代表已排課，建立販售方案也不代表學員已持有方案。",
    details: ["需要轉帳購買時先設定銀行資料；需要通知時另確認提醒設定與 LINE 連結。", "每個設定需具備對應權限；本題是操作順序，詳細步驟可搜尋教室、教練、排課或指派方案。"],
    success: "課表有正確課次，學員能在本店入口看到可預約課程與自己的方案。",
    permission: "booking.read", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/app/(dashboard)/dashboard/courses/settings-workspace.tsx"],
  },
  {
    id: "C127", category: "customers", title: "如何新增或修改課程學員資料？",
    summary: "先搜尋既有學員，再新增或編輯基本資料與緊急聯絡資訊。", answer: "已有學員請編輯原資料，避免為了改電話重建一份。",
    path: "顧客管理 → 新增顧客／顧客詳情 → 基本資料", keywords: "新增學員 修改姓名 電話 生日 緊急聯絡人 重複建檔",
    steps: ["先以姓名或電話搜尋並明確選取候選，核對是否已有資料。", "新增時填寫表單；已有資料時進入基本資料，點編輯顧客資料，修改姓名、電話或緊急聯絡資訊。", "儲存成功後重新開啟該學員，核對欄位與原持有方案。"],
    important: "修改聯絡電話不等於更換 LINE 帳號；身分綁定問題應另外核對。",
    details: ["新增需要顧客建立權限，修改需要顧客編輯權限；查看資料不表示可編輯。", "遇到錯誤先保留內容與訊息，確認是否已建檔，不要反覆新增同名學員。"],
    success: "原學員資料顯示正確，未因修改資料而另建重複學員。",
    permission: "customer.read", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/server/actions/course-members.ts"],
  },
  {
    id: "C128", category: "customers", title: "如何設定學員的直屬店長與推薦人？",
    summary: "在身分與歸屬資訊中核對並修改，與本次方案成交開發人分開。", answer: "學員目前歸屬和購買當時的開發人快照用途不同。",
    path: "顧客管理 → 顧客詳情 → 基本資料 → 身分與歸屬資訊", keywords: "直屬店長 推薦人 歸屬 開發人 分配",
    steps: ["打開正確學員，展開身分與歸屬資訊。", "核對直屬店長；需要推薦人時搜尋並選取正確候選，再儲存。", "重新開啟確認結果；後續指派方案時另核對本次開發人。"],
    important: "不要把修改學員歸屬當成改寫歷史成交分配。",
    details: ["歸屬設定需要顧客指派權限，候選及資料受門市範圍限制。", "課程分析的出席歸屬與購買快照口徑不同，可配合營運分析指南核對。"],
    success: "重新開啟後顯示正確歸屬與推薦人。",
    permission: "customer.assign", additionalPermissions: ["customer.read"], feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/server/actions/course-customer-attribution.ts", "src/app/(dashboard)/dashboard/courses/member-workspace.tsx"],
  },
  {
    id: "C129", category: "customers", title: "哪裡查看學員的購買與上課紀錄？",
    summary: "從顧客詳情切換持有方案或購買與上課，分開核對額度與交易。", answer: "上課紀錄、持有方案與購買紀錄各自反映不同狀態。",
    path: "顧客管理 → 顧客詳情 → 持有方案／購買與上課", keywords: "購買紀錄 上課歷史 顧客詳情 交易 持有方案",
    steps: ["搜尋並開啟學員，核對姓名與電話。", "在持有方案查看卡片；在購買與上課查看可見紀錄，核對日期與狀態。", "發現差異時回查原課次或原購買，不直接再指派一張方案。"],
    important: "預約存在不代表已出席；待核帳購買也不代表已啟用方案。",
    details: ["方案、交易與預約的查看權限分開，部分分頁或資料可能不顯示。", "退款、作廢與取消應回到對應原紀錄處理，不用刪除學員來消除歷史。"],
    success: "能把同一學員的方案、購買狀態與上課紀錄對應起來。",
    permission: "customer.read", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx"],
  },
  {
    id: "C130", category: "customers", title: "店內備註與本次上課備註有何不同？",
    summary: "長期提醒放學員資料，單次交代放該筆預約。", answer: "兩種備註都不能代替點名、取消或收款操作。",
    path: "顧客詳情 → 基本資料；課程名單／教練我的工作 → 本次備註", keywords: "備註 長期提醒 本次上課 教練可見 留言",
    steps: ["長期服務提醒在學員基本資料編輯店內備註。", "只涉及這一堂的事情，在正確課次及學員列編輯本次備註。", "儲存後重新查看文字；離開前確認沒有未儲存修改。"],
    important: "店內與教練工作畫面會提供相關備註，不要把它當作只有自己可見的私人筆記。",
    details: ["店內備註需顧客編輯權限；後台本次備註需預約編輯權限，教練依自己的授權課程操作。", "課程備註欄有字數限制；不要照搬蒸足文章的欄位限制或入口。"],
    success: "長期與本次內容各保留在正確位置，預約及帳務狀態不變。",
    permission: "customer.read", feature: null, modules: ["course"], kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/app/(dashboard)/dashboard/courses/roster.tsx", "src/app/(customer)/book/course-portal-client.tsx"],
  },
  {
    id: "C131", category: "hours", title: "如何設定每週營業、公休及預約開放日期？",
    summary: "先設定每週規則，再處理特殊日期與會員可預約範圍。", answer: "營業時間限制排課範圍；會員可預約範圍另由預約開放設定控制。",
    path: "設定 → 營業與預約", keywords: "每週營業 公休 特殊日期 預約開放 期限 日期",
    steps: ["開啟每週營業時間，核對各日規則並儲存。", "有例外日期時開啟特殊公休／調整日期，設定當日規則。", "核對預約開放設定並儲存，再查看課表及會員可預約範圍。"],
    important: "有課程或預約衝突時需先處理衝突，不能直接用公休覆蓋。",
    details: ["特殊日期優先於每週設定；回復預設會移除當日覆寫。", "調整營業時間不會自動建立新課次；有課次才能讓會員選課。"],
    success: "重新開啟後規則正確，課表與會員開放範圍符合設定。",
    permission: "business_hours.manage", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/settings-workspace.tsx", "src/server/actions/course-business-hours.ts", "src/server/actions/course-booking-window.ts"],
  },
  {
    id: "C132", category: "hours", title: "課程預約與自行取消截止時間怎麼設定？",
    summary: "在營業與預約分別設定兩個截止時間。", answer: "預約截止與取消截止是不同限制，請分別核對。",
    path: "設定 → 營業與預約 → 預約與取消截止", keywords: "預約截止 取消截止 提前 分鐘 逾期 不能取消",
    steps: ["找到預約與取消截止區塊，查看目前設定。", "分別調整預約及自行取消的提前時間，確認後儲存。", "重新開啟核對；請會員以我的預約顯示的自行取消截止時間為準。"],
    important: "超過自行取消期限請聯絡店長，不要以刪除帳號或重建預約處理。",
    details: ["自由預約先保留額度，出席才扣；固定期課未到仍扣堂，不提供補課券。", "改截止時間不等於退款，也不會放寬教室容量或方案限制。"],
    success: "設定保留正確，會員畫面顯示對應截止時間。",
    permission: "business_hours.manage", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/server/actions/course-settings.ts", "src/app/(dashboard)/dashboard/courses/settings-workspace.tsx", "src/app/(customer)/book/course-portal-client.tsx"],
  },
  {
    id: "C133", category: "hours", title: "值班聯動開啟後，如何影響排課？",
    summary: "啟用時教練值班需涵蓋完整課程，僅開始時間相符仍可能衝突。", answer: "值班聯動是排課檢查條件，不能代替教練授課資格。",
    path: "設定 → 營業與預約 → 值班聯動 → 查看值班概況", keywords: "值班聯動 排班 教練 衝突 完整課程",
    steps: ["先查看值班聯動目前是否啟用。", "開啟值班概況，核對教練與整堂課的起訖時間；需要調整時由有權限者修改。", "回課表重新預覽排課，確認值班、教室及教練時段都無衝突。"],
    important: "不要為了略過一堂衝突而直接改全店設定，先確認實際教練班表。",
    details: ["未啟用時值班供參考；排課仍須符合其他時間與資源規則。", "值班管理需要值班管理權限；教練可教授課程需到人員設定另行配置。"],
    success: "排課預覽通過，教練值班涵蓋預定課程。",
    permission: "duty.manage", feature: null, modules: ["course"], kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/settings-workspace.tsx", "src/server/actions/duty.ts", "src/lib/course-scheduling.ts"],
  },
  {
    id: "C134", category: "plans", title: "剩餘、預約保留與可用額度怎麼看？",
    summary: "先選正確卡片，再核對額度單位、期限及預約保留。", answer: "可用額度是剩餘減掉預約保留；點數與堂數不能混加。",
    path: "顧客詳情 → 持有方案；會員專區 → 我的方案", keywords: "剩餘 預約保留 占用 可用額度 異動 到期 約不到",
    steps: ["開啟正確學員的卡片，核對方案名稱、單位及到期日。", "比較剩餘、已預約保留與可用額度，回查尚未完成的預約。", "若仍約不到，再查方案是否適用課程、是否過期，以及課程容量與截止時間。"],
    important: "有剩餘不代表可立即預約；額度可能已保留給其他課次。",
    details: ["會員我的方案可查看額度異動；出席、取消、未到及退款的規則不同。", "固定期課綁指定課次；不要把固定期課剩餘堂數用來預約其他課程。"],
    success: "可用額度與預約保留可對應，能確認不能預約的具體原因。",
    permission: "wallet.read", feature: null, modules: ["course"], kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/app/(customer)/book/course-portal-client.tsx"],
  },
  {
    id: "C135", category: "health", title: "如何新增、修改與查看學員健康量測？",
    summary: "在學員詳情開啟健康追蹤，核對日期後新增或編輯紀錄。", answer: "健康功能需開通；查看與修改權限分開，會員只讀寫自己的資料。",
    path: "顧客管理 → 顧客詳情 → 健康追蹤", keywords: "健康追蹤 量測 體重 日期 歷史 修改 健康紀錄",
    steps: ["核對學員後開啟健康追蹤，查看最新量測與摘要。", "新增時點新增量測；修正時展開編輯量測紀錄，選正確日期那筆再編輯。", "填寫實際量測日期與數據，儲存後返回核對紀錄。"],
    important: "量測日期只能選今天或之前；不要為了修正數字重複新增同一筆。",
    details: ["編輯清單提供最近 100 筆，不能將清單範圍當成全部歷史都被刪除。", "後台新增與修改需要顧客編輯權限；共卡不開放其他成員的健康資料。讀取失敗時用重新讀取，不當作沒有紀錄。"],
    success: "儲存後正確日期的量測已更新，沒有產生非預期重複紀錄。",
    permission: "customer.read", feature: "ai_health_summary", modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/components/course-health-workspace.tsx", "src/server/actions/course-health.ts"],
  },
  {
    id: "C136", category: "staff", title: "如何切換會員／教練身分並使用我的工作？",
    summary: "從本店會員入口登入，具教練工作身分者可切換我的工作。", answer: "教練工作身分與一般會員功能分開，需先由店家完成連結及授課資格設定。",
    path: "本店會員入口 → 我的工作", keywords: "教練 會員 身分切換 我的工作 課表 名單 授課紀錄",
    steps: ["從正確課程店入口登入，確認畫面店家名稱。", "有身分切換時選我的工作，按日期查看自己的課次與名單。", "依實際情況處理點名或本次備註；查看授課紀錄時確認月份與統計說明。"],
    important: "看到工作入口不表示具有店長後台權限，也不能處理其他未授權教練的課次。",
    details: ["沒有我的工作時請店家核對教練身分、顧客帳號連結與授課資格。", "純工作身分可能無會員操作；授課紀錄不等於授課費已支付，付款請查看營運紀錄。"],
    success: "能看到自己的工作課次，會員與教練操作範圍清楚。",
    permission: "staff.view", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(customer)/book/course-portal-client.tsx", "src/app/(dashboard)/dashboard/courses/staff-workspace.tsx"],
  },
  {
    id: "C137", category: "money", title: "銀行轉帳資料與體驗價格在哪裡設定？",
    summary: "在收款與體驗分別維護銀行資訊及體驗設定，付款聯繫沿用店家官方 LINE。", answer: "設定收款資料不會自動核帳，會員回報轉帳後仍需店家確認實際入帳。",
    path: "設定 → 收款與體驗", keywords: "銀行 轉帳 帳號 體驗價格 調整範圍 官方LINE",
    steps: ["在銀行轉帳資訊核對銀行名稱、代碼與帳號，修改後儲存。", "在體驗設定核對預設價格與可調整範圍，另行儲存。", "重新開啟確認；付款聯繫資訊需到店家資料核對官方 LINE。"],
    important: "銀行資訊與體驗價格是不同設定；每區都需確認儲存成功。",
    details: ["銀行編輯需要方案編輯權限，體驗設定另受對應權限限制；沒有按鈕時請有權限者處理。", "體驗設定套用新體驗單，不表示已收款或已完成出席；不要拿舊交易金額驗證新預設。"],
    success: "銀行與體驗設定保留正確，新流程顯示對應資訊。",
    permission: "plans.edit", feature: null, modules: ["course"], kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/settings-workspace.tsx", "src/server/actions/course-settings.ts"],
  },
];
