import type { OperationGuide } from "./operation-guide-types";

/** Course instructions use the course actions, never the steamfoot wallet rules. */
export const courseOperationGuides: OperationGuide[] = [
  {
    id: "C101", category: "booking", title: "共卡會員只替另一位學員預約，怎麼操作？",
    summary: "先選實際上課者，再核對使用方案與占用額度。", answer: "預約人可以不上課；名額與額度依實際上課者計算。",
    keywords: "共卡 代約 多人 本人 學員 點數", path: "會員專區 → 預約課程 → 誰要上課？",
    steps: ["選日期與課程，點預約。", "只勾選要上課的已授權共卡成員；本人不上課就不要勾本人。", "核對上課者、適用方案及總占用額度，再確認預約。"],
    important: "共卡授權不會開放其他成員的健康資料，也不會授予教練權限。",
    success: "我的預約依同堂課合併，學員逐人列出，能辨識本人與代約。",
    details: ["方案必須未過期、適用該課程且可用額度足夠；預約先占用，完成出席才正式使用。", "滿班或送出時額度已被使用會拒絕預約，不能以畫面先前顯示的餘額為準。"],
    permission: "booking.read", feature: null, sources: ["src/app/(customer)/book/course-portal-client.tsx", "src/server/services/course-booking.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C102", category: "booking", title: "同堂多人只取消其中一人，怎麼處理？",
    summary: "核對學員姓名後逐人取消，保留其他學員。", answer: "個別取消與取消整堂課是不同操作。",
    keywords: "取消 釋放 占用 歷史 共卡", path: "課表排程 → 選課程 → 學員名單",
    steps: ["選日期並打開課程名單，核對實際上課者。", "在該學員列選取消預約，確認姓名。", "核對該筆狀態、剩餘名額與額度占用；其他學員不應被取消。"],
    important: "不要誤選「取消整堂課」。取消预約不等於退款。",
    success: "該學員轉為已取消並釋放占用，歷史紀錄仍保留。",
    details: ["會員自行取消受本店取消期限限制；已完成出席不能直接當成未上課取消。", "會員已取消紀錄預設收合，展開歷史仍可查看。"],
    permission: "booking.update", feature: null, sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/actions/course-members.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C103", category: "booking", title: "報到、完成與未到，額度有什麼差別？",
    summary: "報到保留占用，完成才使用額度。", answer: "先核對上課者，再使用當下可操作的出席狀態。",
    keywords: "報到 出席 完成 扣點 未到 點名 更正", path: "課表排程 → 課程名單；教練前台 → 我的工作 → 名單／點名",
    steps: ["開啟課程名單，核對姓名與目前狀態。", "學員到場可報到；課程完成後再操作完成出席。", "未到使用未到操作；誤操作時依畫面提供的更正入口與限制處理。"],
    important: "報到不扣點。不要為了更正而另建同一學員的重複預約。",
    success: "完成後狀態與額度紀錄一致；重送不應再次扣點。",
    details: ["目前未到會釋放占用，沒有另外收取未到費用。", "教練僅能處理被授權的自身課程，操作受上課時間限制；卡片已退款等狀態不能任意回補額度。"],
    permission: "booking.update", feature: null, sources: ["src/server/services/course-booking.ts", "src/server/actions/course-portal.ts"], kind: "explanation", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C104", category: "hours", title: "公休或縮短可預約日期，為什麼不能儲存？",
    summary: "先處理受影響課程或預約，再調整設定。", answer: "有衝突時整批拒絕，不會偷偷取消課程與學員。",
    keywords: "公休 營業 特殊日 開放期限 衝突", path: "設定 → 營業／公休",
    steps: ["選日期調整營業時間、公休或預約開放期限。", "核對預覽並儲存；若提示衝突，查看指出的日期與課程。", "回到課表處理受影響課程，再重新檢查設定。"],
    important: "公休不能覆蓋已排課的時間；縮短開放期限不能留下期限外的有效會員預約。",
    success: "成功儲存後月曆與會員可預約範圍符合設定。",
    details: ["特定日期優先於每週規則，回復預設會移除當日覆寫。", "開放期限限制會員新增預約，店長代約沿用後台例外；不會因此放寬教室容量或撞期限制。"],
    permission: "business_hours.manage", feature: null, sources: ["src/server/actions/course-business-hours.ts", "src/server/actions/course-booking-window.ts"], kind: "troubleshooting", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C105", category: "money", title: "尚未使用的課程方案如何全額退款？",
    summary: "核對原購買、卡片使用與占用，再填寫退款原因。", answer: "目前支援未使用且無占用的全額退款；部分使用退款尚未開放。",
    keywords: "退款 實付 退費 作廢 方案", path: "營運 → 購買明細 → 全額退款",
    steps: ["找到原核帳購買，核對實付金額與使用方案。", "確認卡片未使用、無預約占用且符合畫面檢查，再填寫退款原因送出。", "核對訂單、卡片結清、退款紀錄與收支結果。"],
    important: "累計退款不得超過實付。系統記錄退款不代表銀行已自動匯款，實際退款需另行核對。",
    success: "退款紀錄保留，該卡停用、可用額度為零，收支與訂單一致。",
    details: ["額外贈送、額度異動、部分使用或收款不一致可能阻擋，請依錯誤說明核對。", "同一退款重送不會再次退款；不要為了繞過檢查另建購買。"],
    permission: "transaction.refund", additionalPermissions: ["transaction.read"], feature: null, sources: ["src/server/services/course-refund.ts", "src/app/(dashboard)/dashboard/revenue/_components/course-transaction-actions.tsx"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C106", category: "care", title: "課程提醒會寄給誰？怎麼確認有沒有送達？",
    summary: "上課提醒給實際學員，店長通知另行指定收件人。", answer: "通知需啟用規則、具備店家功能與額度，並有有效 LINE 連結。",
    keywords: "LINE 提醒 通知 收件人 發送 紀錄", path: "設定 → 提醒管理",
    steps: ["在顧客提醒編輯課程上課提醒並核對開關。", "需要店長當日預約或待核帳通知時，到店長通知設定授權收件人與偏好。", "到發送紀錄核對對象與狀態；跳過或失敗不代表送達。"],
    important: "上課提醒給實際上課者，不會因共卡而寄給其他成員；隔離預覽不向外發送。",
    success: "設定成功後重新開啟仍保留；實際送達需以成功紀錄及收件端確認。",
    details: ["課程上課提醒於前一日18:00處理，取消預約不發送。", "儲存文字不會自動啟用；店長 LINE 收件人必須另行授權，教練身分不會自動加入。"],
    permission: "business_hours.manage", feature: "line_reminder", sources: ["src/server/services/course-reminders.ts", "src/server/services/course-manager-notifications.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
];
