import type { OperationGuide } from "./operation-guide-types";

/** Course instructions use the course actions, never the steamfoot wallet rules. */
export const courseOperationGuides: OperationGuide[] = [
  {
    id: "C101", category: "booking", title: "共卡會員只替另一位學員預約，怎麼操作？",
    summary: "先選實際上課者，再核對使用方案與占用額度。", answer: "預約人可以不上課；名額與額度依實際上課者計算。",
    keywords: "共卡 代約 多人 本人 學員 點數", path: "會員專區 → 預約課程 → 誰要上課？",
    steps: ["選日期與課程，點預約。", "只勾選要上課的已授權共卡成員；本人不上課就不要勾本人。", "核對上課者、適用方案及總占用額度，再確認預約。"],
    important: "共卡授權不會開放其他成員的健康資料，也不會授予教練權限。",
    success: "我的預約依同堂課合併，學員逐人列出，能辨識本人與代約。",
    details: ["方案必須未過期、適用該課程且可用額度足夠；預約先占用，完成出席才正式使用。", "滿班或送出時額度已被使用會拒絕預約，不能以畫面先前顯示的餘額為準。"],
    permission: "booking.read", feature: null, sources: ["src/app/(customer)/book/course-portal-client.tsx", "src/server/services/course-booking.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C102", category: "booking", title: "同堂多人只取消其中一人，怎麼處理？",
    summary: "核對學員姓名後逐人取消，保留其他學員。", answer: "個別取消與取消整堂課是不同操作。",
    keywords: "取消 釋放 占用 歷史 共卡", path: "課表排程 → 選課程 → 學員名單",
    steps: ["選日期並打開課程名單，核對實際上課者。", "在該學員列選取消預約，確認姓名。", "核對該筆狀態、剩餘名額與額度占用；其他學員不應被取消。"],
    important: "不要誤選「取消整堂課」。取消預約不等於退款。",
    success: "該學員轉為已取消並釋放占用，歷史紀錄仍保留。",
    details: ["會員自行取消受本店取消期限限制；已完成出席不能直接當成未上課取消。", "會員已取消紀錄預設收合，展開歷史仍可查看。"],
    permission: "booking.update", feature: null, sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/actions/course-members.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C103", category: "booking", title: "報到、完成與未到，額度有什麼差別？",
    summary: "自由預約報到保留占用、完成才使用額度；固定期課未到仍扣堂。", answer: "先確認是自由預約或固定期課，再核對上課者與可操作的出席狀態。",
    keywords: "報到 出席 完成 扣點 未到 點名 更正 固定期課", path: "課表排程 → 課程名單；教練前台 → 我的工作 → 名單／點名",
    steps: ["開啟課程名單，核對姓名與目前狀態。", "教練前台在開課後直接選出席或未到；店長後台若使用報到，報到只留下到場時間，不扣額度。", "誤操作時使用更正，回到待點名後再依實際結果處理。"],
    important: "報到不扣點。固定期課未到會扣堂；不要為了更正而另建同一學員的重複預約。",
    success: "完成後狀態與額度紀錄一致；重送不應再次扣點。",
    details: ["自由預約未到會釋放占用；固定期課依指定課次扣堂，未到不提供補課券，更正才返還。", "教練僅能處理被授權的自身課程，操作受上課時間限制；卡片已退款等狀態不能任意回補額度。"],
    permission: "booking.update", feature: null, sources: ["src/server/services/course-booking.ts", "src/server/actions/course-portal.ts"], kind: "explanation", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C104", category: "hours", title: "公休或縮短可預約日期，為什麼不能儲存？",
    summary: "先處理受影響課程或預約，再調整設定。", answer: "有衝突時整批拒絕，不會偷偷取消課程與學員。",
    keywords: "公休 營業 特殊日 開放期限 衝突 每週營業 設定視窗", path: "設定 → 營業與預約 → 營業／公休／預約開放",
    steps: ["在設定的「營業與預約」找到營業／公休／預約開放，於桌機／平板置中視窗或手機滿版視窗調整每週或指定日期。", "核對預覽並儲存；若提示衝突，查看指出的日期與課程。", "回到課表處理受影響課程，再重新檢查設定。"],
    important: "公休不能覆蓋已排課的時間；縮短開放期限不能留下期限外的有效會員預約。",
    success: "成功儲存後月曆與會員可預約範圍符合設定。",
    details: ["特定日期優先於每週規則，回復預設會移除當日覆寫；每週營業可一次編輯後批次儲存。", "開放期限限制會員新增預約，店長代約沿用後台例外；不會因此放寬教室容量或撞期限制。"],
    permission: "business_hours.manage", feature: null, sources: ["src/server/actions/course-business-hours.ts", "src/server/actions/course-booking-window.ts"], kind: "troubleshooting", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C105", category: "money", title: "課程方案如何登錄協商退款？",
    summary: "核對實付、已退款、剩餘與占用，再輸入協商金額。", answer: "有退款權限的店長可登錄實際退款金額，累計不得超過原實付。",
    keywords: "退款 實付 退費 作廢誤建交易 原交易明細 退款試算 選用 停用方案", path: "營運 → 購買明細 → 登錄退款",
    steps: ["找到原核帳購買，核對已退款及尚可退款；需要查原資料時展開「原交易明細」。", "先處理預約占用，再填退款金額、方式及原因；「退款試算（選用）」不會自動帶入金額。", "核對收回全部剩餘額度的提示，點「登錄退款並停用方案」，再查看原交易與退款紀錄；系統不會自動退刷或轉帳。"],
    important: "累計退款不得超過實付。系統記錄退款不代表銀行已自動匯款，實際退款需另行核對。",
    success: "退款紀錄保留，該卡停用、可用額度為零，收支與訂單一致。",
    details: ["贈送額度不折算現金。參考金額不強制限制協商結果，但累計退款上限仍是實付。", "同一退款重送不會再次退款；已結清卡若尚有可退款金額可補登，不會再次收回額度。現金方式需今日抽屜已開店。", "建錯或重複交易才用「作廢誤建交易」，須無預約及額度異動，填原因後「確認作廢」；另需作廢權限。實際退還款項不能用作廢冒充退款。"],
    permission: "transaction.refund", additionalPermissions: ["transaction.read"], feature: null, sources: ["src/server/services/course-refund.ts", "src/app/(dashboard)/dashboard/revenue/_components/course-transaction-actions.tsx"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C106", category: "care", title: "課程提醒會寄給誰？怎麼確認有沒有送達？",
    summary: "上課提醒給實際學員，店長通知另行指定收件人。", answer: "通知需啟用規則、具備店家功能與額度，並有有效 LINE 連結。",
    keywords: "LINE 提醒 通知 收件人 發送 紀錄", path: "設定 → 提醒管理",
    steps: ["在顧客提醒編輯課程上課提醒，並依方案設定低額度門檻與到期前天數。", "需要店長當日預約或待核帳通知時，到店長通知設定授權收件人與偏好。", "到發送紀錄核對對象與狀態；跳過或失敗不代表送達。"],
    important: "上課提醒給實際上課者，不會因共卡而寄給其他成員；隔離預覽不向外發送。",
    success: "設定成功後重新開啟仍保留；實際送達需以成功紀錄及收件端確認。",
    details: ["課程上課提醒於前一日18:00處理，取消預約不發送。低額度依可用額度（剩餘扣除占用）判斷；到期提醒須同時開啟總開關與方案設定。", "儲存文字不會自動啟用；店長 LINE 收件人必須另行授權，教練身分不會自動加入。", "發送紀錄顯示已略過時，先看原因，例如隔離預覽不外發、提醒額度已用完或 LINE 身分／通道未確認；失敗或略過不能當成送達，也不要直接重發全店通知。"],
    permission: "business_hours.manage", feature: "line_reminder", sources: ["src/server/services/course-reminders.ts", "src/server/services/course-manager-notifications.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C107", category: "booking", title: "新課程要先設定哪些資料？",
    summary: "先建立課程預設值，再用預設值排出實際課次。", answer: "課程設定是排課範本；修改範本不會回寫已排好的課次。",
    keywords: "新增課程 課程設定 課型 團課 私課 點數 人數 預設教室 上架 隱藏 下架 批次停用 刪除", path: "店務設定 → 課程設定 → ＋ 新增課程",
    steps: ["輸入課程名稱、課型、分類、時間、人數上限及每人點數。", "視需要選預設教室，填寫課程介紹與注意事項，並選擇上架、隱藏或下架。", "儲存後到課表排程建立實際日期、教練與教室；返回課程清單核對狀態。"],
    important: "範本的時間、容量與點數只是之後排課的預設值；已排課次保留建立當時的快照。",
    success: "課程出現在課程設定清單，狀態與扣抵預設正確，並可用於新增排課。",
    details: ["團課與私課是必填課型；點數卡依每人點數扣抵，堂數卡每人每堂使用 1 堂。", "可勾選多筆批次上／下架；只有店長可刪除完全未使用的項目，已有方案、教練資格、排課或歷史時會整批阻擋，請改用下架。"],
    permission: "booking.create", additionalPermissions: ["booking.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/lib/course-scheduling.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C108", category: "booking", title: "如何新增教室並設定容納人數？",
    summary: "建立教室名稱、位置與容量後，才能在排課時選用。", answer: "教室容量是排課警示與後續調整依據，不會自動增加課程名額。",
    keywords: "新增教室 教室管理 場地 容量 設備 位置 停用 批次 刪除", path: "店務設定 → 教室管理 → ＋ 新增教室",
    steps: ["輸入教室名稱、分類與容納人數，可補位置、設備及備註。", "儲存後返回教室清單，確認教室為啟用。", "排課時再選教室並核對該堂課的人數上限。"],
    important: "教室已有未結束課次時，不能直接停用；縮小容量也不能低於仍在使用的排課需求。",
    success: "教室出現在教室管理與排課選單，名稱、容量及狀態正確。",
    details: ["同一教室的重疊時段會被阻擋；教室容量較小時系統會提示，但課程本身的人數上限仍需另行設定。", "可勾選多筆批次啟用／停用；只有店長可刪除完全未使用的教室，使用中或有歷史關聯時整批不刪除。"],
    permission: "booking.create", additionalPermissions: ["booking.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/server/actions/course.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C109", category: "booking", title: "怎麼一次排單堂、每週或多個指定日期？",
    summary: "選課程、教練、教室與日期，先看預覽再整批建立。", answer: "每週重複與指定日期都會整批檢查；其中一堂衝突時整批不建立。",
    keywords: "新增排課 批次排課 每週 重複 指定日期 複製 預覽 衝突", path: "課表排程 → 新增排課／複製課程",
    steps: ["選課程、教練、教室、開始時間與人數上限。", "選單堂、每週至某日，或加入其他指定日期，再執行排課預覽。", "逐筆核對日期、營業時間、值班、教練與教室衝突後，確認建立。"],
    important: "預覽通過不保證稍後仍可儲存；正式送出會在鎖定店家資料後重新檢查全部日期。",
    success: "顯示建立堂數，所有日期都出現在課表；不會只建立無衝突的一部分。",
    details: ["同一教練或教室時段重疊、超出營業時間、值班未涵蓋或資源停用都會阻擋。", "重送同一請求不會建立重複課次；若資料已變更，請重新開啟表單。"],
    permission: "booking.create", additionalPermissions: ["booking.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/server/actions/course.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C110", category: "booking", title: "排好的課程要改時間、容量或取消，先看什麼？",
    summary: "先看有效預約與點名狀態，再決定修改單堂、後續系列或取消。", answer: "已有預約或完成點名時，部分欄位會被保護，不能直接覆蓋歷史。",
    keywords: "修改排課 改時間 改教練 改教室 容量 取消課程 系列 後續課次", path: "課表排程 → 選課程 → 編輯／取消",
    steps: ["打開課次，核對日期、學員數、點名狀態及它是否屬於系列。", "依畫面選修改單堂或後續系列，重新核對教練、教室、容量與時間。", "預覽並儲存；若要取消，先確認有效預約會如何處理，再查看課表與學員紀錄。"],
    important: "已完成點名的課次保留歷史不可修改；有預約時不能把容量調到低於人數，也不能改每人點數或課程種類。",
    success: "指定範圍的課次更新或取消，其他課次不受影響，原預約與額度紀錄一致。",
    details: ["改期若超過學員方案期限會被阻擋；教練、教室、營業時間與值班會重新檢查。", "取消整堂課與只取消一位學員不同；取消也不等於退款。"],
    permission: "booking.update", additionalPermissions: ["booking.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/server/actions/course.ts"], kind: "troubleshooting", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C111", category: "plans", title: "如何建立點數或堂數方案？",
    summary: "選額度單位、額度、售價、成本、效期與適用課程，再決定是否上架。", answer: "點數方案按課程點數扣抵；堂數方案每位學員每堂使用 1 堂，固定期課另需連結指定課次。",
    keywords: "新增方案 點數 堂數 售價 店家成本 有效天數 適用課程 顧客可購買 僅後台指派 允許共卡 上架 下架 固定期課", path: "店務設定 → 方案管理 → ＋新增方案",
    steps: ["輸入方案名稱，選點數或堂數，填額度、售價、店家成本與有效天數。", "勾選適用課程，再選「顧客可購買／僅後台指派」及是否允許共卡；固定期課需連結與堂數相同的未開始課次。", "選上架或下架後儲存，回到清單核對額度單位、使用方式、成本、期課與狀態。"],
    important: "修改方案預設不會改動已指派給顧客的卡片；目前沒有自動續費。",
    success: "方案出現在清單，額度單位、價格、效期、適用課程與狀態正確。",
    details: ["下架只阻止後續選購或指派，不會刪除既有卡片及歷史；「僅後台指派」不會出現在會員購買頁。成本用於本次結帳分配與低於成本阻擋。", "只有勾選允許共卡的方案可新增授權成員；堂數卡不使用課程點數，固定期課另受指定課次限制。"],
    permission: "plans.edit", additionalPermissions: ["wallet.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/server/actions/course-members.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C112", category: "plans", title: "店內購買方案並結帳，怎麼處理？",
    summary: "選顧客、方案、效期與本次開發人，再核對優惠、實收及收款方式。", answer: "「購買方案」確認結帳會同時完成發卡、購買與收款登記；全額折抵保留購買與方案，但不建立收入。",
    keywords: "指派方案 購買方案 確認結帳 現金抽屜 重新確認 折扣 打折 折抵 轉帳 後四碼 店家成本 開發人", path: "顧客管理 → 顧客詳情 → 持有方案 → 購買方案",
    steps: ["從顧客詳情點「購買方案」（原指派方案），核對學員、上架方案、效期與本次開發人。", "選優惠與已收款方式；轉帳填後四碼。現金且實收大於零時，先等畫面確認今日現金抽屜已開啟。", "抽屜未開時可另開新分頁處理，回來按「重新確認」；若已結帳先依權限處理，不改填別種付款方式繞過。", "核對實收後點「確認結帳」一次，看到「結帳完成，方案已加入」，再查持有方案與原交易。"],
    important: "這個按鈕會同時發卡並登記收款，不是單純增加額度。連線中斷先查原交易，不要直接重按。",
    success: "只新增一張卡、一筆購買與一筆對應收款；顧客、效期、實收與本次開發人快照正確。",
    details: ["從顧客進入時會帶入其直屬店長作為本次開發人，可依實際成交調整；沒有用核帳人自動代替。使用折扣另需折扣權限。", "實收不能低於店家成本；成本為 0 的全額折抵不要求付款方式，也不建立收入。現金需今日抽屜已開啟。"],
    permission: "wallet.create", additionalPermissions: ["transaction.create", "customer.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/components/admin/course-assignment-payment.tsx", "src/server/actions/course-checkout-status.ts", "src/server/services/course-assignment-checkout.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C113", category: "money", title: "會員線上回報轉帳後，店家如何核帳？",
    summary: "在待核帳區核對顧客、方案、金額與轉出帳號後四碼，再確認收款並啟用。", answer: "會員回報轉帳只建立待核帳購買；店家確認後才發卡與啟用額度。",
    keywords: "線上購買 待核帳 轉帳 後四碼 確認已收款 啟用方案", path: "方案管理 → 線上購買待核帳 → 核帳",
    steps: ["找到待核帳購買，核對顧客、方案、金額與轉出帳號後四碼。", "先查實際入帳，再點核帳並二次確認「確認已收款並啟用」。", "看到已核帳訊息後，核對顧客卡片、額度與交易紀錄。"],
    important: "後四碼相符不等於款項一定入帳；未查帳前不要啟用，也不要因連線中斷直接重按。",
    success: "待核帳項目消失，方案卡啟用且只新增一次額度與購買紀錄。",
    details: ["同一購買請求只能核帳一次；若畫面中斷，先重新整理查結果。", "這個流程是課程模組購買，與蒸足方案付款確認頁分開。"],
    permission: "wallet.create", additionalPermissions: ["wallet.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/purchase-review.tsx", "src/server/actions/course-portal.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C114", category: "staff", title: "新增教練後，為什麼還不能排課或登入我的工作？",
    summary: "授課資格、每堂固定費、教練工作身分與會員登入連結是分開設定。", answer: "先啟用教練身分、可教授課程與每堂固定費；要登入「我的工作」還需連結本店既有顧客帳號。",
    keywords: "新增教練 授課資格 可教授課程 每堂固定費 授課費 我的工作 登入 會員連結 店長兼教練", path: "店務設定 → 人員與權限 → 新增／編輯人員 → 授課費設定",
    steps: ["新增或打開人員，啟用教練工作身分並設定緊急聯絡資料。", "在授課費設定勾選可教授課程，逐項填每堂固定費後一次儲存。", "需要使用教練前台時，連結已完成本店會員登入的顧客，再核對「已開通教練登入」。"],
    important: "授課資格不會自動建立登入；連結顧客也不會自動授予店長後台權限。",
    success: "排課可選到該教練；有登入需求者能從自己的課程店入口開啟「我的工作」。",
    details: ["停用或移除授課資格前，先處理尚未結束的課次與交接清單；新費率只套用之後排出的課次，不回寫既有課次快照。", "只有店主且具人員管理權限可管理此頁；教練不建立蒸足 PARTNER 帳號。設定 0 元表示該課程不另領授課費。"],
    permission: "staff.manage", additionalPermissions: ["staff.view"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/staff-workspace.tsx", "src/server/actions/course-staff.ts"], kind: "troubleshooting", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C115", category: "analysis", title: "課程分析的上課、收款與回流數字怎麼看？",
    summary: "先選期間與分析對象，再分開看來客人次、去重人數、成交、收款與近六個月營收結構。", answer: "來客人次按完成出席堂次累加；方案與體驗收退款按入帳時間，營業額、收支結餘與出席不能直接當成同一數字。",
    keywords: "營運分析 報表 匯出 CSV 來客人次 不重複人數 直屬店長 教練 回流 收款 營業額 營收結構 收支結餘 近六個月 近一年", path: "分析 → 營運分析",
    steps: ["選今日、本月或自訂日期，確認頁首台灣時間範圍，再選店家、直屬店長或教練。", "分開查看來客人次、體驗、新卡、續卡、回流、收款、利潤與授課費；點卡片可看名單或每人出席堂數。", "在店家視角查看固定近六個月的營業額、收支結餘、方案、零售、其他收入與支出；具匯出權限者可下載所選日期與權限範圍的 CSV。"],
    important: "同一人同日上兩堂計 2 人次；「不重複來客人數」才是期間去重。團體同堂有兩位實際出席就計 2 人次。",
    success: "所選期間、比較期間與各區塊口徑一致，匯出檔使用相同日期範圍。",
    details: ["方案依核帳／退款日，體驗依收款／沖銷日；直屬店長的出席依顧客目前歸屬，成交依購買時快照，未指定列未歸屬。", "查看金額、顧客名單、授課費、收支及匯出各受額外權限控制；沒有權限時不顯示，不代表資料為零。共用財務圖固定近六個月、本月統計至今日，上方日期只影響摘要；原課程趨勢依其頁面期間說明。"],
    permission: "report.read", feature: "basic_reports", sources: ["src/app/(dashboard)/dashboard/courses/analytics-page.tsx", "src/server/queries/course-analytics.ts"], kind: "explanation", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C116", category: "money", title: "課程體驗的收款、出席與作廢為什麼要分開？",
    summary: "先登記體驗收款，再依實際上課狀況點名；兩個動作互不代替。", answer: "收款不會自動完成出席，出席也不會再次收費或使用其他方案額度。",
    keywords: "體驗 收款 混合付款 報到 出席 作廢 沖銷 更正 無卡 未收款 已收", path: "課表排程 → 上課名單 → 體驗學員列的收款／點名",
    steps: ["在體驗學員列核對金額與未收款標示，點旁邊的「收款」登記實際付款；已收者顯示已收金額。", "學員到場及課程結束後，另依實際狀況操作報到、出席或未到。", "收款登記錯誤時使用更正收款或作廢，填原因後核對歷史與收支；不要用取消預約代替帳務更正。"],
    important: "作廢只沖銷收款，保留原紀錄及出席狀態；系統不會自動銀行退刷。",
    success: "付款狀態、出席狀態及收支紀錄各自正確；體驗沒有建立方案額度異動。",
    details: ["體驗預約無卡且每人點數為 0；已支付的同堂出席不再扣其他方案。", "重送同一收款不會重複入帳；連線中斷時先查原紀錄再決定是否重試。"],
    permission: "booking.read", additionalPermissions: ["trial.confirm"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/services/course-trial-payment.ts"], kind: "explanation", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C117", category: "customers", title: "會員登入後看不到本店課程或方案，先查什麼？",
    summary: "先確認從正確課程店入口登入，再核對帳號是否連結本店顧客。", answer: "課程會員身分按店別連結；同名、同電話或其他店登入不會自動取得本店資料。",
    keywords: "會員登入 看不到課程 看不到方案 帳號尚未連結 本店顧客 LINE 店別 身分衝突", path: "顧客管理 → 顧客詳細資料；會員專區 → 我的",
    steps: ["請會員確認是從這間課程店的網頁或 LINE 入口登入。", "在顧客管理查本店顧客與 LINE／帳號連結狀態，避免建立重複顧客。", "若顯示帳號尚未連結或身分衝突，使用既有身分確認流程處理，不以姓名或電話猜測覆蓋。"],
    important: "不要為了排錯解除其他人的 LINE、重建同名顧客，或把其他店的會員資料直接搬入。",
    success: "會員重新進入本店入口後，可看到屬於本店且已授權的課程、預約與方案。",
    details: ["共卡授權只開放使用該卡預約，不會開放其他成員健康資料。", "教練若只開放工作身分，會員操作可能被停用；店家需在工作入口與會員連結設定核對。", "已有蒸管家 LINE 帳號但尚未加入這間課程店時，符合條件可依本店畫面填姓名與電話完成加入；已有本店資料或身分衝突時需人工核對，不能用同名同電話直接覆蓋。暫時服務失敗請保留提示，確認後再試。"],
    permission: "customer.read", feature: null, sources: ["src/app/(customer)/book/course-portal.tsx", "src/server/services/course-access.ts", "src/server/services/course-line-onboarding.ts"], kind: "troubleshooting", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C118", category: "plans", title: "共卡成員要怎麼新增或移除？",
    summary: "先打開顧客持有方案，再搜尋並儲存同店授權成員。", answer: "共卡成員共享同一張卡的可用額度；固定期課不開放共卡。",
    keywords: "共卡 授權成員 新增成員 移除成員 搜尋顧客 占用 固定期課", path: "顧客管理 → 顧客詳情 → 持有方案 → 方案與共卡",
    steps: ["打開顧客的持有方案，選正確卡片並等待詳細資料載入完成。", "在共卡授權成員輸入姓名或電話；明確點選正確候選再勾選，搜尋框按 Enter 不會自動選第一位。", "儲存後重新開啟，核對成員、剩餘、已預約占用與可用額度。"],
    important: "移除成員前先處理該成員或代約人的有效預約；系統會阻擋留下無權使用卡片的預約。",
    success: "卡片只保留正確同店成員，原額度與使用紀錄沒有被重建。",
    details: ["搜尋只會回傳部分結果，必須選到實際顧客，不能只輸入姓名；共卡不開放彼此健康資料。", "固定期課綁定指定學員與課次，不能加入共卡成員；請另購自由預約方案。"],
    permission: "wallet.create", additionalPermissions: ["wallet.read", "customer.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/components/admin/course-customer-picker.tsx", "src/server/actions/course-members.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C119", category: "plans", title: "固定期課方案怎麼建立與指派？",
    summary: "使用堂數方案，連結與販售堂數相同的未開始課次。", answer: "固定期課結帳時一次預約全期；未到仍扣堂，不能改用其他課次或共卡。",
    keywords: "固定期課 期課 整期預約 指定課次 堂數 未到扣堂 補課券", path: "方案管理 → 新增／編輯方案 → 期課：連結指定課次",
    steps: ["建立堂數方案，設定販售堂數與適用課程。", "展開期課設定，選擇相同堂數、尚未開始且互不重疊的課次後儲存。", "指派並結帳時核對固定期課堂數；完成後確認整期課次都已預約。"],
    important: "任一堂預約失敗時整筆不發卡、不收款也不保留部分預約。已有購買紀錄的期別不可直接改課次。",
    success: "卡片顯示指定課次，整期預約數等於方案堂數，名單可辨識第 N／共 N 堂。",
    details: ["固定期課不能共卡；預約只限方案指定課次。未到仍扣 1 堂，更正未到會返還，沒有補課券。", "要更換已有購買的期別，請建立下一期新方案，保留原購買與課次歷史。"],
    permission: "plans.edit", additionalPermissions: ["booking.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/server/services/course-term.ts", "src/server/services/course-assignment-checkout.ts", "src/server/services/course-booking.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C120", category: "care", title: "每個課程方案的低額度與到期提醒怎麼設定？",
    summary: "在提醒管理逐一設定低額度門檻與到期前天數，再一次儲存。", answer: "每張卡依可用額度與該方案的天數判斷；到期提醒還需要總開關啟用。",
    keywords: "低額度提醒 到期提醒 方案提醒 門檻 到期天數 14 7 可用額度", path: "設定 → 通知與顧客經營 → 提醒管理 → 顧客提醒",
    steps: ["搜尋方案，勾選低額度提醒並填門檻。", "勾選到期提醒，輸入逗號分隔的天數，例如 14, 7；確認上方到期提醒總開關已開。", "儲存全部修改，重新開啟並用預覽核對方案名稱、單位與提醒階段。"],
    important: "預覽是示意，不會證明 LINE 已送達；隔離預覽不向外發送。",
    success: "頁面顯示所有設定已儲存，重新開啟後各方案門檻與天數仍正確。",
    details: ["低額度用剩餘扣除已預約占用後的可用額度判斷；每卡每位成員提醒一次。", "到期天數限 1–365 天、最多 6 次；更改天數不補發已錯過階段，也不會變更方案期限。"],
    permission: "business_hours.manage", feature: "line_reminder", sources: ["src/app/(dashboard)/dashboard/courses/reminders/low-balance-settings.tsx", "src/server/actions/course-plan-reminders.ts", "src/server/services/course-expiry-reminders.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C121", category: "care", title: "首頁顯示「未指派方案」，要怎麼處理？",
    summary: "打開站內待辦名單，核對顧客後再進顧客頁購買方案。", answer: "這是尚無本店課程方案紀錄的站內待辦，不會自動傳 LINE，也不代表顧客欠款。",
    keywords: "未指派方案 顧客方案待辦 沒有方案 站內提醒 不發LINE", path: "首頁 → 顧客方案待辦；設定 → 通知與顧客經營 → 未指派方案提醒",
    steps: ["打開未指派方案名單，核對姓名、電話末四碼、建檔日與直屬店長。", "進入顧客詳情查既有卡片、待核帳與歷史，避免重複購買。", "確定需要購買時點「購買方案」，依實際收款「確認結帳」；返回名單重新整理。"],
    important: "不要把名單當成催款名單或直接群發通知；本功能目前只讀、不自動建立方案或交易。",
    success: "完成有效指派後重新整理，該顧客移出名單；未處理者仍保留。",
    details: ["已有共卡成員、待核帳、已核帳／退款訂單、到期／用完／結清卡或持卡預約歷史者不列入；純教練帳號也排除。", "名單沿用店別與直屬店長可見範圍，需要顧客與方案查看權限；查詢失敗不顯示假零人。"],
    permission: "customer.read", additionalPermissions: ["wallet.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/unassigned-plans/page.tsx", "src/server/queries/course-unassigned-plans.ts", "src/app/(dashboard)/dashboard/courses/settings-workspace.tsx"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C122", category: "money", title: "教練每堂授課費如何登錄已付或更正？",
    summary: "在收入總覽依期間展開授課費，核對已結束課次後登錄。", answer: "授課費按課次快照每堂固定一次；登錄已付只留帳，不會自動匯款。",
    keywords: "授課費 教練費 每堂固定 待付 已付 登錄已付 更正誤登 支出", path: "營運 → 收入總覽 → 授課費 → 展開明細",
    steps: ["選日期範圍並展開授課費，核對課次、教練、固定費與付款狀態。", "在待付課次點登錄已付，選現金或非現金並填付款備註後確認。", "若只是誤登，點更正誤登並填原因；另行確認實際匯款或款項收回。"],
    important: "登錄或更正都不是銀行付款／退款。現金付款需今日抽屜已開啟；連線中斷先重新整理查結果。",
    success: "付款狀態與備註正確，現金帳有對應支出；更正保留原付款及反向沖回紀錄。",
    details: ["只有已結束、未取消、費率為正整數且教練與快照一致的課次可登錄；0 元表示不另領。", "舊課次缺費率或小數金額會標成待核對；單次最多顯示 100 堂，超過時需縮短日期範圍。", "新版每月收入結算不再提供新增付款入口；原授課費付款仍從營運處理。月結可查看歷史付款，兩處共用同一紀錄，不要重複新增支出。"],
    permission: "cashbook.read", additionalPermissions: ["cashbook.create"], feature: null, sources: ["src/app/(dashboard)/dashboard/revenue/_components/course-fees.tsx", "src/app/(dashboard)/dashboard/revenue/_components/course-fee-payment-button.tsx", "src/server/services/course-fee-payment.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C123", category: "settings", title: "課程店的設定入口怎麼找？未儲存草稿會消失嗎？",
    summary: "設定分為五區；桌機用左側分類、手機用上方選單，細項使用桌機／平板置中視窗或手機滿版視窗。", answer: "切換設定分類會保留各區草稿；離開設定頁、關閉視窗或重新載入前仍要先儲存或確認捨棄。",
    keywords: "課程設定 五分類 置中視窗 平板 手機滿版 草稿 未儲存 店家資料 營業 收款 通知 系統方案", path: "設定",
    steps: ["桌機從左側、手機從設定分類選單切換店家資料、營業與預約、收款與體驗、通知與顧客經營、系統方案與用量。", "直接編輯目前區塊；營業、公休、提醒等細項會在桌機／平板置中視窗或手機滿版視窗開啟。", "確認未儲存標記後逐區儲存；要離開或關閉時依提示繼續編輯或捨棄。"],
    important: "分類切換保留草稿不等於已儲存；網路失敗後也要確認成功訊息與重新開啟結果。",
    success: "重新開啟後資料仍正確，未儲存標記消失，關閉視窗回到原設定分類。",
    details: ["儲存中的表單不能捨棄；關閉視窗、遮罩、Escape 與視窗內導覽會先處理草稿。", "入口仍受角色、權限、功能開通與總部檢視模式限制；看不到項目不代表設定被刪除。"],
    permission: "booking.read", feature: null, sources: ["src/app/(dashboard)/dashboard/courses/settings-workspace.tsx", "src/app/(dashboard)/dashboard/courses/settings-panel.tsx", "src/components/admin/settings-panel-context.tsx"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C124", category: "booking", title: "怎麼從課表替既有學員或新體驗客預約？",
    summary: "打開課次後選學員預約；找不到既有顧客時再切換建立新體驗客。", answer: "既有學員需選有效方案；新顧客可在名單直接建檔並建立未收款體驗預約。",
    keywords: "學員預約 新增體驗客 建立新顧客 有效方案 最快到期 直接預約 名單", path: "課表排程 → 打開課次 → ＋學員預約／＋體驗客",
    steps: ["打開正確日期與課次，選「＋學員預約」後搜尋姓名、電話或 LINE。", "選到既有學員後核對系統列出的可用方案；多張適用卡會優先帶入最快到期者，仍可手動更換。", "找不到顧客時切換建立新體驗客，填姓名、電話與體驗金額後確認；再回名單核對。"],
    important: "不要為找不到的人重複建檔；先改用電話或姓名搜尋。體驗預約只保留名額，收款與出席仍分開處理。",
    success: "學員出現在正確課次名單；一般預約占用正確方案，體驗客顯示尚未收款。",
    details: ["沒有適用方案時先到顧客詳情「購買方案」並確認結帳，不能用不適用或已到期卡硬約；送出時系統仍會重查額度與容量。", "新體驗客建檔需顧客建立及體驗預約權限；不會自動發卡或登記收款。"],
    permission: "booking.create", additionalPermissions: ["booking.read", "customer.read"], feature: null, sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/actions/course-members.ts"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
  {
    id: "C125", category: "plans", title: "會員如何用轉帳購買課程方案？",
    summary: "在會員專區選可購買方案，依店家銀行資訊匯款後填轉出帳號後四碼。", answer: "送出後只是待核帳；店家確認實際入帳，方案才會啟用。",
    keywords: "會員購買方案 線上購買 轉帳 後四碼 銀行資訊 待核帳 課程方案", path: "會員專區 → 購買方案",
    steps: ["選擇標示可購買且適用的方案，核對價格、額度、效期與店家銀行資訊。", "完成實際匯款後，輸入轉出帳號後四碼並送出一次。", "到購買紀錄查看待核帳；店家確認後，再到我的方案核對額度與期限。"],
    important: "送出回報不代表已付款完成或方案已啟用；查詢進度不要重複送出同一筆。",
    success: "購買紀錄出現一筆待核帳，核帳後才有一張有效方案卡。",
    details: ["只有上架且設為「顧客可購買」的方案會出現；僅供後台「購買方案」結帳使用的方案，不會因此開放會員自行購買。", "系統不會自動扣款；後四碼只供對帳，店家仍需查看實際入帳。舊資料欄位名稱雖保留，畫面與驗證均為四碼。"],
    permission: "customer.read", feature: null, sources: ["src/app/(customer)/book/course-portal-client.tsx", "src/server/actions/course-portal.ts", "src/app/(customer)/book/course-portal.tsx"], kind: "howto", modules: ["course"], verification: "source-reviewed",
  },
];
