import { priceCategories, type InventoryData } from "./inventory";
const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:number)=>escape("$"+n.toLocaleString("zh-TW"));
export const inventoryPrintCss=`@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font:14px/1.5 system-ui,sans-serif;color:#111;margin:0}.document{max-width:190mm;margin:auto}h1{font-size:20px;margin:0}h2{font-size:17px;margin:10px 0}p{margin:5px 0}table{width:100%;border-collapse:collapse;margin:12px 0;table-layout:fixed}th,td{border-bottom:1px solid #bbb;padding:7px 5px;text-align:right;overflow-wrap:anywhere}th:first-child,td:first-child{text-align:left;width:42%}thead{display:table-header-group}tr{break-inside:avoid}.totals{margin-left:auto;width:65mm;break-inside:avoid}.totals p{display:flex;justify-content:space-between;gap:12px}.note{white-space:pre-wrap;overflow-wrap:anywhere}footer{margin-top:18px;color:#666}@media print{.controls{display:none}}`;
/** Only already-authorized sale/receipt snapshots enter the printable document; never internal notes or costs. */
export function inventoryPrintBody(data:Pick<InventoryData,"store"|"orders"|"payments">,kind:string,id:string) {
 const sale=kind==="sale"?data.orders.find(o=>o.kind==="SALE"&&o.id===id):undefined;
 const receipt=kind==="receipt"?data.payments.find(p=>p.kind==="SALE"&&p.id===id):undefined;
 if(!sale&&!receipt)return null;
 const item=sale||receipt!;
 const header=`<h1>${escape(data.store.name)}</h1><p>${escape([data.store.phone,data.store.address].filter(Boolean).join("・"))}</p><h2>${sale?"銷貨明細":"收款明細"}</h2><p>單號 ${escape(id.slice(-8).toUpperCase())}　日期 ${escape(item.date)}</p><p>顧客 ${escape(item.partyName)}　電話 ${escape(item.partyPhone)}</p>`;
 const body=sale?`<p>身份價格：${escape(priceCategories[sale.priceCategory||"GENERAL"])}</p><table><thead><tr><th>商品</th><th>數量</th><th>單價</th><th>優惠</th><th>實際金額</th></tr></thead><tbody>${sale.lines.map(l=>`<tr><td>${escape([l.brand,l.name,l.specification].filter(Boolean).join("・"))}${l.gift?"（贈品）":""}</td><td>${l.quantity} ${escape(l.unit||"")}</td><td>${money(l.unitPrice)}</td><td>${l.gift?"贈送":l.discountMode==="PERCENT"?`折扣 ${l.discount}%`:l.discountMode==="AMOUNT"?`折抵 ${money(l.discount)}`:"—"}</td><td>${money(l.total)}</td></tr>`).join("")}</tbody></table><div class="totals"><p>商品金額 <b>${money(sale.total-sale.freight)}</b></p>${sale.freight?`<p>運費 <b>${money(sale.freight)}</b></p>`:""}<p>應收總額 <b>${money(sale.total)}</b></p><p>已收金額 <b>${money(sale.paid)}</b></p><p>尚欠金額 <b>${money(sale.total-sale.paid)}</b></p></div><p>交貨方式：${escape(sale.delivery)}${sale.channel?"・"+escape(sale.channel):""}</p>${sale.shippingNote?`<p class="note">寄送備註：${escape(sale.shippingNote)}</p>`:""}`:
 `<p>付款方式：${escape(receipt!.method)}</p><table><thead><tr><th>銷貨單號</th><th>本次收款</th><th>收款後尚欠</th></tr></thead><tbody>${receipt!.allocations.map(a=>`<tr><td>${escape(a.orderId.slice(-8).toUpperCase())}</td><td>${money(a.amount)}</td><td>${money(a.remainingAfter)}</td></tr>`).join("")}</tbody></table><div class="totals"><p>本次實收 <b>${money(receipt!.total)}</b></p><p>本單所列銷貨尚欠 <b>${money(receipt!.allocations.reduce((n,a)=>n+a.remainingAfter,0))}</b></p></div>`;
 return header+body+`<footer>${escape(new Date().toLocaleString("zh-TW",{timeZone:"Asia/Taipei"}))} 列印</footer>`;
}
export function inventoryPrintHtml(data:Pick<InventoryData,"store"|"orders"|"payments">,kind:string,id:string) {const body=inventoryPrintBody(data,kind,id);return body===null?null:`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><title>列印明細</title><style>${inventoryPrintCss}</style></head><body><article id="inventory-document" class="document">${body}</article></body></html>`;}
