import type { OperationGuide } from "./operation-guide-types";

/** Source review at 693c8446. No logged-in operation acceptance is implied. */
export const dailyOperationGuides20260930: OperationGuide[] = [
  {
    id: "B11", category: "hours", title: "同一組服務時段，怎麼套用到多個指定日期？",
    summary: "先完成來源日設定，再跨月複選 1～62 個未來日期；可保留或覆蓋目標日既有設定。",
    answer: "指定日期只建立各日特殊設定，不會改每週固定規則；儲存後可從完成提示立即復原本批操作。",
    path: "設定 → 營業與預約 → 選來源日期 → 套用其他日期 → 套用到指定日期",
    keywords: "複製時段 套用指定日期 多選日期 跨月 來源日期 保留原設定 略過 覆蓋 單一時段調整 復原",
    steps: ["選已設定好的來源日期，核對營業／公休狀態、服務時段與名額。", "展開套用其他日期，選「套用到指定日期」並跨月勾選目標日；決定既有設定要略過或覆蓋，以及是否包含來源日的單一時段調整。", "查看儲存前範圍與衝突處理說明，確認後儲存；逐日核對結果，誤套用時從完成提示點「復原」。"],
    important: "覆蓋會取代目標日整日設定與單一時段調整；既有預約不會自動取消。課程門市不使用此流程，需保留排課衝突檢查。",
    success: "來源日與實際完成的目標日顯示相同設定；略過日期會列出原因，每週固定規則與預約、收款、扣堂均未改變。",
    details: ["不可選過去日期或來源日，單次最多 62 個目標日。保留原設定時，有整日特殊設定或單一時段調整的日期會略過。", "整批由同一交易寫入；失敗不會只成功一半。復原只適用剛完成的同一批操作，若相關日期已被別人修改會拒絕覆蓋新版。", "蒸足與 SPA 服務時段可使用；課程模組應在課程營業設定與課表中處理。"],
    modules: ["steamfoot", "spa"], permission: "business_hours.manage", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/settings/hours/schedule-manager.tsx", "src/server/actions/business-hours.ts"],
  },
  {
    id: "I11", category: "settings", title: "總部怎麼查看一筆資料是誰、何時做了什麼操作？",
    summary: "HQ 管理員可從原資料旁查看最近操作；集中查詢及登入互查則使用「操作與登入紀錄」，另有獨立開通的 OWNER 本店唯讀紀錄，見 I20。",
    answer: "本題完整稽核與登入互查限 HQ ADMIN 且需 audit.read，只供追查；它們不提供還原，也不代表交易、付款或通知已完成。",
    path: "總部切換特定店舖 → 相關預約／課程名單／SPA 預約／現金帳／進銷存資料 → 查看紀錄",
    keywords: "操作紀錄 誰修改 最後操作 操作人 修改時間 修改前 修改後 稽核 歷史 紀錄中心 HQ 集中查詢 操作與登入紀錄 未記錄",
    steps: ["由具權限的 HQ 管理員切到要追查的門市，打開原始資料，核對顧客、日期或金額後點「查看紀錄」。", "查看最近操作的時間、姓名、當時身分與白話摘要，再核對實際異動欄位的前後值；缺少內容時依「未記錄」提示判讀。", "若要修正，關閉紀錄後回原功能走正式更正流程；需要查當次登入或跨筆篩選時，依 I12 到集中中心查詢。"],
    important: "操作紀錄是唯讀稽核資料，不能代替退款、取消、扣堂更正或實際通知。門市不取得 HQ 完整紀錄；獨立開通的 OWNER 本店業務紀錄見 I20；功能上線前的舊歷史不會補填操作人。",
    success: "HQ 能辨識正確門市的最近操作人、時間及變更內容；需更正的資料仍由原功能處理。",
    details: ["單筆入口目前顯示最近 20 筆；HQ 集中中心「操作與登入紀錄」每頁 50 筆，詳見 I12。沒有紀錄不表示資料從未存在，可能是功能上線前的歷史。", "單筆入口與集中中心都限 HQ ADMIN 與 audit.read，並依目前可查看的店別範圍處理；電話等敏感內容會遮蔽。", "內容用白話動作及異動欄位辨識資料；「異動內容未記錄」不是沒有做過操作。標示「目前資料」的名稱是目前資料來源，不應視為當時完整快照。", "店長與教練若標記為同一人，紀錄仍保留實際登入身分及當下姓名快照；系統自動操作會標示觸發人。"],
    modules: ["steamfoot", "spa", "course"], permission: "audit.read", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/components/operation-history-button.tsx", "src/components/operation-audit-access.tsx", "src/components/audit-changes.tsx", "src/lib/permissions.ts", "src/lib/audit-presentation.ts", "src/server/actions/operation-audit.ts", "src/server/services/operation-audit.ts", "src/app/(dashboard)/dashboard/operation-audits/page.tsx", "src/app/(dashboard)/dashboard/bookings/booking-detail-drawer.tsx", "src/app/(dashboard)/dashboard/spa-schedule/booking-summary.tsx", "src/app/(dashboard)/dashboard/courses/roster.tsx", "src/app/(dashboard)/dashboard/cashbook/page.tsx"],
  },
  {
    id: "C153", category: "plans", title: "音樂課程名稱與收費方案為什麼分開？怎麼建立？",
    summary: "課程管理只維護科目名稱、分類及上下架；收費方案另設定課型、每堂學費、每期堂數、效期與拆帳。",
    answer: "同一個課程可有多種收費方案；改方案不會改名課程，也不會回寫既有購買或排課。",
    path: "課程管理 → 新增課程／收費方案",
    keywords: "音樂課程 科目 收費方案 分類 課型 個別課 自組班 團體班 每堂學費 每期堂數 拆帳 上架 下架",
    steps: ["在課程管理新增科目名稱、分類與介紹，確認狀態為上架。", "從該課程列點「收費方案」，新增個別、自組或團體方案，填每堂學費、老師拆帳比、每期堂數、排課方式與每期有效天數。", "儲存後分別核對課程及方案狀態，再到教師管理設定可教授的實際方案。"],
    important: "課程名稱與收費規則是不同層級。下架只阻止後續選用，不會刪除既有購買、排課、點名或薪資快照。",
    success: "課程下能看到正確方案，排課及繳費選單依狀態與保存順序顯示，舊資料未被改寫。",
    details: ["方案的每期堂數可設 1～1000；固定時段預設每期 35 天、約課預設 70 天，可依實際商品調整。", "新方案需另確認教師可教授資格；建立科目不會自動讓所有老師可排。", "課程或方案有未結束課次時，下架前會顯示影響數量；既有課次與歷史保留。"],
    modules: ["course"], permission: "plans.edit", additionalPermissions: ["booking.create"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/music-subject-catalog.tsx", "src/app/(dashboard)/dashboard/courses/course-profile-forms.tsx", "src/server/actions/music-subject.ts", "src/server/actions/course-members.ts"],
  },
  {
    id: "C154", category: "money", title: "音樂方案多期、贈課或中途插班，繳費時怎麼核對？",
    summary: "方案只保存單期規則；購買時再選期數、贈課、折扣或插班，系統即時計算期別、總堂數、價格與效期。",
    answer: "贈課會併入購買期別但不自動延長效期；插班只購買本期剩餘堂數，不能再疊加多期。",
    path: "顧客管理／音樂課名單 → 購買方案／學員繳費",
    keywords: "音樂繳費 買幾期 贈課 買三送一 期別 5加4加4 插班 剩餘堂數 折扣 有效天數 即時試算",
    steps: ["選正確學員與適用方案；完整方案／續報輸入購買期數，插班則選系統列出的第一堂與本期剩餘堂數。", "有授權時輸入贈課或折扣；核對各期堂數、總堂數、總價、實收及從首次使用起算的有效天數。", "確認款項已實際收到後送出一次，再查購買紀錄、持有方案及名單的本期／下期資訊。"],
    important: "試算不等於收款。送出結果不明時先查原購買，不要重建第二筆；既有訂單永遠使用購買當時的期別、價格與效期快照。",
    success: "只新增一筆購買與付款，期別總和等於總堂數，贈課、折扣、插班與效期均符合畫面確認內容。",
    details: ["例如每期 4 堂、購買 3 期、贈 1 堂會顯示 5＋4＋4，共 13 堂；贈課不另成第四期。", "插班只接受系統列出的同課程本期場次與剩餘堂數；學員撞堂、滿班、方案狀態或資格不符仍會阻擋。", "購買完成不等於下期課表已排；排課、付款與方案堂數需分開核對。"],
    modules: ["course"], permission: "wallet.create", additionalPermissions: ["transaction.create", "customer.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/components/admin/music-assignment-payment.tsx", "src/components/admin/course-assignment-payment.tsx", "src/lib/music-course-products.ts", "src/server/services/course-assignment-checkout.ts"],
  },
  {
    id: "C155", category: "settings", title: "音樂課程、方案、教室與老師的顯示順序怎麼調整？",
    summary: "清除搜尋與篩選後，可拖曳排序；手機也可點排序把手選上移／下移，成功後會保存門市共用順序。",
    answer: "上架與下架項目各自排序；課程、方案、教室與老師的順序會套用到對應管理及選擇清單。",
    path: "課程管理／方案管理／教室管理／教師管理 → 排序把手",
    keywords: "音樂清單 排序 拖曳 上移 下移 顯示順序 復原 手機 平板 清除篩選 上架 下架",
    steps: ["先清除搜尋、分類、狀態與測試資料篩選，確認要調整的是上架或下架區。", "桌機拖曳「⋮⋮」到新位置；手機或鍵盤點排序把手後選上移／下移。", "看到「排序已儲存」後核對清單與相關選單；若移錯可立即點「復原」。"],
    important: "有搜尋或篩選時禁止排序，避免只看部分清單卻覆蓋完整順序；上架項目不能拖進下架區。",
    success: "重新整理後順序保留，對應的排課、繳費或選擇清單按新順序顯示。",
    details: ["每次移動都用版本號防止舊頁覆蓋新版；衝突或儲存失敗會恢復原順序。", "排序不會改變上下架、售價、教師資格或既有排課；這些需使用各自的正式操作。"],
    modules: ["course"], permission: "", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/components/admin/course-display-order.tsx", "src/server/actions/course-display-order.ts", "src/app/(dashboard)/dashboard/courses/music-subject-catalog.tsx", "src/app/(dashboard)/dashboard/courses/staff-workspace.tsx"],
  },
  {
    id: "C156", category: "staff", title: "同一人既是店長又是老師，兩個身分怎麼建立與連結？",
    summary: "在人員管理建立店長後台帳號，在教師／教練管理另建授課身分；確認為本店同一人後再選擇連結。",
    answer: "連結只標示兩筆身分屬於同一人，不會合併登入、權限、授課資格、薪資或歷史。",
    path: "人員管理／教師管理 → 編輯 → 基本資料 → 連結同一人（選填）",
    keywords: "店長兼老師 店長兼教練 身分分離 連結同一人 後台帳號 LINE 教師帳號 解除連結 舊資料兼任",
    steps: ["先在人員管理建立店長後台帳號，再到教師／教練管理建立授課身分；兩邊使用各自正確的登入方式。", "編輯其中一邊，在「連結同一人」選正確姓名及電話，核對生日與緊急聯絡資料後儲存。", "分別驗證店長後台權限與老師「我的工作」；舊兼任資料需完成課次交接後再關閉兼任。"],
    important: "不要用同名自行合併。解除連結不會刪除兩筆身分或過往紀錄；停用其中一邊也不會自動停用另一邊。",
    success: "兩邊顯示已連結同一人，但各自登入、權限、授課資格及歷史仍正確。",
    details: ["一筆身分只能連到一個對應身分，不能連自己或跨店連結。建立連結時會核對對方尚未被占用。", "老師也可以是學員，前台可依開通狀態使用會員專區／我的工作或僅我的工作；這和店長後台連結是不同層級。", "操作紀錄保留實際登入帳號及姓名快照，不因同一人連結而把兩邊歷史混成一筆。"],
    modules: ["course"], permission: "staff.manage", additionalPermissions: ["staff.view"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/staff-page.tsx", "src/app/(dashboard)/dashboard/courses/staff-workspace.tsx", "src/server/actions/course-staff.ts"],
  },
  {
    id: "C157", category: "money", title: "音樂老師拆帳與可查看的教師範圍怎麼設定？",
    summary: "拆帳可依老師預設、科目與個別方案逐層覆蓋；後台人員另設定全店或指定教師的財務範圍及讀寫權限。",
    answer: "新排課依方案例外、科目例外、老師預設、方案比例的順序取值並保存快照；舊課次不回算。",
    path: "教師管理 → 授課與拆帳；人員管理 → 後台帳號／權限 → 教師財務範圍",
    keywords: "音樂老師 拆帳 比例 固定費 老師預設 科目 方案例外 恢復預設 教師財務範圍 指定教師 月結權限",
    steps: ["在教師管理選老師，先設定可教授課程，再選預設拆帳；有差異時才新增科目或個別方案例外。", "儲存後新建一堂測試課，核對課次的老師、規則來源與試算金額；舊課次維持原快照。", "在人員管理為後台帳號選全店或指定教師範圍，再分別開放拆帳查看／管理及月結查看／確認／付款權限。"],
    important: "可教授資格與拆帳權限分開；能看指定教師不代表能確認全店月結。付款登錄只是帳務紀錄，不會自動匯款。",
    success: "新課次採用預期拆帳快照，後台人員只看到授權教師及允許的財務操作。",
    details: ["代課使用實際代課老師規則；老師請假／曠課為零，免費老師補課排除，學員曠課或團體班放棄請假仍依規則計算。", "授課費可分次登錄，每次不得超過未付餘額；現金付款仍需現金抽屜，錯誤付款用更正保留反向紀錄。", "店主保留全店範圍。被授權人員不能把自己沒有的教師範圍或權限再授予別人；修改權限後既有快取會失效。"],
    modules: ["course"], permission: "teacher.compensation.manage", additionalPermissions: ["staff.manage"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/components/admin/music-teacher-fee-editor.tsx", "src/app/(dashboard)/dashboard/courses/staff-workspace.tsx", "src/server/actions/course-staff.ts", "src/server/services/course-teacher-fee.ts", "src/server/services/music-finance-access.ts"],
  },
];
