import type { OperationGuide } from "./operation-guide-types";

/** Source review at main 95dd0b8e; logged-in operation acceptance remains separate. */
export const dailyOperationGuides20261007: OperationGuide[] = [
  {
    id: "W01", category: "work-orders", title: "工單入口為什麼看不到？如何新增第一張工單？",
    summary: "門市要先開通工單，帳號需有查看或編輯權限；新增時選顧客、日期、種類／型號與施工內容，儲存後才取得每日單號。",
    answer: "先核對功能與 work_order 權限，再建立工單；單號以台灣日期加流水號產生，未成功儲存不占號。",
    path: "店務管理 → 工單 → 新增工單",
    keywords: "工單 看不到 未開通 權限 新增 顧客 種類 型號 施工內容 每日單號 流水號",
    steps: ["確認目前門市已開通工單，帳號有查看權限；要新增或修改另需編輯權限。", "點新增工單，選正確顧客與日期，填種類／型號、施工內容及顧客備註。", "核對內容後儲存一次，再以產生的單號搜尋並重新開啟確認。"],
    important: "工單號碼成功儲存後才產生，之後改日期不改號；不要為了取得新號碼重複建立。",
    success: "清單出現正確顧客、日期、單號、進度與未付款狀態。",
    details: ["單號格式為 YYMMDD 加至少三位流水號，依門市及工單日期編號。", "清單可依姓名、完整電話或單號搜尋，並篩進度及付款狀態。", "功能授權、查看、編輯與收款權限分開；直接網址不能繞過。"],
    modules: ["steamfoot", "spa", "course"], permission: "work_order.read", feature: "work_orders", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/work-orders/page.tsx", "src/app/(dashboard)/dashboard/work-orders/workspace.tsx", "src/server/services/work-orders.ts"],
  },
  {
    id: "W02", category: "work-orders", title: "工單材料、身分價格、折扣、贈品與工費怎麼填？",
    summary: "材料從進銷存商品選取，可用身分價格、數量、折扣或贈品；工費獨立填寫，儲存時依差額異動庫存。",
    answer: "先選價格身分，再加入材料與優惠，最後填工費；贈品金額為 0 仍會扣庫存。",
    path: "工單 → 新增／編輯 → 施工項目與商品材料",
    keywords: "工單材料 商品 身分價格 折扣 百分比 贈品 工費 庫存 改價",
    steps: ["選價格身分，再用商品搜尋加入材料，核對數量與單價。", "有折扣時選金額或百分比；贈品明確標記，不用把單價手改為 0。", "填工費並核對材料小計、優惠與應收，再儲存。"],
    important: "贈品仍扣庫存；沒有改價權限不可繞過身分價格。編輯材料只按新舊差額調整庫存。",
    success: "應收等於材料優惠後金額加工費，庫存只異動一次。",
    details: ["材料共用進銷存商品；工單功能已開但進銷存資料或權限不足時，先由管理者核對。", "已收款後不得把應收改到低於淨已收，系統會拒絕並回滾庫存。", "結果不明先查原工單與庫存，不要重建。"],
    modules: ["steamfoot", "spa", "course"], permission: "work_order.read", additionalPermissions: ["work_order.write"], feature: "work_orders", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/work-orders/workspace.tsx", "src/server/services/work-orders.ts", "src/server/services/inventory.ts"],
  },
  {
    id: "W03", category: "work-orders", title: "工單如何分次收款？取件時仍欠款怎麼辦？",
    summary: "工單可在明細同頁分次收現金、轉帳或其他；取件與收款是兩個狀態，欠款取件會再次確認。",
    answer: "每次只填實收金額與方式，成功後核對已收／尚欠及現金帳；標記取件不會自動視為付清。",
    path: "工單 → 查看明細 → 收款／改為已取件",
    keywords: "工單收款 分次收款 現金 轉帳 尚欠 取件 未付清 現金抽屜 收支帳",
    steps: ["開啟正確單號，核對應收、已收與尚欠。", "點收款，選日期、付款方式與本次實收，送出一次。", "成功後核對金額、收款紀錄及現金帳；仍欠款要標記取件時閱讀確認提示。"],
    important: "取件不等於已付款；現金需當日抽屜可收款，結果不明先查原工單與現金帳，不要重送。",
    success: "淨已收與尚欠正確，現金只影響抽屜一次，轉帳不改抽屜現金。",
    details: ["未付款工單不先列營收；部分付款只按實收日列入其他收入。", "收款不會再次扣材料庫存；防重送與版本衝突由後端處理。", "課程方案收入明細不含工單，請到全店營收／收支帳核對。"],
    modules: ["steamfoot", "spa", "course"], permission: "work_order.read", additionalPermissions: ["work_order.write"], feature: "work_orders", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/work-orders/settlement-panel.tsx", "src/server/services/work-orders.ts", "src/server/services/cash-drawer.ts"],
  },
  {
    id: "W04", category: "work-orders", title: "工單取消或退款時，材料、工費與庫存怎麼處理？",
    summary: "取消／退款表單要填原因、保留工費、退回材料數量、保留材料費、退款金額與方式；原收款與歷史保留。",
    answer: "只填實際可回補的材料數量；退款不得超過淨已收或本次降低的應收，送出後核對庫存、退款帳與新應收。",
    path: "工單 → 查看明細 → 取消／不維修",
    keywords: "工單取消 退款 保留檢測費 退回材料 回補庫存 淨已收 現金退款 轉帳退款",
    steps: ["展開取消／退款，填原因並核對目前應收、淨已收與材料。", "填保留工費及材料費，只對實際未使用且已退回的材料填回補數量，再填退款與方式。", "確認新應收不低於淨已收，送出後查取消／退款紀錄、庫存及收支帳。"],
    important: "已使用或免收費材料不會自動回補；已取消工單不可一般編輯或重新開工。",
    success: "新應收、淨已收、退款與尚欠一致，庫存只回補指定數量，原收款紀錄仍在。",
    details: ["現金退款會影響現金抽屜；轉帳退款只影響收支帳。已關帳日期、撤權、跨店或舊版本會拒絕且不留下部分寫入。", "同一請求重送不重退、不重補庫存；結果不明先查歷史。", "取消後仍可依實際狀態標記已取件。"],
    modules: ["steamfoot", "spa", "course"], permission: "work_order.read", additionalPermissions: ["work_order.write"], feature: "work_orders", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/work-orders/settlement-panel.tsx", "src/server/services/work-orders.ts", "src/lib/work-orders.ts"],
  },
  {
    id: "W05", category: "work-orders", title: "工單如何列印雙聯、查看進度與歷史？",
    summary: "明細可列印顧客聯／店家聯並查看進度、付款、取消與退款紀錄；列印只顯示店家已設定的聯絡資料。",
    answer: "先核對工單號、顧客、施工內容、材料與金額，再列印；進度與付款分開閱讀。",
    path: "工單 → 查看明細 → 列印／紀錄",
    keywords: "工單列印 雙聯 顧客聯 店家聯 QR 官方LINE 處理中 待取件 已取件 歷史",
    steps: ["開啟正確單號，核對顧客、種類／型號、施工內容、材料、應收與尚欠。", "查看處理中、待取件、已取件或已取消進度，以及收款／退款歷史。", "點列印，預覽顧客聯與店家聯；確認營業時間、電話、官方 LINE、地址及 QR 後再印。"],
    important: "畫面預覽不等於實體印表機、PDF 分頁或 QR 已驗證；長內容請先試印。",
    success: "兩聯單號與金額一致，顧客文件不洩漏成本或內部資料。",
    details: ["空白聯絡資料不顯示；官方 LINE 顯示設定的 ID，QR 沿用連結。", "進度與付款是兩件事；已取件仍可能欠款。", "A4 橫向雙聯及長內容可能依印表機分頁，正式大量列印前先用測試工單驗收。"],
    modules: ["steamfoot", "spa", "course"], permission: "work_order.read", feature: "work_orders", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/work-orders/document/page.tsx", "src/app/(dashboard)/dashboard/work-orders/workspace.tsx", "src/lib/work-orders.ts"],
  },
  {
    id: "C167", category: "care", title: "課程 LINE 提醒的改期、取消、確認會到與續購，後台怎麼核對？",
    summary: "前一日提醒可開啟改期、取消與確認會到；低額度、用完及到期提醒可進預約、購買／續購或諮詢店長。",
    answer: "提醒按鈕仍受本店身分、期限、名額與方案檢查；店家在後台原課次、購買及發送紀錄核對結果。",
    path: "設定 → 通知與顧客經營 → 提醒管理／發送紀錄",
    keywords: "課程 LINE 改期 取消 確認會到 立即預約 購買方案 續購 諮詢店長 館名",
    steps: ["在後台核對上課提醒及取消截止設定，先確認提醒是否啟用與訊息預覽。", "區分改期、取消、確認會到與續購的用途；按鈕顯示不代表已變更預約、完成點名或收到款項。", "需確認結果時回後台原課次、購買與發送紀錄核對，結果不明不重送收款或重建預約。"],
    important: "確認會到不等於已報到；改期／取消不處理退費。定期方案、補課或已報到的預約可能需店家協助。",
    success: "後台能核對正確門市的提醒設定、原預約與購買結果，沒有重複送出。",
    details: ["改期在同一交易取消原預約並建立新預約，任一步失敗會回滾；原體驗收款保留，不新增退款。", "體驗後關懷只納入啟用後、課程結束且已完成的體驗；已購買、待核帳、已有預約或停止接收會依規則略過。", "共用官方 LINE 不會合併兩店會員、方案或預約；一般聊天不猜門市。"],
    modules: ["course"], permission: "business_hours.manage", feature: "line_reminder", kind: "howto", verification: "source-reviewed",
    sources: ["src/components/course-booking-notification-dialog.tsx", "src/server/actions/course-booking-notification.ts", "src/server/services/course-delivery-links.ts", "src/server/services/course-trial-care.ts"],
  },
];
