import type { OperationGuide } from "./operation-guide-types";

/** Source review at e919aa5e. No logged-in operation acceptance is implied. */
export const dailyOperationGuides20260928: OperationGuide[] = [
  {
    id: "C143", category: "booking", title: "音樂課程要先設定哪些售價、期數與排課規則？",
    summary: "音樂教室需先選課型，再設定每堂售價、每期堂數、有效天數及固定時段或每次約課。",
    answer: "個別課與自組班每期 4 堂、團體班每期 8 堂；音樂課只使用堂數，每位每次固定 1 堂。",
    path: "店務設定 → 課程管理 → 新增／編輯課程", keywords: "音樂教室 吉他課 私課 自組班 團體班 每堂售價 每期堂數 固定時段 每次約課 有效天數 免費體驗 付費體驗",
    steps: ["選私課、自組班或團體班，填每位學員每堂售價。", "依課型核對每期 4 或 8 堂，選固定時段或每次約課，並填每期有效天數。", "需要體驗時另選一般、免費 30 分鐘或付費完整一堂；儲存後回清單核對。"],
    important: "音樂教室不能建立點數方案；已排課的課型不能直接改成另一種，請複製課程另建。",
    success: "課程清單顯示正確課型、時長、每堂售價、堂數、效期及排課方式。",
    details: ["固定課預設 35 天、約課預設 70 天只是表單預設值，仍以實際儲存內容為準；效期從第一堂實際上課日起算。", "音樂課時長只接受 30／60／90／120 分鐘，開始時間須在整點或半點。免費體驗的老師計費基礎只供分成計算，不代表已收款。"],
    modules: ["course"], permission: "booking.create", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/server/actions/course.ts", "src/server/services/course-availability.ts"],
  },
  {
    id: "C144", category: "booking", title: "音樂課如何找老師與教室空位並建立課表？",
    summary: "依序選課程、時長與日期，再從可排時段選老師及教室，可建立單堂或每週一整期。",
    answer: "空位會同時核對店家授課時間、老師可授課時間、教室及既有課表。",
    path: "音樂課表 → 新增課程／找空位", keywords: "音樂課表 找空位 可排時段 老師 教室 每週固定 一整期 30 60 90 120",
    steps: ["選課程與 30／60／90／120 分鐘時長，再選要找空位的日期。", "從可排時段選時間、老師與教室；需要時展開不能排的原因。", "選單堂，或勾每週固定排一整期後建立，再接著選學員。"],
    important: "畫面列出空位後到正式建立前仍可能有其他人排課；送出時會重新檢查，每堂衝突就不建立該請求。",
    success: "新課出現在正確日期、老師與教室的課表，固定排課堂數符合課程每期堂數。",
    details: ["老師原固定課保留的空位只能排單次臨時課，不能再勾整期固定。", "沒有合適空位時先換日期或時長，或核對店家授課時間、老師例外及教室使用狀態，不要任意覆蓋衝突。"],
    modules: ["course"], permission: "booking.create", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/music-schedule-wizard.tsx", "src/server/actions/course-slot-matches.ts", "src/server/actions/course.ts"],
  },
  {
    id: "C145", category: "booking", title: "音樂課怎麼記錄出席、曠課、請假與恢復待點名？",
    summary: "逐位或批次記錄學員；出席與曠課扣 1 堂，自組班及團體班的請假規則不同。",
    answer: "自組班請假不扣堂、可在期限內另約；團體班請假仍扣 1 堂，兩者都保留缺課紀錄。",
    path: "音樂課表 → 課程名單；音樂課表 → 請假學員／待點名學員", keywords: "音樂 點名 簽到 出席 曠課扣堂 請假 自組班 團體班 恢復待點名 批次點名 累計缺課",
    steps: ["開啟正確課次，核對學員與課型；可逐位操作，或勾選多人後批次套用。", "依實際狀況選出席、曠課扣堂或請假；曠課需等課程結束。", "誤記時選恢復待點名，再核對堂數、名單狀態及累計缺課紀錄。"],
    important: "音樂教室沒有補課券。自組班請假與老師曠課的免費補課是不同流程；團體班請假仍扣堂。",
    success: "名單、課表左槓及堂數紀錄一致；批次操作只更新勾選的學員。",
    details: ["出席或曠課才正式扣堂；自組班請假保留本堂日期並釋放堂數，須在方案期限內另約。團體班請假記錄缺課並扣堂。", "恢復請假前會重查名額及方案效期；資料已被他人更新時不會覆寫，應重新核對。"],
    modules: ["course"], permission: "booking.update", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/app/(dashboard)/dashboard/courses/daily-attendance-list.tsx", "src/server/actions/course-members.ts", "src/server/services/course-booking.ts"],
  },
  {
    id: "C146", category: "booking", title: "音樂課老師請假或曠課，學員與補課怎麼處理？",
    summary: "先記錄老師狀態；該堂學員免逐一點名且不扣堂，老師曠課後才能安排免費補課。",
    answer: "老師請假／曠課不會替學員新增出勤；免費補課另排一堂，且不增加原課期數。",
    path: "音樂課表 → 課程名單 → 老師", keywords: "老師請假 老師曠課 教師缺席 學員免點名 免費補課 原課期數 更正紀錄",
    steps: ["開啟課次名單，在老師區核對姓名後選老師請假或老師曠課，填原因並確認。", "確認學員顯示本堂免點名，沒有新增出勤或扣堂。", "老師曠課需補課時，點安排免費補課，選日期、整點／半點時間、老師及教室後加入課表。"],
    important: "只有先記錄老師曠課才能建立免費補課；補課不增加原方案堂數或原課期數。",
    success: "課表顯示老師狀態；免費補課另有課次並保留與原課的關聯。",
    details: ["老師狀態可用更正紀錄恢復；更正後才依實際狀況逐位點名。", "免費補課預設沿用原老師與教室，仍會檢查店家、老師與教室空檔；原課紀錄不會被刪除。"],
    modules: ["course"], permission: "booking.update", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/actions/course.ts", "src/server/actions/course-members.ts"],
  },
  {
    id: "C147", category: "staff", title: "音樂老師的每週可授課時間與單日請假怎麼設定？",
    summary: "可沿用店家時間，或逐日設定多段可授課時間；單日例外另記請假或臨時加開。",
    answer: "老師固定時間與單日例外會一起影響找空位及正式排課，單日例外優先。",
    path: "人員管理 → 老師 → 可授課時間", keywords: "音樂老師 可授課時間 沿用店家 每週 多段時段 單日例外 請假 臨時加開 反灰",
    steps: ["選老師後查看可授課時間；決定沿用店家授課時間，或取消勾選後逐日增減時段。", "儲存每週可授課時間，再展開單日例外／請假／臨時加開。", "選日期與不可授課、自訂時段或恢復固定規則，填原因後儲存。"],
    important: "設定不可授課不會自動搬移既有課程；先核對該日課表及受影響學員。",
    success: "老師視角非授課時段反灰，找空位只列出符合店家、老師及教室條件的時段。",
    details: ["一天可設定多段，每段以 30 分鐘為單位；單日自訂時間覆蓋該日固定規則。", "看得到人員資料不代表可修改，需人員管理權限；排課仍會另外核對授課資格與教室。"],
    modules: ["course"], permission: "staff.manage", additionalPermissions: ["staff.view"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/course-staff-availability-editor.tsx", "src/server/actions/course-availability.ts", "src/server/services/course-availability.ts"],
  },
  {
    id: "C148", category: "booking", title: "音樂固定課要調課或改回原時段，怎麼操作？",
    summary: "從原課次選調課，找新的老師／教室空位；課表保留原時段影子與調課關聯。",
    answer: "調課不是刪除後重建；成功前原課保留，失敗時也不會消失。",
    path: "音樂課表 → 選課次 → 調課", keywords: "音樂調課 原時段 已調課 改回原時段 老師 教室 原課保留",
    steps: ["開啟原課次，核對學員、原時間、老師與教室，再點調課；固定課另選這堂、連續幾週或換固定時段。", "切到目標日期的日表或週表，在符合時長的白格貼上，送出後查看新課次及原時段的已調課標示。", "要回原時段時從已調課課次選恢復原時段，確認原資源仍可用後再核對課表。"],
    important: "已完成點名或原時段已有新衝突時可能不能回復；不要用取消學員或另建方案代替調課。",
    success: "新位置顯示調課，原位置保留可辨識的歷史影子，學員及原課關聯未遺失。",
    details: ["調課送出會重新檢查營業時間、老師可授課時間、教室與其他固定／調課占用。", "調課失敗會顯示原課程保留；先查錯誤與最新課表，不要重複連按建立多堂。"],
    modules: ["course"], permission: "booking.update", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/app/(dashboard)/dashboard/courses/course-schedule-board.tsx", "src/app/(dashboard)/dashboard/courses/music-schedule-wizard.tsx", "src/server/actions/course.ts"],
  },
  {
    id: "C149", category: "plans", title: "音樂方案的購買期數、堂數與到期日怎麼算？",
    summary: "音樂方案依課程每期堂數與每堂售價組成；購買多期會等比例增加堂數、價格與有效天數。",
    answer: "到期日從第一堂被正式結算的課程日期起算，不是從店內結帳日或建立方案日開始。",
    path: "店務設定 → 方案管理；顧客管理 → 購買方案", keywords: "音樂方案 購買期數 堂數 每堂售價 有效天數 第一堂上課 到期日 4堂 8堂",
    steps: ["建立音樂方案時只選一種一般音樂課，確認課型、每期堂數、每堂售價及每期有效天數。", "替學員購買時選方案與購買期數，核對換算後的總堂數、價格與有效天數，再完成收款。", "第一堂完成出席／曠課等正式扣堂後，回持有方案核對自該堂日期起算的到期日。"],
    important: "體驗課不建立期數方案；音樂固定時段由課表管理，購買方案不會預先綁定指定課次。",
    success: "方案為堂數制，總堂數、價格、有效天數及第一堂後的到期日一致。",
    details: ["個別／自組班每期 4 堂，團體班每期 8 堂；每位每次使用 1 堂。購買期數必須是正整數且受系統上限限制。", "購買完成後尚未正式扣第一堂時不應自行填假的起算日；首次出席、曠課或團體班請假等扣堂紀錄會以該堂日期啟用效期。若更正最早一筆扣堂，系統會依下一筆紀錄重算。"],
    modules: ["course"], permission: "plans.edit", additionalPermissions: ["wallet.create", "wallet.read", "customer.read"], feature: null, kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/course-profile-forms.tsx", "src/app/(dashboard)/dashboard/courses/member-workspace.tsx", "src/lib/music-course-products.ts", "src/server/actions/course-members.ts"],
  },
];
