import type { OperationGuide } from "./operation-guide-types";

/** Incremental source review at main 64d30d38; interaction acceptance remains separate. */
export const dailyOperationGuides20260925: OperationGuide[] = [
  {
    id: "C138", category: "money", title: "每月收入結算怎麼核對店長利潤與教練授課費？",
    summary: "選月份與收入類別，核對應領金額，再確認月結；確認不等於付款。",
    answer: "新版以應領金額為主，可切全部、店長利潤、教練授課費，展開人員明細查來源。",
    path: "月結管理 → 每月收入結算", keywords: "課程月結 每月收入結算 店長利潤 教練授課費 搜尋人員 應領合計 確認月結 重新確認 修正版",
    steps: ["選月份，再選「全部／店長利潤／教練授課費」；多人時可搜尋人員。", "展開人員「明細」，核對原方案或課次、日期及金額；待核對項目先查原因。", "點「確認月結」，核對月份後再按「確認」；有異動時點「重新確認」並填調整原因。"],
    important: "確認只保存本次收入金額，不會付款或自動發 LINE；舊資料缺少快照不能當作零元略過。",
    details: ["利潤按方案核帳月份、授課費按上課月份且只納入已結束課次；新排課未設定費率沿用 0 元規則。", "收入類別會改變合計及人員範圍；人員搜尋只篩清單，不把合計改成單一人的金額。新版不再提供待處理／已結清篩選。", "「結算紀錄」保留確認版本；退款或作廢影響舊月份時，依提示回原月份重新核對。", "僅店長且具報表權限、月結功能可操作；跨店檢視不能確認。"],
    success: "顯示已確認，結算紀錄保留版本；實際收付款另行核對。",
    modules: ["course"], permission: "report.read", feature: "service_fee_calculator", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly.tsx", "src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly-client.tsx", "src/server/actions/course-monthly-settlement.ts", "src/server/services/course-monthly-settlement.ts"],
  },
  {
    id: "C139", category: "money", title: "如何開放人員查看本人收入？原本的計算開關在哪？",
    summary: "新版「查看權限」只管理本人收入查詢，不會修改原本利潤與授課費計算設定。",
    answer: "由店長展開查看權限，決定是否開放人員查詢本人已確認月結；預設關閉。",
    path: "每月收入結算 → 查看權限", keywords: "月結設定 獨立開關 計算店長利潤 計算教練授課費 查看權限 本人收入 我的收入 歷史保留",
    steps: ["展開「查看權限」，核對「開放人員查看本人收入」。", "由具權限的店長選擇開放或關閉，再按「儲存設定」。", "已綁定本店且在職的教練從「我的工作 → 我的收入」、非教練人員從「我的 → 我的收入」查看本人已確認金額。"],
    important: "查詢開關不是計算開關。新版畫面已移除利潤與授課費計算開關；儲存查看權限會保留原有計算設定。",
    details: ["修改需店長身分、人員管理權限、月結功能及可寫訂閱狀態；看得到月結不代表可改設定。", "關閉只停止後續查詢，不刪除紀錄、不停止計算，也不等於取消舊帳。", "尚未結算不表示 0 元；調整中先顯示上次確認金額。人員不能查看別人的收入或內部付款備註。", "儲存開關不自動發通知；需要通知時由「通知人員」另行核對與手動送出。"],
    success: "查看權限儲存成功，符合條件的人員可查本人已確認收入。",
    modules: ["course"], permission: "report.read", additionalPermissions: ["staff.manage"], feature: "service_fee_calculator", kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly-client.tsx", "src/server/actions/course-monthly-settlement.ts", "src/server/services/course-personal-income.ts", "src/app/(customer)/book/income/page.tsx"],
  },
  {
    id: "C140", category: "money", title: "新版月結找不到登錄利潤已付，舊付款與更正去哪裡查？",
    summary: "新版月結專注收入結算，已移除新增利潤付款入口；舊付款紀錄仍保留。",
    answer: "有既有付款時可展開「歷史付款紀錄」回查，只有確實誤登才使用更正。",
    path: "每月收入結算 → 歷史付款紀錄", keywords: "分次付款 利潤已付 找不到 付款入口 歷史付款紀錄 溢付 退款 更正誤登 修正版",
    steps: ["選原月結月份；若曾登記付款，展開「歷史付款紀錄」核對人員、原項目、日期及金額。", "只有確實誤登且具權限時，才選原紀錄的更正，填原因並核對結果。", "退款或作廢造成舊月金額變動時，依提示回原月結查核並重新確認；實際退回款項另外確認。"],
    important: "目前畫面沒有新增利潤付款按鈕，不要照舊教學尋找隱藏入口。更正誤登不等於已收回實際溢付款。",
    details: ["舊的分次付款紀錄未刪除；畫面未顯示歷史付款區時，不代表收入為零或已付清。", "授課費原有付款作業仍從營運的授課費區處理，與歷史紀錄共用帳本，不要重複新增支出。", "更正需店長身分及現金帳新增權限；連線中斷先查原紀錄，不反覆送出。"],
    success: "找到原付款或確認尚無紀錄，沒有把收入確認、登記付款與實際收回款項混為一談。",
    modules: ["course"], permission: "report.read", additionalPermissions: ["cashbook.create"], feature: "service_fee_calculator", kind: "troubleshooting", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly.tsx", "src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly-client.tsx", "src/server/services/course-profit-payment.ts", "src/server/actions/course-monthly-settlement.ts"],
  },
  {
    id: "C141", category: "booking", title: "課表如何切換月表、週表、日表及上課名單？",
    summary: "同一份課表可切換三種視角，配合教練、教室與分類篩選查找課次。",
    answer: "月表看整月，週表看一週，日表看當日安排；切換視角不會建立或修改課程。",
    path: "課表排程 → 月表／週表／日表", keywords: "月表 週表 日表 課表 視角 教練 教室 分類 篩選 上課名單 右側面板",
    steps: ["選月表、週表或日表，使用日期欄位或前後切換按鈕移到目標日期。", "依需要篩選教練、教室、課程分類；找不到課程時先清除篩選。", "開啟課次的上課名單，在右側面板核對學員；關閉面板回到課表。"],
    important: "上課名單與設定表單的呈現不同，不是所有操作都用置中視窗；公休日既有課程仍可查看處理，但不能新增排課。",
    details: ["課表上的顯示與篩選不會放寬教室容量、教練資格或撞期限制。", "體驗未收款的學員列可看到「收款」入口，是否能操作仍依收款權限與狀態。"],
    success: "三種視角顯示同一批符合篩選的課次，能打開正確課次名單。",
    modules: ["course"], permission: "booking.read", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/app/(dashboard)/dashboard/courses/course-schedule-board.tsx", "src/app/(dashboard)/dashboard/courses/roster.tsx"],
  },
  {
    id: "I10", category: "settings", title: "店家換名字，可以保留原本會員、方案與網址嗎？",
    summary: "可以請 HQ 在原店舖更改顯示店名，不需另開一間店。",
    answer: "更名更新原店顯示名稱，店舖 ID、網址代碼、訂閱與顧客歷史仍保留。",
    path: "聯繫 HQ → 店舖詳情 → 顯示店名", keywords: "店名 更名 改名 品牌 更換名字 續約 原會員 網址不變 HQ",
    steps: ["提供需更名的原門市與新顯示名稱，請 HQ 核對店舖，避免另建新店。", "由具權限的 HQ 人員在店舖詳情輸入 1～80 字店名，點「儲存新店名」。", "看到店名已更新後，重新整理店家及會員入口，確認名稱與原本資料。"],
    important: "此操作限 HQ 管理員及人員管理權限，不是一般店長後台的自助更名功能。",
    details: ["只改顯示名稱，不會重置試用、訂閱期限或轉移資料；既有網址代碼保持不變。", "外部 LINE 官方帳號名稱與其他宣傳資料不會因此一併更改。"],
    success: "同一門市顯示新店名，原網址與會員、方案、預約歷史保留。",
    modules: ["steamfoot", "spa", "course"], permission: "", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/server/actions/store-rename.ts", "src/app/hq/dashboard/stores/[storeId]/rename-store-form.tsx"],
  },
  {
    id: "S04", category: "start", title: "課程體驗店顯示已授權，為什麼 LINE 還不能用？",
    summary: "功能授權、試用計時與外部服務設定是三件不同的事。",
    answer: "HQ 功能頁會顯示實際授權及試用計時；LINE 入口、提醒規則和發送仍需另行設定與驗收。",
    path: "請 HQ 核對店舖詳情與功能設定", keywords: "體驗版 試用授權 實際授權 三十天 30 天 尚未開始 LINE 未設定 全功能",
    steps: ["請 HQ 核對門市的實際授權、試用起迄及「尚未開始／已開始／已到期」狀態。", "課程體驗店尚未設定試用起迄時，可顯示功能已授權但 30 天試用尚未起算。", "LINE 相關功能另核對導流入口、綁定、提醒規則及實際發送結果；不要只憑授權標籤判斷成功。"],
    important: "完整單店試用不包含多店功能；試用期間的單店授權覆寫不生效，並不等於店長有全部管理權限。",
    details: ["本題說明 HQ 顯示與檢查方式，不提供重新起算試用或略過訂閱限制的方法。"],
    success: "能區分已開通功能、試用日期與仍待設定／驗收的 LINE 流程。",
    modules: ["course"], permission: "", feature: null, kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/hq/dashboard/stores/[storeId]/features/page.tsx", "src/app/hq/dashboard/stores/[storeId]/page.tsx"],
  },
];
