import type { OperationGuide } from "./operation-guide-types";

/** Incremental source review at main 64d30d38; interaction acceptance remains separate. */
export const dailyOperationGuides20260925: OperationGuide[] = [
  {
    id: "C138", category: "money", title: "課程月結怎麼核對店長利潤與教練授課費？",
    summary: "月結依人員合併利潤與固定授課費，確認金額與登錄付款是兩個動作。",
    answer: "店長在已開通的月結管理選月份，先核對明細，再保存本月確認版本。",
    path: "月結管理 → 選月份 → 人員月結清單", keywords: "課程月結 店長利潤 教練授課費 核帳月份 上課月份 確認本月金額 修正版",
    steps: ["由店長選擇月份，查看目前應付、已登錄付款、待付及溢付待核對。", "展開每位人員及原購買／課次，核對利潤與授課費；有待核對明細時先查原因。", "填確認備註並點「確認本月金額」；已有版本而金額改變時，填修訂原因並確認修正版。"],
    important: "確認只保存金額版本，不會付款或建立支出；既有資料缺少分配或費率快照時，不能當作零元略過。",
    details: ["利潤按方案核帳月份、授課費按上課月份，且只納入已結束課次；同一人兼任會合併在同一列。", "新排課未設定費率仍沿用 0 元規則，與舊資料缺少快照的異常不同。", "付款狀態持續更新，舊確認版本保留確認當時的資料。教練前台目前不會因此新增月結明細入口。", "僅店長可查看及確認，需報表查看權限與月結功能；跨店檢視模式不能確認或付款。"],
    success: "顯示金額已確認及版本號，實際付款仍另行核對。",
    modules: ["course"], permission: "report.read", feature: "service_fee_calculator", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly.tsx", "src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly-client.tsx", "src/server/actions/course-monthly-settlement.ts", "src/server/services/course-monthly-settlement.ts"],
  },
  {
    id: "C139", category: "money", title: "月結的利潤與授課費開關，關閉後會清掉舊帳嗎？",
    summary: "不會。利潤開關只影響新購買，授課費開關只影響新排課。",
    answer: "HQ 的月結功能授權與店長的計算設定不同；店長可在月結設定決定是否計算兩種費用。",
    path: "月結管理 → 月結設定", keywords: "月結設定 獨立開關 HQ 授權 計算店長利潤 計算教練授課費 關閉 歷史保留",
    steps: ["由店長開啟月結管理並展開「月結設定」。", "核對「計算店長利潤」與「計算教練授課費（每堂固定）」的勾選狀態，再儲存設定。", "重新開啟核對設定；新購買／新排課依新設定，舊資料仍回原月份查核。"],
    important: "兩項預設開啟。關閉不會清除既有待核帳訂單、課次、待付金額、費率設定或付款紀錄。",
    details: ["修改設定需店長身分、人員管理權限、月結功能及可寫入訂閱狀態；看得到月結不代表可改設定。", "既有待核帳訂單保留原分配；不要透過切換開關來取消舊帳。"],
    success: "設定儲存後保留，歷史與既有待付資料仍能查詢。",
    modules: ["course"], permission: "report.read", additionalPermissions: ["staff.manage"], feature: "service_fee_calculator", kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly-client.tsx", "src/server/actions/course-monthly-settlement.ts", "src/server/services/course-sale-allocation.ts", "prisma/migrations/20260924090000_course_monthly_settlement/migration.sql"],
  },
  {
    id: "C140", category: "money", title: "月結利潤如何分次登錄付款？退款後溢付怎麼辦？",
    summary: "先確認目前月結金額，再登錄已實際支付的利潤；退款可能改變原月份應付。",
    answer: "登錄只記帳，不自動轉帳；更正誤登也不代表已收回實際溢付款。",
    path: "月結管理 → 人員明細 → 登錄利潤已付／付款與更正紀錄", keywords: "分次付款 利潤已付 確認登錄 溢付待核對 退款 原月份 更正誤登 修正版",
    steps: ["確認目前月份金額後，展開人員及利潤明細，點「登錄利潤已付」。", "填本次實付金額、付款方式與備註，核對未超過待付金額後確認；分次支付分次登錄。", "退款或作廢後回原月份查核，金額異動須先確認修正版；只有確實誤登時，才在原付款填原因更正。"],
    important: "實際溢付先核對款項，不能用更正誤登假裝已收回錢。現金登錄需今日現金抽屜已開啟。",
    details: ["本月涉及舊單退款／作廢時會提供原月結連結；退款按累計比例調整原月份利潤。", "授課費沿用既有付款帳本，月結與營運會同步，不要再手動新增同一筆支出。", "需要店長身分及現金帳新增權限。連線未完成或待付金額已變更時，先重新整理查原付款，再決定是否重試。"],
    success: "付款紀錄與對應支出一致，誤登更正保留原紀錄與沖回，不會自動匯款。",
    modules: ["course"], permission: "report.read", additionalPermissions: ["cashbook.create"], feature: "service_fee_calculator", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly.tsx", "src/app/(dashboard)/dashboard/service-fee-calculator/course-monthly-client.tsx", "src/server/services/course-profit-payment.ts", "src/server/actions/course-monthly-settlement.ts"],
  },
  {
    id: "C141", category: "booking", title: "課表如何切換月表、週表、日表及上課名單？",
    summary: "同一份課表可切換三種視角，配合教練、教室與分類篩選查找課次。",
    answer: "月表看整月，週表看一週，日表看當日安排；切換視角不會建立或修改課程。",
    path: "課表排程 → 月表／週表／日表", keywords: "月表 週表 日表 課表 視角 教練 教室 分類 篩選 上課名單 右側面板",
    steps: ["選月表、週表或日表，使用日期欄位或前後切換按鈕移到目標日期。", "依需要篩選教練、教室、課程分類；找不到課程時先清除篩選。", "開啟課次的上課名單，在右側面板核對學員；關閉面板回到課表。"],
    important: "上課名單與設定表單的呈現不同，不是所有操作都用置中視窗；公休日既有課程仍可查看處理，但不能新增排課。",
    details: ["課表上的顯示與篩選不會放寬教室容量、教練資格或撞期限制。", "體驗未收款的學員列可看到「收款」入口，是否能操作仍依收款權限與狀態。"],
    success: "三種視角顯示同一批符合篩選的課次，能打開正確課次名單。",
    modules: ["course"], permission: "booking.read", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/app/(dashboard)/dashboard/courses/course-schedule-board.tsx", "src/app/(dashboard)/dashboard/courses/roster.tsx"],
  },
  {
    id: "I10", category: "settings", title: "店家換名字，可以保留原本會員、方案與網址嗎？",
    summary: "可以請 HQ 在原店舖更改顯示店名，不需另開一間店。",
    answer: "更名更新原店顯示名稱，店舖 ID、網址代碼、訂閱與顧客歷史仍保留。",
    path: "聯繫 HQ → 店舖詳情 → 顯示店名", keywords: "店名 更名 改名 品牌 更換名字 續約 原會員 網址不變 HQ",
    steps: ["提供需更名的原門市與新顯示名稱，請 HQ 核對店舖，避免另建新店。", "由具權限的 HQ 人員在店舖詳情輸入 1～80 字店名，點「儲存新店名」。", "看到店名已更新後，重新整理店家及會員入口，確認名稱與原本資料。"],
    important: "此操作限 HQ 管理員及人員管理權限，不是一般店長後台的自助更名功能。",
    details: ["只改顯示名稱，不會重置試用、訂閱期限或轉移資料；既有網址代碼保持不變。", "外部 LINE 官方帳號名稱與其他宣傳資料不會因此一併更改。"],
    success: "同一門市顯示新店名，原網址與會員、方案、預約歷史保留。",
    modules: ["steamfoot", "spa", "course"], permission: "", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/server/actions/store-rename.ts", "src/app/hq/dashboard/stores/[storeId]/rename-store-form.tsx"],
  },
  {
    id: "S04", category: "start", title: "課程體驗店顯示已授權，為什麼 LINE 還不能用？",
    summary: "功能授權、試用計時與外部服務設定是三件不同的事。",
    answer: "HQ 功能頁會顯示實際授權及試用計時；LINE 入口、提醒規則和發送仍需另行設定與驗收。",
    path: "請 HQ 核對店舖詳情與功能設定", keywords: "體驗版 試用授權 實際授權 三十天 30 天 尚未開始 LINE 未設定 全功能",
    steps: ["請 HQ 核對門市的實際授權、試用起迄及「尚未開始／已開始／已到期」狀態。", "課程體驗店尚未設定試用起迄時，可顯示功能已授權但 30 天試用尚未起算。", "LINE 相關功能另核對導流入口、綁定、提醒規則及實際發送結果；不要只憑授權標籤判斷成功。"],
    important: "完整單店試用不包含多店功能；試用期間的單店授權覆寫不生效，並不等於店長有全部管理權限。",
    details: ["本題說明 HQ 顯示與檢查方式，不提供重新起算試用或略過訂閱限制的方法。"],
    success: "能區分已開通功能、試用日期與仍待設定／驗收的 LINE 流程。",
    modules: ["course"], permission: "", feature: null, kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/hq/dashboard/stores/[storeId]/features/page.tsx", "src/app/hq/dashboard/stores/[storeId]/page.tsx"],
  },
];
