import type { OperationGuide } from "./operation-guide-types";

/** Source review at main 87f7fc78. Logged-in operation acceptance remains separate. */
export const dailyOperationGuides20261001: OperationGuide[] = [
  {
    id: "C158", category: "settings", title: "課程候補怎麼開啟？名額與停止遞補時間怎麼設定？",
    summary: "先在課程店設定開啟候補與門市預設值，再到個別課程決定是否開放及是否覆蓋名額、停止時間。",
    answer: "門市開關與個別課程開關都開啟，滿班課才會顯示候補；預設為 5 人、開課前 4 小時停止自動遞補。",
    path: "設定 → 營業與預約 → 候補；課程管理 → 編輯課程 → 候補設定",
    keywords: "課程候補 開啟候補 候補名額 5人 停止遞補 4小時 自動遞補 不停止 個別課程 滿班",
    steps: ["在設定的營業與預約區開啟候補，設定門市預設候補名額與停止自動遞補時間後儲存。", "到課程管理編輯要開放的課程，勾選「本課程允許滿班候補」，核對該課程的候補上限與停止時間。", "用未開課且已滿班的測試課核對會員端顯示候補；尚有名額時應維持直接預約。"],
    important: "只開門市設定不會替所有課程自動開放。停止時間只停止自動遞補；具預約修改權限的人員仍可在名單依順位立即處理。",
    success: "滿班且符合預約期間的指定課程顯示候補，未開放課程與尚有空位課程不顯示錯誤入口。",
    details: ["門市與課程候補名額可設 1～100 人；停止選項包含不停止及開課前 1、2、4、6、12、24 小時。", "會員仍須持有適用且涵蓋上課日期的有效方案、足夠可用額度，並在會員預約開放與截止期間內。", "候補是課程加購功能；沒有功能授權、跨店查看模式或缺少設定權限時不能修改。"],
    modules: ["course"], permission: "business_hours.manage", feature: "course_waitlist", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/settings-workspace.tsx", "src/app/(dashboard)/dashboard/courses/course-waitlist-settings.tsx", "src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/server/actions/course-waitlist.ts"],
  },
  {
    id: "C159", category: "booking", title: "課程有空位後，候補名單如何依順位遞補？",
    summary: "取消預約或增加容量時，系統在停止時間前依加入順序自動遞補；需要時可從上課名單人工立即處理。",
    answer: "同行候補視為同一組，只有空位足以容納整組才處理；成功後才建立正式預約、保留額度並嘗試發 LINE。",
    path: "課表排程 → 上課名單 → 候補名單",
    keywords: "候補名單 順位 自動遞補 人工遞補 立即遞補 同行 空位 保留額度 LINE 通知 跳過",
    steps: ["開啟正確課次的上課名單，展開候補名單，核對目前空位、加入順位、同行標記與停止自動遞補時間。", "在停止時間前先等待取消／增額後的自動處理；需要立即處理且確有空位時，點「依順位立即遞補」。", "重新整理後核對正式上課名單、候補人數及方案額度；通知結果另從發送紀錄查，不以按鈕成功代替送達。"],
    important: "不能跳過前面的同行組去遞補後面的人。人工遞補會略過停止時間，但不會略過方案、額度、資格、撞堂或容量檢查。",
    success: "符合資格的最前順位整組移入正式名單，失敗組保留可追查原因，沒有重複預約或多扣額度。",
    details: ["前面兩人同行而只空一席時，系統不拆組，也不改遞補下一位；須等空位足夠或由店家另行處理。", "候補時不先扣堂；正式遞補成功才建立預約並保留額度。會員取消候補會讓同次同行候補者一起退出。", "LINE 未綁定、路由不可用或發送失敗不會撤銷已成功的正式遞補；應先查正式名單再處理通知。"],
    modules: ["course"], permission: "booking.update", feature: "course_waitlist", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/services/course-waitlist.ts", "src/server/actions/course-waitlist.ts", "src/server/services/course-waitlist-notifications.ts"],
  },
  {
    id: "I12", category: "settings", title: "總部如何查各店操作與登入紀錄？",
    summary: "具稽核查看權限的 HQ 管理員可按目前店別範圍查操作與登入，每頁 50 筆；有關聯的紀錄可互查並返回原列表。",
    answer: "「操作與登入紀錄」分操作紀錄與登入紀錄；目前集中頁與原資料的「查看紀錄」都只供 HQ ADMIN 使用。",
    path: "總部後台 → 操作與登入紀錄 → 操作紀錄／登入紀錄",
    keywords: "總部 操作紀錄中心 稽核 各店 日期 操作人 模組 關鍵字 分頁 跨店查看 HQ 操作與登入紀錄 查看當次登入 查看這次操作 返回紀錄列表 補記中 未記錄",
    steps: ["由具 audit.read 的 HQ 管理員開啟「操作與登入紀錄」，先核對目前店別範圍與日期；預設最近 7 日，已有操作篩選時先確認是否沿用。", "在操作紀錄選日期及操作人；要查模組或關鍵字時展開「更多篩選」。從列表的操作人與「做了什麼」找目標，展開查看白話動作與實際異動欄位。", "有「查看當次登入」時可連到對應登入；在登入紀錄選日期、人員及成功／失敗後點「查詢」，成功登入可點「查看這次操作」。完成後用「返回紀錄列表」回原條件及頁次。"],
    important: "此頁及單筆紀錄限 HQ ADMIN 且需 audit.read；門市店主、店長、合作夥伴及一般員工沒有入口。出現「操作紀錄補記中」只表示紀錄待補送，不代表原業務交易失敗，不要因此重做交易。",
    success: "能在正確店別與日期範圍辨識操作及登入，有關聯時互查並返回原條件；未授權帳號無法進入。",
    details: ["操作紀錄的日期、操作人、模組與關鍵字會自動套用；條件依同瀏覽器的帳號與店別保存，清除可回預設。登入紀錄則需點「查詢」；不要把兩邊的篩選方式混用。", "操作與登入列表各每頁 50 筆，由新到舊排列；單筆最近 20 筆見 I11。有關聯時才提供互查，從列表連出後可用返回連結回原篩選與頁次；瀏覽器允許暫存時也保留展開位置與捲動位置。", "詳情只呈現可辨識的資料與異動欄位；缺資料顯示「未記錄」，「沒有欄位變更」與缺少異動內容不同。", "登入紀錄可查看時間、人員、成功／失敗、裝置、當時身分與最近使用；裝置資訊僅供參考，最近使用約每 5 分鐘更新，舊登入不回補。登入成功不代表當次一定有業務操作。", "紀錄唯讀，不能刪除、還原、退款或發通知；敏感值會遮蔽，HQ 切換單店或全部分店時仍按目前範圍查詢。"],
    modules: ["steamfoot", "spa", "course"], permission: "audit.read", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/operation-audits/page.tsx", "src/app/(dashboard)/dashboard/operation-audits/login-audit-view.tsx", "src/app/(dashboard)/dashboard/operation-audits/operation-audit-filters.tsx", "src/app/(dashboard)/dashboard/operation-audits/audit-list-state.tsx", "src/components/audit-changes.tsx", "src/lib/audit-presentation.ts", "src/lib/permissions.ts", "src/server/services/operation-audit.ts", "src/components/sidebar.tsx"],
  },
  {
    id: "I13", category: "settings", title: "新版設定中心怎麼找營業、收款、人員、提醒與方案？",
    summary: "蒸足與 SPA 的設定依五區集中顯示；桌機從左側選分類，手機從上方選單切換，提醒可在同頁側邊面板完成。",
    answer: "設定中心只整理入口與狀態，不會替你自動開啟功能；可見項目仍依模組、角色、權限及方案顯示。",
    path: "設定 → 選擇分類／設定項目",
    keywords: "新版設定中心 五分類 營業與預約 收款與體驗 人員與服務 人員與權限 通知與顧客經營 系統方案 提醒側邊面板",
    steps: ["進入設定，桌機從左側、手機從設定分類選單選營業與預約、收款與體驗、人員、通知與顧客經營或系統方案與用量。", "先看每列的目前狀態，再點修改、管理或查看；提醒管理會在同頁開啟桌機側邊／手機滿版面板。", "完成個別表單後確認儲存訊息，再關閉面板或返回設定核對摘要；切換分類本身不會儲存任何值。"],
    important: "看得到設定摘要不代表能修改。跨店查看一律唯讀；全部分店模式不顯示或儲存單店設定。",
    success: "能從唯一設定入口找到正確項目，修改後摘要與實際表單一致，未授權項目不會誤顯示可寫操作。",
    details: ["SPA 的人員區為「人員與服務」，蒸足為「人員與權限」；課程模組沿用自己的五區設定文章 C123。", "提醒面板分顧客提醒、店長 LINE 通知及發送紀錄；關閉有未儲存或正在儲存內容時會先阻擋。", "總部全部分店模式只提供跨店系統設定；要改單店內容須先切到具權限的特定店舖。"],
    modules: ["steamfoot", "spa"], permission: "", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/settings/page.tsx", "src/components/settings/settings-workspace.tsx", "src/components/settings/settings-panel.tsx", "src/app/(dashboard)/dashboard/reminders/page.tsx"],
  },
];
