import type { OperationGuide } from "./operation-guide-types";

/** Source review at 38d745a1. No logged-in operation acceptance is implied. */
export const dailyOperationGuides20260929: OperationGuide[] = [
  {
    id: "A12", category: "money", title: "蒸足方案扣堂要改成單次，同行多人金額怎麼算？",
    summary: "未完成、未扣堂且未收款的方案預約可改為單次；系統先釋放原保留堂數，再依最新預約人數建立整筆單次原價。",
    answer: "單次原價是每人 NT$799 × 預約人數；轉換本身不收款，仍要在原預約完成單次收款。",
    path: "預約管理 → 預約明細 → 其他操作 → 改為單次",
    keywords: "改為單次 方案扣堂 單次蒸足 同行 多人 799 原價 實收 折扣 釋放堂數 調整結帳方式",
    steps: ["開啟原預約，核對顧客、最新預約人數、方案及目前未收款／未扣堂狀態。", "點其他操作的「改為單次」，確認原保留堂數會釋放；需要時填原因後送出。", "重新核對明細顯示單次蒸足，單次原價為 799 乘人數；再依實際金額完成單次收款。"],
    important: "轉換不會自動收款。補課、已完成、已扣堂或已有成功交易的預約不能使用；這些情況應回原紀錄走更正流程。",
    success: "原預約保留、方案堂數釋放，明細改為單次且整筆原價符合最新預約人數；沒有新增第二筆預約或交易。",
    details: ["單次收款可依既有流程記錄實收與折扣，但不得高於轉換後原價；多人原價不是只算一人。", "送出時系統會重新鎖定並核對人數、狀態、扣堂及交易；若顯示資料已變更，重新讀取後再決定，不要重複收款。"],
    modules: ["steamfoot"], permission: "booking.update", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/bookings/booking-detail-drawer.tsx", "src/app/(dashboard)/dashboard/bookings/adjust-checkout-modal.tsx", "src/app/(dashboard)/dashboard/bookings/collect-single-modal.tsx", "src/server/actions/booking-checkout.ts", "src/server/actions/single-booking.ts"],
  },
  {
    id: "C150", category: "booking", title: "音樂課名單的本期進度、付款與下期紀錄怎麼看？",
    summary: "名單會把本期堂次、請假／曠課、付款與下期續報分開顯示，避免把已繳費當成已排課。",
    answer: "「下期已繳」只代表已有下一筆購買；下方顯示「尚未排課」時，仍需另外安排下期課次。",
    path: "音樂課表 → 開啟課次 → 學員名單 → 查看日期",
    keywords: "音樂名單 本期第幾堂 查看日期 本期付款 下期已繳 下期尚未排課 請假 曠課 續報紀錄",
    steps: ["開啟正確課次，核對學員列上的本期第幾堂、請假／曠課次數及下期已繳標示。", "點「查看日期」，逐堂核對本期日期與已出席、待上課、請假或曠課狀態。", "再核對本期付款日期、金額、方式，以及下期已繳堂數；有下期日期時逐堂查看，否則依提示另行排課。"],
    important: "付款、方案堂數與已排課是三件事；不能用「下期已繳」推定所有下期日期已建立。",
    success: "本期堂次與出勤紀錄相符，付款方式及金額可對應購買紀錄，下期是否已排課清楚可辨。",
    details: ["個別／自組班請假不扣堂並另列請假日期；團體班請假仍占本期一堂。補課會顯示原請假日期到實際補課日期的關聯。", "整頁重新整理後仍應顯示相同進度；若資料不同，先查原購買與原課次，不要再購買一筆來修正顯示。"],
    modules: ["course"], permission: "booking.read", feature: null, kind: "explanation", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/queries/course-members.ts"],
  },
  {
    id: "C151", category: "booking", title: "音樂個別課請假後，怎麼安排、取消或重排補課？",
    summary: "先在原課次記錄請假；之後從同課程的新課次選學員與原請假紀錄，沿用原方案安排補課。",
    answer: "補課必須連到尚未使用的原請假，且使用同課程、同一張原堂數方案；不是補課券。",
    path: "音樂課表 → 原課次記錄請假；新課次 → 加入學員 → 待補課",
    keywords: "音樂補課 個別課 自組班 請假 待補課 原請假日期 原方案 取消補課 重排補課 恢復待點名",
    steps: ["在原課次將學員記錄請假，確認顯示不扣堂；團體班不適用這個補課流程。", "建立或開啟同課程、晚於原請假的新課次，加入學員時從「待補課」選原請假日期；系統會優先帶入原方案。", "送出後在名單查看「原請假日期 → 實際補課日期」；要重排時先取消目前補課，再到新課次重新選原請假。"],
    important: "原方案須仍在效期內且有可用堂數。已安排補課時不能直接把原請假恢復待點名；先取消補課，避免同一次請假被排兩堂。",
    success: "補課名單保留原請假關聯，只占用一次堂數；取消後可重新安排，原請假歷史不消失。",
    details: ["補課只由有權限的人員逐位安排，批次加入不能夾帶補課關聯；跨店、不同課程、團體班或早於原請假的課次會被拒絕。", "補課出席扣原方案一堂；恢復待點名會返還該堂。方案到期、名額已滿或狀態被他人修改時，先核對最新資料。"],
    modules: ["course"], permission: "booking.create", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/actions/course-members.ts", "src/server/services/course-booking.ts", "supabase/migrations/20260928101128_course_student_makeup_link.sql"],
  },
  {
    id: "C152", category: "money", title: "音樂學員要續報，怎麼從課表名單完成繳費？",
    summary: "從學員列的其他操作開啟繳費，只列適用本課程的已上架堂數方案；完成後留在原名單。",
    answer: "續報會新增一筆購買與付款紀錄，不會覆蓋本期；下期尚未排課時仍要另外排課。",
    path: "音樂課表 → 課程名單 → 學員 → 其他操作 → 學員繳費",
    keywords: "音樂續報 學員繳費 下期已繳 課表名單 建立方案 現金 轉帳末四碼 折扣 下期排課",
    steps: ["在正確課次開啟名單，核對學員後點「其他操作」→「學員繳費」。", "選適用本課程的堂數方案，核對堂數、定價、優惠、付款方式；轉帳時填末四碼。", "點「確認已收款並建立方案」，回原名單核對下期已繳堂數、付款日期／金額／方式，以及是否已有下期課次。"],
    important: "按確認代表實際款項已收；只查價格或尚未入帳時不要送出。連線結果不明先查購買紀錄，不能重做第二筆。",
    success: "只新增一筆購買及付款，學員仍在原名單；本期與下期堂數、金額及日期分開顯示。",
    details: ["需要方案建立及交易建立權限；使用優惠另需折扣權限。音樂教室只列堂數方案，不會建立點數方案。", "方案未上架或不適用本課程時不會出現在名單繳費視窗；購買完成不等於下期已排課。"],
    modules: ["course"], permission: "wallet.create", additionalPermissions: ["transaction.create", "booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/components/admin/course-assignment-payment.tsx", "src/server/actions/course-members.ts", "src/server/services/course-assignment-checkout.ts"],
  },
];
