import type { OperationGuide } from "./operation-guide-types";

/** Source review at main ecca3f09. Logged-in operation acceptance remains separate. */
export const dailyOperationGuides20261003: OperationGuide[] = [
  {
    id: "C160", category: "customers", title: "課程顧客標籤如何建立、套用與篩選？",
    summary: "總部開通顧客標籤後，店長還要在本店設定啟用並建立分類；同店各模組會共用標籤。",
    answer: "分類與標籤名稱最多 8 字；在顧客或名單勾選即時儲存，顧客清單可先依標籤篩選再分頁。",
    path: "設定 → 顧客標籤；顧客管理／上課名單 → 標籤",
    keywords: "顧客標籤 分類 八字 顏色 篩選 共用 即時儲存 停用 所屬教練",
    steps: ["先確認總部已開通顧客標籤，再由店長在課程設定啟用。", "建立分類與標籤，核對固定編號、顏色及排序；再到顧客或上課名單勾選正確標籤。", "回顧客清單用標籤篩選並翻頁核對；停用前先確認既有顧客仍需保留哪些標籤。"],
    important: "關閉功能或停用分類不會刪除既有資料；標籤只供店內人員使用，沒有顧客編輯權限者不能修改。",
    success: "同店不同模組顯示一致標籤，篩選後每頁只出現符合顧客，儲存失敗會還原。",
    details: ["分類編號固定且不重用，顏色依編號循環；改名與排序不改色。", "名單顯示會依欄寬收合，點開才能看全部；目前不提供批次貼標籤。", "運動顧客可另設所屬教練；音樂顧客隱藏此欄。"],
    modules: ["course"], permission: "customer.read", additionalPermissions: ["customer.update"], feature: "customer_labels", kind: "howto", verification: "source-reviewed",
    sources: ["docs/shared-customer-labels.md", "src/lib/customer-labels.ts", "src/app/(dashboard)/dashboard/courses/member-workspace.tsx"],
  },
  {
    id: "C161", category: "booking", title: "如何新增空間租借、收款或取消？",
    summary: "先選教室、租借人與起訖時間；租金依 30 分鐘比例計算，也可建立後再收款。",
    answer: "租借只占用教室，不加入上課名單、不扣方案也不產生出席；取消會釋出空間，但原收款會保留供後續退款或作廢。",
    path: "課表排程 → 空白時段／新增 → 空間租借",
    keywords: "空間租借 教室 租金 30分鐘 緩衝 先收款 取消 更正 作廢 其他收入",
    steps: ["從課表空白時段新增租借，搜尋既有顧客；找不到且有權限時再新增顧客。", "選可租借教室、起訖時間，核對前後緩衝、按 30 分鐘比例計算的應收金額；需要時勾選先收款並選付款方式。", "儲存後在課表與租借紀錄核對；取消時確認空間已釋出，若已收款另走更正、作廢或退款流程。"],
    important: "課程與租借共用教室衝突檢查。取消租借不會自動退款；不能因租借取消就重做一筆收款。",
    success: "課表顯示租借與正確教室、時間及收款狀態，營運現金列入其他收入，沒有方案扣點或出席紀錄。",
    details: ["教室要先開放租借並設定每小時租金；前後緩衝也會占用教室。", "先收款需收款權限；更正或作廢需對應權限與原因。取消後仍可查看原付款。", "租借人電話可撥打；搜尋與新增顧客仍受本店範圍與顧客權限限制。"],
    modules: ["course"], permission: "booking.create", additionalPermissions: ["booking.read", "customer.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/rental-panel.tsx", "src/lib/course-rental.ts", "src/server/actions/course-rental.ts"],
  },
  {
    id: "C162", category: "booking", title: "教師或教練請假、曠課後，學員權益怎麼返還？",
    summary: "在課次名單記錄教師請假或曠課後，整堂免點名並返還已扣或保留的方案權益。",
    answer: "體驗收款不會因教師缺席自動退款；恢復課次只回到待處理，也不會重新扣回已返還權益。",
    path: "課表排程 → 課次名單 → 教師／教練狀態",
    keywords: "教師請假 教練請假 曠課 返還權益 免點名 體驗退款 恢復課次 免費補課",
    steps: ["打開正確課次，核對教師與所有學員後，選教師請假或曠課並填原因。", "確認整堂顯示免點名，逐位核對原保留或已扣額度已返還；體驗收款另行核對。", "若選錯可恢復為待處理；音樂老師曠課需要補課時，再建立與原課關聯的免費補課。"],
    important: "教師缺席和取消課程、學員請假、退款是不同流程。恢復後不得假設系統會自動重新扣堂。",
    success: "課次保留缺席原因及更正紀錄，學員沒有重複扣堂；需要的免費補課另有課次與原課關聯。",
    details: ["記錄教師缺席後不能再對該堂學員出席點名；須先恢復。", "體驗金額維持原收款，若需退費請走正式退款或作廢流程。", "音樂老師曠課才可安排免費補課；補課不增加原方案堂數或課期。"],
    modules: ["course"], permission: "booking.update", additionalPermissions: ["booking.read"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/roster.tsx", "src/server/actions/course.ts", "src/__tests__/course-teacher-absence-refund.test.ts"],
  },
  {
    id: "C163", category: "staff", title: "教練每週可授課時段怎麼改？既有課會消失嗎？",
    summary: "修改每週可授課時段後先儲存；超出新時段的既有課仍保留並列出，須另外逐堂處理。",
    answer: "新排課或改日期、時間、教練會檢查可授課時段；只改名稱、備註不重查原時段。",
    path: "教練管理 → 編輯教練 → 工作與授課安排",
    keywords: "可授課時段 每週時段 既有課 保留 超出範圍 單日請假 排課衝突",
    steps: ["開啟正確教練，編輯每週可授課日期與起訖時間，先排除重疊、未填完整或開始晚於結束。", "儲存後查看超出新時段的既有課清單；依實際安排逐堂改期、換教練或取消。", "另有單日請假時，到對應流程處理該日課次，不要只縮短每週時段。"],
    important: "儲存每週時段不會自動取消課程、退堂或發通知；未處理的既有課仍在課表。",
    success: "新排課只允許落在可授課時段，既有超出範圍課次有明確清單且未被靜默刪除。",
    details: ["新增或修改課次會重查營業時間、教練、教室及可授課範圍。", "畫面會在原欄位標示重疊、起訖錯誤或未填完整，修正後才可送出。", "單日請假與每週時段是不同資料，不會互相代替。"],
    modules: ["course"], permission: "staff.manage", additionalPermissions: ["staff.view"], feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/course-staff-availability-editor.tsx", "docs/course-coach-notifications.md", "src/server/actions/course-staff.ts"],
  },
  {
    id: "C164", category: "care", title: "教練的明日課表、課程異動與體驗通知怎麼開？",
    summary: "三種 LINE 通知各自開關且預設關閉；開啟後只記錄新事件，可先預覽訊息而不發送。",
    answer: "明日摘要在台灣時間 21:00 建立、無課不發；通知連結只開本人工作課表與指定日期，不放寬權限。",
    path: "設定 → 通知與顧客經營 → 提醒管理 → 教練／老師",
    keywords: "教練通知 明日授課摘要 21:00 課程異動 體驗學員 預覽 LINE 發送紀錄 重試",
    steps: ["進入教練／老師提醒，分別決定明日授課摘要、課程異動、體驗學員通知是否開啟。", "用預覽核對內容；預覽不儲存也不發 LINE。開啟後再以新建立或新異動的測試事件核對紀錄。", "從發送紀錄查收件人、狀態與略過原因；通知連結應開啟本人工作課表及正確日期。"],
    important: "未綁定 LINE、店家提醒關閉、額度不足、預覽隔離或事件無效都可能略過；課程操作成功不等於訊息送達。",
    success: "三個開關互不影響，新事件有可追查紀錄；無課摘要不發，預覽不產生真實通知。",
    details: ["摘要只列本人授課並含體驗人數；超過 8 筆會收合，已送摘要後新增隔日課程可補充通知。", "同交易、同教練、同類型合併通知；失敗會依固定內容重試，超過 23 小時停止自動重送。", "正式 LINE 送達仍須在確認收件人的受控環境另外驗收，不能用預覽圖替代。"],
    modules: ["course"], permission: "business_hours.manage", feature: "line_reminder", kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/reminders/coach-notification-settings.tsx", "src/lib/course-coach-notifications.ts", "docs/course-coach-notifications.md"],
  },
  {
    id: "C165", category: "booking", title: "課表月、週、日怎麼搜尋與篩選課程？",
    summary: "月／週／日共用名稱搜尋、課程與所屬教練篩選；課程與租借用不同色點及計數。",
    answer: "篩選只改目前查看範圍，不會更改課次。空白時段可直接新增排課或租借，送出仍會重查衝突。",
    path: "課表排程 → 月／週／日",
    keywords: "課表 月表 週表 日表 搜尋 課程篩選 所屬教練 色點 租借 空白時段 點名完成度",
    steps: ["先切月、週或日並選日期，再輸入名稱或選課程、所屬教練篩選。", "依色點、課程堂數、租借筆數及點名完成度找到正確項目；月表可開啟該日完整清單。", "需要新增時點空白時段，選排課或租借；儲存後清除篩選核對完整課表。"],
    important: "租借不是課程，不會顯示教練、容量、加入學員或點名；隱藏筆數只代表目前畫面收合。",
    success: "三種檢視顯示相同日期與正確篩選結果，課程／租借不混淆，清除條件後資料完整。",
    details: ["完成度以已處理點名／應點名人數計算；教師請假或曠課顯示免點名。", "30 分鐘卡片會縮短資訊，詳細狀態請開課次或當日清單。", "新增排課與租借都會檢查教室占用；篩選結果不能代替衝突檢查。"],
    modules: ["course"], permission: "booking.read", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["src/app/(dashboard)/dashboard/courses/workspace.tsx", "src/app/(dashboard)/dashboard/courses/roster.tsx", "src/app/(dashboard)/dashboard/courses/rental-panel.tsx"],
  },
  {
    id: "I14", category: "settings", title: "總部的功能狀態：隱藏、鎖定、啟用與跟隨方案有何差別？",
    summary: "隱藏會移除入口，鎖定保留入口但不可使用，啟用授予功能；跟隨方案則回到目前方案與試用規則。",
    answer: "功能狀態只改資格，不會刪除預約、錢包、收款、標籤或健康資料；角色與操作權限仍另外檢查。",
    path: "總部後台 → 店舖管理 → 功能開通",
    keywords: "總部 功能狀態 隱藏 鎖定 啟用 跟隨方案 INHERIT HIDDEN LOCKED ENABLED 試用 覆寫",
    steps: ["在 HQ 選正確店舖與功能，先核對目前方案、來源及生效／到期時間。", "選隱藏、鎖定、啟用或跟隨方案後儲存，再核對狀態摘要。", "用相符角色檢查側欄、設定內入口與直接網址；另核對原資料仍保留。"],
    important: "總部啟用功能不會自動授予員工操作權限；有期限的覆寫尚未開始或已過期時會回到方案。",
    success: "入口呈現與所選狀態一致，直接操作也受服務端拒絕或允許，歷史營運資料未被刪除。",
    details: ["有效明確覆寫優先於試用預設；舊 DISABLED 試用例外保留相容。", "隱藏與鎖定都不允許使用，差別在是否顯示不可用入口。", "跨店、分析、月結、顧客標籤、課程候補、健康與裝置預覽等項目可依此管理。"],
    modules: ["steamfoot", "spa", "course"], permission: "staff.manage", feature: null, kind: "why", verification: "source-reviewed",
    sources: ["docs/hq-feature-three-state.md", "src/lib/store-feature-catalog.ts", "src/lib/effective-entitlement.ts"],
  },
  {
    id: "I15", category: "settings", title: "總部如何查看體驗版申請、改進度或重試通知？",
    summary: "HQ 管理員可查看申請與補件版本、更新處理進度，並對失敗通知執行重試。",
    answer: "申請者可用專屬補件連結續填同一申請；總部重試通知不會另建一筆申請，預覽環境仍禁止真實寄信。",
    path: "總部後台 → 店舖管理 → 體驗版申請",
    keywords: "體驗版申請 總部 收件 補件 同一編號 修訂 進度 待補件 通知重試 Email Google Sheet",
    steps: ["由 HQ ADMIN 開啟體驗版申請，依店名與進度篩選後展開正確申請。", "核對基本資料、缺件與最新修訂，再更新處理進度；重新整理確認畫面與紀錄一致。", "只有通知失敗時才重試，先核對固定收件、服務設定與發送紀錄；不要用手動寄信冒充系統成功。"],
    important: "此頁限 HQ ADMIN 且需人員管理權限。專屬補件 token 不出現在通知內容，預覽禁寄也不能解除來做驗收。",
    success: "同一申請保留修訂版本與最新進度，通知狀態可追查，未授權帳號無法查看。",
    details: ["公開入口先收基本資料，LINE 可後補；補件連結用 fragment，伺服器只存 token 雜湊。", "正式通知可同步 Email 與同一 Google Sheet 列；重複修訂依版本避免舊頁覆寫。", "程式測試或畫面顯示已送不代表信箱實際收到；真實投遞須由可讀收件匣的人員確認。"],
    modules: ["steamfoot", "spa", "course"], permission: "staff.manage", feature: null, kind: "howto", verification: "source-reviewed",
    sources: ["docs/trial-application-release.md", "src/lib/trial-application.ts", "src/app/hq/dashboard/trial-applications/page.tsx"],
  },
];
