'use client';
import { useState,useTransition } from 'react';
import { toast } from 'sonner';
import { setCoachNotification } from '@/server/actions/course-coach-notifications';
import { COACH_NOTICE_KINDS,COACH_NOTICE_LABELS,type CoachNoticeKind } from '@/lib/course-coach-notifications';
export function CoachNotificationSettings({initial,teachers,logs}:{initial:Record<CoachNoticeKind,boolean>;teachers:{id:string;name:string;bound:boolean}[];logs:{id:string;name:string;kind:CoachNoticeKind;status:string;reason:string;time:string}[]}) {
 const [settings,setSettings]=useState(initial),[pending,start]=useTransition();
 const descriptions={DIGEST:'每日 21:00 · 只通知本人明日課程',CHANGE:'調課、停課、取消與代課',TRIAL:'新增體驗學員及已通知資料異動'};
 const statuses:Record<string,string>={READY:'待發送',PENDING:'處理中',SENT:'已發送',SKIPPED:'已跳過',FAILED:'待重試',BLOCKED:'需確認'};
 return <div className="space-y-4"><section className="rounded-xl border border-earth-200 bg-white px-4">
 {COACH_NOTICE_KINDS.map(kind=><label key={kind} className="flex items-center justify-between gap-4 border-b border-earth-100 py-3 last:border-0"><span><span className="font-medium text-primary-800">{COACH_NOTICE_LABELS[kind]}</span><span className="ml-3 text-sm text-earth-500">{descriptions[kind]}</span></span><input type="checkbox" role="switch" aria-label={COACH_NOTICE_LABELS[kind]} checked={settings[kind]} disabled={pending} onChange={e=>{const enabled=e.target.checked;start(async()=>{try{const result=await setCoachNotification({kind,enabled});if(result.success){setSettings(s=>({...s,[kind]:enabled}));toast.success('通知設定已儲存');}else toast.error(result.error);}catch{toast.error('儲存失敗，請重試');}});}} className="h-5 w-5 accent-primary-700"/></label>)}
 </section><section className="rounded-xl border border-earth-200 bg-white p-4"><h2 className="mb-2 font-medium text-primary-800">教練／老師 LINE 綁定</h2><div className="grid gap-x-6 sm:grid-cols-2">{teachers.map(t=><div key={t.id} className="flex justify-between gap-3 border-b border-earth-100 py-2"><span>{t.name}</span><span className={t.bound?'text-primary-700':'text-earth-500'}>{t.bound?'已綁定':'尚未完成綁定'}</span></div>)}</div>{!teachers.length&&<p className="text-earth-500">尚無授課人員</p>}</section>
 <section className="rounded-xl border border-earth-200 bg-white p-4"><h2 className="mb-2 font-medium text-primary-800">近期教練通知</h2>{!logs.length?<p className="text-earth-500">尚無紀錄；開啟後只通知新事件。</p>:logs.map(log=><div key={log.id} className="flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-earth-100 py-2 last:border-0"><span className="text-sm text-earth-500">{log.time}</span><span>{log.name}</span><span>{COACH_NOTICE_LABELS[log.kind]}</span><span className="text-primary-700">{statuses[log.status]??log.status}</span>{log.reason&&<span className="text-sm text-earth-500">{log.reason}</span>}</div>)}</section></div>;
}
