"use client";
import {useEffect,useState,useTransition} from "react";
import {RightSheet} from "@/components/admin/right-sheet";
import {DashboardLink} from "@/components/dashboard-link";
import {getSpaCustomerAccount,purchaseSpaCredit,refundSpaPayment} from "@/server/actions/spa-commerce";
import {toLocalDateStr} from "@/lib/date-utils";
type Account=Extract<Awaited<ReturnType<typeof getSpaCustomerAccount>>,{success:true}>;
const money=(n:number)=>`NT$${n.toLocaleString()}`;
const methodName:Record<string,string>={CASH:"現金",CARD:"刷卡",STORED_VALUE:"儲值",ENTITLEMENT:"方案扣次"};
const date=(s:string)=>new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",dateStyle:"short",timeStyle:"short"}).format(new Date(s));
export function SpaCustomersWorkspace({customers,search,canSell,canRefund}:{customers:{id:string;name:string;phone:string|null}[];search:string;canSell:boolean;canRefund:boolean}){
 const [selected,setSelected]=useState<string|null>(null);
 return <main className="mx-auto max-w-6xl space-y-5 p-5 md:p-8"><header className="flex items-center justify-between"><h1 className="text-2xl font-bold">顧客管理</h1><DashboardLink href="/dashboard/customers/new" className="rounded-lg border p-3">新增顧客</DashboardLink></header><form className="flex gap-2"><input name="search" defaultValue={search} placeholder="搜尋姓名／電話" aria-label="搜尋姓名或電話" className="min-w-0 flex-1 rounded-lg border p-3"/><button className="rounded-lg border px-5">搜尋</button></form><div className="divide-y rounded-xl border bg-white">{customers.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className="flex w-full items-center justify-between gap-4 p-4 text-left hover:bg-earth-50"><span><strong>{c.name}</strong><span className="ml-3 text-sm text-earth-500">{c.phone?.startsWith('_')?'':c.phone}</span></span><span className="text-sm">方案與儲值 →</span></button>)}{!customers.length&&<p className="p-5">沒有符合的顧客</p>}</div>{customers.length===100&&<p className="text-sm">顯示前 100 位，請用姓名或電話縮小搜尋。</p>}{selected&&<AccountPanel key={selected} customerId={selected} canSell={canSell} canRefund={canRefund} onClose={()=>setSelected(null)}/>}</main>;
}
function AccountPanel({customerId,canSell,canRefund,onClose}:{customerId:string;canSell:boolean;canRefund:boolean;onClose:()=>void}){
 const [account,setAccount]=useState<Account|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [revision,setRevision]=useState(0),[pending,start]=useTransition();
 const [mode,setMode]=useState<"PACKAGE"|"TOPUP"|null>(null),[packageId,setPackageId]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState<"CASH"|"CARD">("CASH"),[confirmed,setConfirmed]=useState(false),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const [refund,setRefund]=useState<{kind:"SALE"|"RECEIPT";id:string;label:string;method:string}|null>(null),[reason,setReason]=useState("");
 useEffect(()=>{let live=true;getSpaCustomerAccount(customerId).then(r=>{if(live){if(r.success){setAccount(r);setError("");}else setError(r.error);}}).catch(()=>{if(live)setError("讀取失敗，請重試。");});return()=>{live=false;};},[customerId,revision]);
 const pack=account?.packages.find(p=>p.id===packageId);
 const reset=()=>{setMode(null);setRefund(null);setConfirmed(false);setRequestKey(crypto.randomUUID());setRevision(v=>v+1);};
 return <RightSheet open onClose={()=>{if(!pending)onClose();}} width={620} labelledById="spa-account-title"><div className="space-y-5 p-5"><header className="flex items-center justify-between"><h2 id="spa-account-title" className="text-xl font-bold">{account?.customer.name??"顧客帳務"}</h2><button disabled={pending} onClick={onClose}>關閉</button></header>{error&&<p role="alert" className="text-red-700">{error} <button onClick={()=>setRevision(v=>v+1)}>重新讀取</button></p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3">{notice}</p>}{!account?<p>讀取中…</p>:<>
 <section className="rounded-xl bg-earth-50 p-4"><p>儲值餘額</p><strong className="text-2xl">{money(account.wallet?.balance??0)}</strong>{account.wallet&&account.wallet.status!=="ACTIVE"&&<p>帳戶已停用</p>}</section>
 {canSell&&!mode&&!refund&&<div className="grid grid-cols-2 gap-3"><button className="rounded-lg bg-earth-800 p-3 text-white" onClick={()=>{setMode("PACKAGE");setConfirmed(false);}}>購買方案</button><button className="rounded-lg border p-3" onClick={()=>{setMode("TOPUP");setConfirmed(false);}}>儲值加值</button></div>}
 {mode&&<form className="space-y-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();if(!confirmed)return;setError("");start(async()=>{try{const r=await purchaseSpaCredit({customerId,kind:mode,amount:mode==="PACKAGE"?pack?.price??-1:Number(amount),paymentMethod:method,requestKey,...(mode==="PACKAGE"?{packageId,expectedPackageUpdatedAt:pack?.updatedAt}:{})});if(!r.success){setError(r.error);return;}setNotice(mode==="PACKAGE"?"方案已購買，堂數已入帳。":"加值完成，餘額已更新。");reset();}catch{setError("連線失敗，請重試同一筆；不會重複入帳。");}});}}><fieldset disabled={pending} className="space-y-3"><legend className="font-bold">{mode==="PACKAGE"?"購買方案":"儲值加值"}</legend>{mode==="PACKAGE"?<><label className="block">方案<select required value={packageId} onChange={e=>{setPackageId(e.target.value);setConfirmed(false);}} className="mt-1 w-full rounded-lg border p-3"><option value="">請選擇方案</option>{account.packages.map(p=><option key={p.id} value={p.id}>{p.name} · {p.uses} 次 · {money(p.price)}</option>)}</select></label>{pack&&<p>今日起生效，有效 {pack.validityDays} 天（含今日）。應收 {money(pack.price)}。</p>}{!account.packages.length&&<DashboardLink href="/dashboard/plans" className="underline">先到方案管理建立方案</DashboardLink>}</>:<label className="block">加值金額<input required type="number" min={1} max={9999999} step={1} value={amount} onChange={e=>{setAmount(e.target.value);setConfirmed(false);}} className="mt-1 w-full rounded-lg border p-3"/></label>}<label className="block">收款方式<select value={method} onChange={e=>{setMethod(e.target.value as "CASH"|"CARD");setConfirmed(false);}} className="ml-3 rounded border p-2"><option value="CASH">現金</option><option value="CARD">刷卡</option></select></label>{method==="CARD"&&<p className="text-sm">請先在店內刷卡機完成收款。</p>}<label className="flex gap-2"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>確認已收到上述金額</label><div className="flex gap-3"><button disabled={!confirmed||(mode==="PACKAGE"&&!pack)} className="rounded-lg bg-earth-800 p-3 text-white">{pending?"處理中…":"確認收款並入帳"}</button><button type="button" onClick={()=>setMode(null)}>返回</button></div></fieldset></form>}
 {refund&&<form className="space-y-3 rounded-xl border border-red-200 p-4" onSubmit={e=>{e.preventDefault();if(!confirmed)return;setError("");start(async()=>{try{const r=await refundSpaPayment({kind:refund.kind,id:refund.id,reason});if(!r.success){setError(r.error);return;}setNotice("已完成全額退款／退回堂數，紀錄已保留。");reset();}catch{setError("連線失敗，請重試；不會重複退款。");}});}}><fieldset disabled={pending} className="space-y-3"><legend className="font-bold">全額退款 · {refund.label}</legend><p>{refund.method==="CASH"||refund.method==="CARD"?"請確認已透過原付款方式退回款項；刷卡退款需先在刷卡機操作。":"將退回原儲值帳戶或原方案堂數，保留原有效期限。"}</p><label className="block">退款原因<input required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded border p-3"/></label><label className="flex gap-2"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>確認退款內容</label><button disabled={!confirmed} className="rounded-lg bg-red-700 p-3 text-white">確認全額退回</button><button type="button" className="ml-3" onClick={()=>setRefund(null)}>返回</button></fieldset></form>}
 <section><h3 className="mb-2 font-bold">顧客方案</h3><div className="space-y-2">{account.entitlements.map(e=><div key={e.id} className="rounded-lg border p-3"><strong>{e.name}</strong><p>剩餘 {e.remaining} 次 · 已保留 {e.reserved} 次 · 可用 {e.status==='ACTIVE'&&(!e.expiryDate||e.expiryDate>=toLocalDateStr())?Math.max(0,e.remaining-e.reserved):0} 次</p><p className="text-sm text-earth-500">{e.expiryDate?`到期日 ${e.expiryDate}`:"無到期日"} · {e.status==='VOIDED'?'已退購／作廢':e.expiryDate&&e.expiryDate<toLocalDateStr()?'已到期':e.status==='EXHAUSTED'?'已用完':'方案紀錄'}</p></div>)}{!account.entitlements.length&&<p>尚無方案</p>}</div></section>
 <section><h3 className="mb-2 font-bold">收款與結帳紀錄（最近 100 筆）</h3>{[...account.sales.map(s=>({...s,kind:"SALE" as const,uses:null})),...account.receipts.map(r=>({...r,kind:"RECEIPT" as const}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=><div key={r.id} className="border-b py-3"><strong>{r.name}</strong><p>{methodName[r.paymentMethod]} · {r.paymentMethod==='ENTITLEMENT'?`${r.uses} 次`:money(r.amount)} · {r.refunded?"已退款":"已完成"}</p><p className="text-xs text-earth-500">{date(r.createdAt)}</p>{canRefund&&!r.refunded&&!mode&&!refund&&!(r.kind==='SALE'&&('sourceId' in r)&&('kind' in r)&&account.sales.find(s=>s.id===r.id)?.kind==='PACKAGE'&&(()=>{const e=account.entitlements.find(e=>e.id===r.sourceId);return !e||e.remaining!==e.total||e.reserved>0||e.status==='VOIDED';})())&&!(r.kind==='SALE'&&account.sales.find(s=>s.id===r.id)?.kind==='TOPUP'&&(account.wallet?.balance??0)<r.amount)&&<button className="mt-1 text-sm text-red-700 underline" onClick={()=>{setRefund({kind:r.kind,id:r.id,label:`${r.name} · ${r.paymentMethod==='ENTITLEMENT'?`${r.uses} 次`:money(r.amount)}`,method:r.paymentMethod});setReason("");setConfirmed(false);}}>全額退款／退回</button>}</div>)}</section>
 <details><summary className="cursor-pointer font-bold">儲值明細</summary>{account.entries.map(e=><p key={e.id} className="border-b py-2 text-sm">{date(e.createdAt)} · {e.amount>=0?"+":""}{money(e.amount)} · 餘額 {money(e.balanceAfter)}</p>)}</details>
 <details><summary className="cursor-pointer font-bold">退款紀錄</summary>{account.refunds.map(r=><p key={r.id} className="border-b py-2 text-sm">{date(r.createdAt)} · {r.paymentMethod==='ENTITLEMENT'?`${r.uses} 次`:money(r.amount)} · {r.reason}</p>)}</details>
 </>}</div></RightSheet>;
}
