"use client";
import { useState,useTransition } from "react";
import { RightSheet } from "@/components/admin/right-sheet";
import { completeSpaBooking } from "@/server/actions/spa-checkout";
import type { SpaScheduleBooking } from "@/server/queries/spa-schedule";
export function SpaCheckoutPanel({booking,customerName,onClose,onCompleted}:{booking:SpaScheduleBooking;customerName:string;onClose:()=>void;onCompleted:()=>void}){
 const[method,setMethod]=useState<"CASH"|"CARD">("CASH");const[confirmed,setConfirmed]=useState(false);const[error,setError]=useState("");const[pending,start]=useTransition();
 return <RightSheet open onClose={()=>{if(!pending)onClose();}} width={520} labelledById="spa-checkout-title"><form className="space-y-5 p-5" onSubmit={e=>{e.preventDefault();if(!confirmed)return;setError("");start(async()=>{try{const r=await completeSpaBooking({bookingId:booking.id,expectedUpdatedAt:booking.updatedAt,expectedAmount:booking.totalPrice,paymentMethod:method});if(!r.success){setError(r.error);return;}onCompleted();}catch{setError("連線失敗，請重試；同筆預約不會重複入帳。");}});}}><header className="flex justify-between"><h2 id="spa-checkout-title" className="text-xl font-bold">完成並結帳</h2><button type="button" disabled={pending} onClick={onClose}>關閉</button></header><section className="rounded-xl bg-earth-50 p-4"><p className="font-semibold">{customerName}</p><p>{booking.serviceName}</p><p>{booking.startTime}–{booking.endTime}</p><p className="mt-3 text-2xl font-bold">NT${booking.totalPrice.toLocaleString()}</p><p className="mt-2 text-sm text-earth-500">依已儲存的預約金額收款。</p></section><fieldset disabled={pending} className="space-y-3"><legend className="mb-2 font-semibold">收款方式</legend><div className="grid grid-cols-2 gap-3">{([['CASH','現金'],['CARD','刷卡']] as const).map(([value,label])=><label key={value} className={`rounded-lg border p-3 ${method===value?'border-earth-700 bg-earth-50':'border-earth-200'}`}><input type="radio" name="paymentMethod" checked={method===value} onChange={()=>{setMethod(value);setConfirmed(false);}}/> {label}</label>)}</div><p className="text-sm text-earth-500">{method==='CARD'?'請先於店內刷卡機完成收款，此處僅記錄收款結果。':'請確認已收到現金。'}</p><label className="flex items-start gap-2"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已完成服務，並確認收到上述金額</label></fieldset>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={pending||!confirmed} className="w-full rounded-lg bg-earth-800 p-3 font-semibold text-white disabled:opacity-50">{pending?'處理中…':'確認收款並完成'}</button></form></RightSheet>;
}
