"use client";
import { useMemo, useState } from "react";
import type { MusicTeacherSettings } from "@/lib/music-teacher-settings";
export type TeacherFeeDraft = { mode: "CLASS" | "SHARE" | "INHERIT"; value: string; revision: number };
export type TeacherPlan = { id: string; name: string; musicSubjectId?: string | null; subjectName?: string; musicTeacherShare?: number | null; musicPricePerLesson?: number | null };
const input = "min-h-11 min-w-0 rounded-lg border border-earth-200 bg-white px-3 text-sm";
function feeSummary(plan: TeacherPlan, draft: TeacherFeeDraft | undefined, settings: MusicTeacherSettings) {
 const rule = draft && draft.mode !== "INHERIT" ? {mode:draft.mode,value:Number(draft.value)} : plan.musicSubjectId && settings.subjectRules[plan.musicSubjectId] ? settings.subjectRules[plan.musicSubjectId] : {mode:"SHARE",value:(settings.defaultRatio ?? plan.musicTeacherShare ?? NaN)*100};
 if (draft && draft.mode !== "INHERIT" && !draft.value.trim()) return "請填分潤";
 if (!Number.isFinite(rule.value)) return "尚未設定分潤";
 if (rule.mode === "CLASS") return `老師 $${rule.value.toLocaleString("zh-TW")}／堂`;
 const amount = plan.musicPricePerLesson == null ? "" : ` · 定價試算 $${Number((plan.musicPricePerLesson*rule.value/100).toFixed(2)).toLocaleString("zh-TW")}／堂`;
 return `老師 ${Number(rule.value.toFixed(2))}%${amount}`;
}
export function MusicTeacherFeeEditor({templates,qualificationIds,fees,settings,onSettings,onFees,onQualification,invalidTemplateId,readOnly=false,qualificationReadOnly=readOnly}:{invalidTemplateId?:string;readOnly?:boolean;qualificationReadOnly?:boolean;templates:TeacherPlan[];qualificationIds:string[];fees:Record<string,TeacherFeeDraft>;settings:MusicTeacherSettings;onSettings:(s:MusicTeacherSettings)=>void;onFees:(f:Record<string,TeacherFeeDraft>)=>void;onQualification:(id:string,selected:boolean)=>void}) {
 const exceptions = useMemo(()=>qualificationIds.filter(id=>fees[id] && fees[id].mode!=="INHERIT"),[qualificationIds,fees]);
 const [showCourses,setShowCourses]=useState(!qualificationIds.length);
 const [courseSearch,setCourseSearch]=useState("");
 const [exceptionSearch,setExceptionSearch]=useState("");
 const [courseScope,setCourseScope]=useState<"all"|"selected"|"unselected">("all");
 const [subject,setSubject]=useState("");
 const [showExceptions,setShowExceptions]=useState(!!exceptions.length);
 const subjects=[...new Set(templates.map(t=>t.subjectName).filter((v):v is string=>!!v))].sort();
 const selectedPlans=templates.filter(t=>qualificationIds.includes(t.id));
 const visibleCourses=templates.filter(t=>(!courseSearch.trim()||`${t.name} ${t.subjectName??""}`.toLocaleLowerCase().includes(courseSearch.trim().toLocaleLowerCase()))&&(!subject||t.subjectName===subject)&&(courseScope==="all"||(courseScope==="selected")===qualificationIds.includes(t.id)));
 const candidates=selectedPlans.filter(t=>!exceptions.includes(t.id));
 const visibleCandidates=candidates.filter(t=>!exceptionSearch.trim()||t.name.toLocaleLowerCase().includes(exceptionSearch.trim().toLocaleLowerCase()));
 function addException(id:string){const plan=templates.find(t=>t.id===id);if(!plan)return;const ratio=settings.defaultRatio??plan.musicTeacherShare;onFees({...fees,[id]:{mode:"SHARE",value:ratio==null?"":String(Number((ratio*100).toFixed(2))),revision:fees[id]?.revision??0}});}
 return <div className="space-y-4">
  <section>
   <header className="flex flex-wrap items-center justify-between gap-2 border-b border-earth-100 pb-2"><h3 className="font-medium text-primary-900">可教課程 <span className="text-sm font-normal text-earth-500">已選 {qualificationIds.length} 項</span></h3><button type="button" disabled={qualificationReadOnly} className={`${input} text-primary-800`} onClick={()=>setShowCourses(v=>!v)}>{showCourses?"完成選擇":"選擇課程"}</button></header>
   {showCourses && <div className="space-y-2 pt-2">
    <div data-browse-control className="grid gap-2 sm:grid-cols-3"><input className={input} aria-label="搜尋課程" placeholder="搜尋課程" value={courseSearch} onChange={e=>setCourseSearch(e.target.value)}/><select className={input} aria-label="課程選取狀態" value={courseScope} onChange={e=>setCourseScope(e.target.value as typeof courseScope)}><option value="all">全部課程</option><option value="selected">已勾選</option><option value="unselected">未勾選</option></select><select className={input} aria-label="科目篩選" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">全部科目</option>{subjects.map(name=><option key={name}>{name}</option>)}</select></div>
    <div data-browse-control className="flex flex-wrap items-center gap-2 text-sm"><span className="mr-auto text-earth-500">篩選結果 {visibleCourses.length} 項</span><button type="button" disabled={qualificationReadOnly||!visibleCourses.length} className={input} onClick={()=>visibleCourses.forEach(t=>{if(!qualificationIds.includes(t.id))onQualification(t.id,true);})}>勾選這 {visibleCourses.length} 項</button><button type="button" disabled={qualificationReadOnly||!visibleCourses.some(t=>qualificationIds.includes(t.id))} className={input} onClick={()=>visibleCourses.forEach(t=>{if(qualificationIds.includes(t.id))onQualification(t.id,false);})}>取消這 {visibleCourses.length} 項</button></div>
    <div className="grid max-h-64 gap-x-4 overflow-y-auto sm:grid-cols-2">{visibleCourses.map(plan=><label key={plan.id} className="flex min-h-11 items-center gap-2 border-b border-earth-100 py-2 text-sm"><input type="checkbox" disabled={qualificationReadOnly} checked={qualificationIds.includes(plan.id)} onChange={e=>onQualification(plan.id,e.target.checked)}/><span className="min-w-0 break-words">{plan.name}</span></label>)}{!visibleCourses.length&&<p className="col-span-full py-3 text-sm text-earth-500">沒有符合的課程</p>}</div>
   </div>}
   {!showCourses && <ul className="divide-y divide-earth-100">{selectedPlans.map(plan=><li key={plan.id} className="flex flex-wrap justify-between gap-x-3 gap-y-1 py-2 text-sm"><span className="min-w-0 break-words">{plan.name}</span><span className="text-earth-600">{feeSummary(plan,fees[plan.id],settings)}</span></li>)}</ul>}
  </section>
  {!!qualificationIds.length && <>
   <section className="space-y-2 border-t border-earth-200 pt-3"><h3 className="font-medium text-primary-900">老師分潤</h3><div className="flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 text-sm">共同比例<input disabled={readOnly} aria-label="老師全科預設比例" className={`${input} w-24`} type="number" min="0" max="100" step="0.01" value={settings.defaultRatio==null?"":Number((settings.defaultRatio*100).toFixed(2))} placeholder="沿用班型" onChange={e=>onSettings({...settings,defaultRatio:e.target.value===""?null:Number(e.target.value)/100})}/><span>% 給老師</span></label>{settings.defaultRatio!==null&&!readOnly&&<button type="button" className="min-h-11 px-2 text-sm text-primary-800" onClick={()=>onSettings({...settings,defaultRatio:null})}>沿用班型比例</button>}</div><p className="text-sm text-earth-500">{settings.defaultRatio===null?"沿用各班型比例":"套用未個別調整的課程"} · 僅套用新課次</p></section>
   <section className="border-t border-earth-200 pt-2"><button type="button" aria-expanded={showExceptions||!!invalidTemplateId} className="flex min-h-11 w-full items-center justify-between gap-2 text-left text-sm font-medium text-primary-900" onClick={()=>setShowExceptions(v=>!v)}><span>個別課程調整{exceptions.length?`（${exceptions.length}）`:""}</span><span>{showExceptions||invalidTemplateId?"收合":"展開"}</span></button>
    {(showExceptions||invalidTemplateId)&&<div className="space-y-2"><div data-browse-control className="flex flex-wrap gap-2">{candidates.length>6&&<input disabled={readOnly} aria-label="搜尋例外課程" placeholder="搜尋課程" className={`${input} flex-1`} value={exceptionSearch} onChange={e=>setExceptionSearch(e.target.value)}/>}<select disabled={readOnly||!visibleCandidates.length} aria-label="新增彈性拆帳課程" className={`${input} w-full`} value="" onChange={e=>addException(e.target.value)}><option value="">選擇要調整的課程</option>{visibleCandidates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="divide-y divide-earth-100">{exceptions.map(id=>{const plan=templates.find(t=>t.id===id),draft=fees[id];if(!plan||!draft)return null;return <div key={id} className="space-y-2 py-3"><div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="min-w-0 break-words font-medium">{plan.name}</span><span className="text-earth-600">{feeSummary(plan,draft,settings)}</span></div><div className="flex flex-wrap items-center gap-2"><select disabled={readOnly} className={input} aria-label={`${plan.name}拆帳方式`} value={draft.mode} onChange={e=>onFees({...fees,[id]:{...draft,mode:e.target.value as "CLASS"|"SHARE",value:""}})}><option value="SHARE">比例</option><option value="CLASS">每堂固定金額</option></select><input disabled={readOnly} className={`${input} w-24`} aria-invalid={invalidTemplateId===id||undefined} aria-label={`${plan.name}拆帳數值`} type="number" min="0" max={draft.mode==="SHARE"?100:1000000} step="0.01" value={draft.value} required onChange={e=>onFees({...fees,[id]:{...draft,value:e.target.value}})}/><span className="text-sm">{draft.mode==="SHARE"?"% 給老師":"元／堂"}</span><button disabled={readOnly} type="button" className="min-h-11 px-2 text-sm text-primary-800" onClick={()=>onFees({...fees,[id]:{...draft,mode:"INHERIT",value:"0"}})}>恢復共同設定</button></div></div>})}{!exceptions.length&&<p className="py-2 text-sm text-earth-500">全部使用共同設定</p>}</div></div>}
   </section>
  </>}
 </div>;
}
