"use client";
import {useMemo,useState} from "react";
import type {MusicTeacherSettings} from "@/lib/music-teacher-settings";
export type TeacherFeeDraft={mode:"CLASS"|"SHARE"|"INHERIT";value:string;revision:number};
export type TeacherPlan={id:string;name:string;musicSubjectId?:string|null;subjectName?:string;musicTeacherShare?:number|null};
const input="min-h-9 rounded-lg border border-earth-200 bg-white px-2 text-sm";
type SimpleRule={mode:"CLASS"|"SHARE";value:number};
function RuleInput({label,rule,onChange,disabled=false}:{disabled?:boolean;label:string;rule:SimpleRule;onChange:(r:SimpleRule)=>void}) {
 return <div className="flex items-center gap-2"><select disabled={disabled} className={input} aria-label={`${label}拆帳方式`} value={rule.mode} onChange={e=>onChange({mode:e.target.value as "CLASS"|"SHARE",value:e.target.value==="SHARE"?60:0})}><option value="SHARE">比例</option><option value="CLASS">固定費</option></select><input disabled={disabled} className={`${input} w-24`} aria-label={`${label}拆帳數值`} type="number" min="0" max={rule.mode==="SHARE"?1:1000000} step={rule.mode==="SHARE"?0.0001:1} value={rule.mode==="SHARE"?rule.value/100:rule.value} onChange={e=>onChange({...rule,value:Number(e.target.value)*(rule.mode==="SHARE"?100:1)})}/><span className="whitespace-nowrap text-xs text-earth-500">{rule.mode==="SHARE"?"老師比例":"元／堂"}</span></div>;
}
export function MusicTeacherFeeEditor({templates,qualificationIds,fees,settings,onSettings,onFees,onQualification,readOnly=false,qualificationReadOnly=readOnly}:{readOnly?:boolean;qualificationReadOnly?:boolean;templates:TeacherPlan[];qualificationIds:string[];fees:Record<string,TeacherFeeDraft>;settings:MusicTeacherSettings;onSettings:(s:MusicTeacherSettings)=>void;onFees:(f:Record<string,TeacherFeeDraft>)=>void;onQualification:(id:string,selected:boolean)=>void}) {
 const exceptions=useMemo(()=>qualificationIds.filter(id=>fees[id]&&fees[id].mode!=="INHERIT"),[qualificationIds,fees]);
 const [mode,setMode]=useState<"default"|"flexible">(exceptions.length?"flexible":"default");
 const candidates=templates.filter(t=>qualificationIds.includes(t.id)&&!exceptions.includes(t.id));
 const defaultRatio=settings.defaultRatio??0;
 function useDefault(){setMode("default");onSettings({...settings,subjectRules:{}});onFees(Object.fromEntries(Object.entries(fees).map(([id,draft])=>[id,qualificationIds.includes(id)?{...draft,mode:"INHERIT",value:"0"}:draft])));}
 function addException(id:string){if(!id)return;const old=fees[id];onFees({...fees,[id]:{mode:"SHARE",value:String(defaultRatio*100||60),revision:old?.revision??0}});}
 return <div className="space-y-3">
  <div className="grid grid-cols-2 gap-2 rounded-lg bg-earth-50 p-1"><button disabled={readOnly} type="button" onClick={useDefault} className={`min-h-10 rounded-md px-3 text-sm ${mode==="default"?"bg-white font-medium text-primary-900 shadow-sm":"text-earth-600"}`}>預設拆帳</button><button disabled={readOnly} type="button" onClick={()=>setMode("flexible")} className={`min-h-10 rounded-md px-3 text-sm ${mode==="flexible"?"bg-white font-medium text-primary-900 shadow-sm":"text-earth-600"}`}>彈性拆帳</button></div>
  <div className="flex flex-wrap items-center gap-2 rounded-lg border border-earth-200 px-3 py-2"><strong className="text-sm">預設比例</strong><input disabled={readOnly} aria-label="老師全科預設比例" className={`${input} w-24`} type="number" min="0" max="1" step="0.0001" value={settings.defaultRatio??""} placeholder="0.6" onChange={e=>onSettings({...settings,defaultRatio:e.target.value===""?null:Number(e.target.value),subjectRules:{}})}/><span className="text-sm text-earth-500">套用全部課程</span></div>
  <section className="rounded-lg border border-earth-200"><header className="flex items-center justify-between bg-earth-50 px-3 py-2"><h4 className="text-sm font-medium">可教授課程</h4><span className="text-xs text-earth-500">已選 {qualificationIds.length}</span></header><div className="grid grid-cols-1 gap-x-4 px-3 py-2 min-[680px]:grid-cols-2">{templates.map(plan=><label key={plan.id} className="flex min-h-8 items-center gap-2 border-b border-earth-100 text-sm"><input type="checkbox" disabled={qualificationReadOnly} checked={qualificationIds.includes(plan.id)} onChange={e=>onQualification(plan.id,e.target.checked)}/><span className="truncate">{plan.name}</span></label>)}</div></section>
  {mode==="flexible"&&<section className="overflow-hidden rounded-lg border border-earth-200"><header className="flex flex-wrap items-center justify-between gap-2 bg-earth-50 px-3 py-2"><div><h4 className="text-sm font-medium">彈性拆帳</h4><p className="text-xs text-earth-500">{exceptions.length} 項例外</p></div><select disabled={readOnly||!candidates.length} aria-label="新增彈性拆帳課程" className={input} value="" onChange={e=>addException(e.target.value)}><option value="">＋ 新增例外</option>{candidates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></header><div className="divide-y divide-earth-100">{exceptions.map(id=>{const plan=templates.find(t=>t.id===id),draft=fees[id];if(!plan||!draft)return null;return <div key={id} className="grid items-center gap-2 px-3 py-2 min-[680px]:grid-cols-[minmax(10rem,1fr)_auto_auto]"><span className="truncate text-sm">{plan.name}</span><RuleInput disabled={readOnly} label={plan.name} rule={{mode:draft.mode as "CLASS"|"SHARE",value:Number(draft.value)}} onChange={rule=>onFees({...fees,[id]:{mode:rule.mode,value:String(rule.value),revision:draft.revision}})}/><button disabled={readOnly} type="button" className="min-h-9 px-2 text-xs text-earth-500" onClick={()=>onFees({...fees,[id]:{...draft,mode:"INHERIT",value:"0"}})}>恢復預設</button></div>})}{!exceptions.length&&<p className="p-3 text-sm text-earth-500">全部使用預設拆帳</p>}</div></section>}
 </div>;
}
