import {coursePrisma} from "@/lib/course-db";
import {getCurrentUser} from "@/lib/session";
import {checkPermission} from "@/lib/permissions";
import {formatTWDateTime} from "@/lib/date-utils";
import {CourseRoster} from "../../courses/roster";
import {DashboardLink as Link} from "@/components/dashboard-link";
export async function CourseTrialTransactions({storeId,range,readOnly,page,basePath,query,staff,status}:{storeId:string;range:{gte:Date;lte:Date};readOnly:boolean;page:number;basePath:string;query:Record<string,string>;staff?:string;status?:string}){
 const user=await getCurrentUser();if(!user||!await checkPermission(user.role,user.staffId,"trial.read"))return null;
 const where={storeId,bookingKind:"TRIAL",createdAt:range,...(status==="PENDING"?{trialPayments:{none:{status:"SUCCESS"}}}:status==="CONFIRMED"?{trialPayments:{some:{status:"SUCCESS"}}}:status==="VOIDED"?{trialPayments:{some:{status:"VOIDED"}}}:status==="REFUNDED"?{id:"__no_refunded_trial__"}:{}),...(staff?{AND:[{trialPayments:{some:{actorUserId:staff,...(status==="VOIDED"?{status:"VOIDED"}:status==="CONFIRMED"?{status:"SUCCESS"}:{})}}}]}:{})};
 const count=await coursePrisma.courseBooking.count({where});const pages=Math.max(1,Math.ceil(count/20));const selected=Math.min(pages,page);
 const unpaidWhere={AND:[where,{trialPayments:{none:{status:"SUCCESS" as const}}}]};
 const [bookings,unpaidSummary]=await Promise.all([coursePrisma.courseBooking.findMany({where,include:{session:true,trialPayments:{orderBy:{createdAt:"desc"}}},orderBy:{createdAt:"desc"},skip:(selected-1)*20,take:20}),coursePrisma.courseBooking.aggregate({where:unpaidWhere,_count:true,_sum:{trialPrice:true}})]);
 const canRoster=await checkPermission(user.role,user.staffId,"booking.read");const canEdit=!readOnly&&await checkPermission(user.role,user.staffId,"booking.update");
 return <details className="rounded-xl border border-earth-200 bg-white p-4"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-3"><span><strong className="font-semibold">體驗交易</strong><span className="ml-2 text-sm text-earth-500">{count} 位上課者</span></span><span className="text-sm font-medium text-primary-800">待收 {unpaidSummary._count} 人／NT$ {(unpaidSummary._sum.trialPrice??0).toLocaleString()}　展開明細</span></summary><p className="mt-1 text-xs text-earth-600">依體驗建立日期及上方條件篩選；付款、出席分開。原收款更正保留作廢紀錄。</p><ul className="divide-y">{bookings.map(b=>{const paid=b.trialPayments.find(p=>p.status==="SUCCESS");return <li key={b.id} className="py-3"><p className="font-medium">{b.customerName} · {b.session.nameSnapshot}</p><p className="text-sm">{formatTWDateTime(b.session.startsAt)} · {paid?`已收款 NT$ ${paid.amount}`:`未收款 NT$ ${b.trialPrice}`} · {({RESERVED:b.checkedInAt?"已報到":"待出席",ATTENDED:"已出席",NO_SHOW:"未到",CANCELLED:"已取消"} as Record<string,string>)[b.status]}</p>{canRoster&&<details className="mt-2"><summary className="min-h-11 cursor-pointer text-sm text-primary-700">查看名單／體驗收款</summary><CourseRoster sessionId={b.sessionId} capacity={b.session.capacity} canCreate={false} canEdit={canEdit} allowTrialActions={!readOnly}/></details>}</li>})}</ul>{!count&&<p className="py-3 text-sm text-earth-500">此期間沒有符合條件的體驗。</p>}{pages>1&&<nav className="flex gap-4 text-sm"><span>{selected}／{pages}</span>{selected>1&&<Link href={`${basePath}?${new URLSearchParams({...query,trialPage:String(selected-1)})}`}>上一頁</Link>}{selected<pages&&<Link href={`${basePath}?${new URLSearchParams({...query,trialPage:String(selected+1)})}`}>下一頁</Link>}</nav>}</details>;
}
