import {beforeEach,expect,it,vi} from "vitest";
import {fixedCourseFee} from "@/lib/course-fee-payment";
import {recordCourseFeePayment,voidCourseFeePayment} from "@/server/services/course-fee-payment";
import type {Prisma} from "../../generated/course-client";
const m=vi.hoisted(()=>({cash:vi.fn(),manager:vi.fn(),writable:vi.fn(),transaction:vi.fn()}));
vi.mock("@/server/services/course-assignment-checkout",()=>({lockCourseCashDay:m.cash}));
vi.mock("@/server/services/course-access",()=>({courseManager:m.manager,courseTransaction:m.transaction}));
vi.mock("@/lib/subscription-guard",()=>({assertStoreSubscriptionWritable:m.writable}));
vi.mock("next/cache",()=>({revalidatePath:vi.fn()}));
import {payCourseFee,correctCourseFee} from "@/server/actions/course-fee-payment";
const actor={storeId:"A",userId:"owner"};
const input={sessionId:"class",requestKey:"a3407c3e-4ed7-4b85-8a09-5aa4cb5ecdfa",expectedAmount:600,method:"OTHER",note:"已轉帳"};
const row={name:"課程",staffId:"teacher",coachId:"teacher",staffName:"老師",rule:{mode:"CLASS",value:600},endsAt:new Date("2020-01-01"),cancelledAt:null};
const raw=vi.fn(),execute=vi.fn();
const tx={$queryRaw:raw,$executeRaw:execute} as unknown as Prisma.TransactionClient;
beforeEach(()=>{vi.resetAllMocks();execute.mockResolvedValue(1);m.manager.mockResolvedValue({storeId:"A",user:{id:"owner",role:"OWNER"}});});
it("distinguishes zero, missing and legacy fees",()=>{expect(fixedCourseFee({mode:"CLASS",value:0})).toBe(0);expect(fixedCourseFee(null)).toBeNull();expect(fixedCourseFee({mode:"HOUR",value:600})).toBeNull();});
it("records one expense and audit for a whole class",async()=>{raw.mockResolvedValueOnce([]).mockResolvedValueOnce([row]).mockResolvedValueOnce([]);await recordCourseFeePayment(tx,actor,input);expect(execute).toHaveBeenCalledTimes(3);});
it("replay does not create another expense",async()=>{raw.mockResolvedValue([{sessionId:input.sessionId,amount:600,method:"OTHER",note:input.note,voidedAt:null}]);await recordCourseFeePayment(tx,actor,input);expect(execute).not.toHaveBeenCalled();});
it("rejects a changed replay",async()=>{raw.mockResolvedValue([{sessionId:"different",amount:600,method:"OTHER",note:input.note}]);await expect(recordCourseFeePayment(tx,actor,input)).rejects.toThrow();expect(execute).not.toHaveBeenCalled();});
it.each([null,{...row,cancelledAt:new Date()},{...row,endsAt:new Date("2099-01-01")},{...row,coachId:"different"},{...row,rule:{mode:"CLASS",value:500}}])("rejects missing cross-store, cancelled, future or changed class %#",async r=>{raw.mockResolvedValueOnce([]).mockResolvedValueOnce(r?[r]:[]);await expect(recordCourseFeePayment(tx,actor,input)).rejects.toThrow();expect(execute).not.toHaveBeenCalled();});
it("rejects a second request key for an already paid class",async()=>{raw.mockResolvedValueOnce([]).mockResolvedValueOnce([row]).mockResolvedValueOnce([{id:"paid"}]);await expect(recordCourseFeePayment(tx,actor,input)).rejects.toThrow("已登錄付款");expect(execute).not.toHaveBeenCalled();});
it("closed cash drawer blocks all writes",async()=>{raw.mockResolvedValueOnce([]).mockResolvedValueOnce([row]).mockResolvedValueOnce([]);m.cash.mockRejectedValue(new Error("closed"));await expect(recordCourseFeePayment(tx,actor,{...input,method:"CASH"})).rejects.toThrow("closed");expect(execute).not.toHaveBeenCalled();});
it("correction replay does not reverse twice",async()=>{raw.mockResolvedValue([{amount:600,method:"OTHER",voidedAt:new Date(),voidReason:"誤登"}]);await voidCourseFeePayment(tx,actor,{paymentId:input.requestKey,reason:"誤登"});expect(execute).not.toHaveBeenCalled();});
it("checks original expense before correction",async()=>{raw.mockResolvedValueOnce([{amount:600,method:"OTHER",voidedAt:null}]).mockResolvedValueOnce([{amount:500,type:"EXPENSE",paymentMethod:"OTHER"}]);await expect(voidCourseFeePayment(tx,actor,{paymentId:input.requestKey,reason:"誤登"})).rejects.toThrow("不一致");expect(execute).not.toHaveBeenCalled();});
it("rejects non-owner payment and correction",async()=>{m.manager.mockResolvedValue({storeId:"A",user:{id:"coach",role:"STAFF"}});expect((await payCourseFee(input)).success).toBe(false);expect((await correctCourseFee({paymentId:input.requestKey,reason:"誤登"})).success).toBe(false);expect(m.transaction).not.toHaveBeenCalled();});
it("expired subscription prevents writing",async()=>{m.writable.mockRejectedValue(new Error("expired"));expect((await payCourseFee(input)).success).toBe(false);expect(m.transaction).not.toHaveBeenCalled();});
