import { createCipheriv, createHash, randomBytes } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";

const h = vi.hoisted(() => ({ findUnique: vi.fn(), customers: vi.fn(), links: vi.fn(), accounts: vi.fn(), config: vi.fn() }));
vi.mock("server-only", () => ({}));
vi.mock("@/lib/db", () => ({ prisma: { lineRebindRequest: { findUnique: h.findUnique }, customer: { findMany: h.customers }, customerIdentityLink: { findMany: h.links }, account: { findMany: h.accounts } } }));
vi.mock("@/lib/line-config", () => ({ getLineConfigForStore: h.config }));
import { runLineRebindDryRun } from "@/server/services/line-rebind-dry-run";

const uid = "U1234567890abcdef1234567890abcdef";
const hash = (v: string) => createHash("sha256").update(v).digest("hex");
function candidate() { const iv = randomBytes(12); const c = createCipheriv("aes-256-gcm", Buffer.alloc(32, 7), iv); return { userIdHash: hash(uid), ciphertext: Buffer.concat([c.update(uid), c.final()]), iv, authTag: c.getAuthTag(), keyVersion: "v1", expiresAt: new Date(Date.now() + 60_000) }; }
function request(overrides: Record<string, unknown> = {}) { const c = candidate(); const expiresAt = new Date(Date.now() + 60_000); c.expiresAt = expiresAt; return { id: "r1", storeId: "store-hsinchu", customerId: "c1", status: "CANDIDATE_CAPTURED", expiresAt, phoneHash: hash("0912345678"), oldUserIdHash: hash("Uold"), candidate: c, customer: { phone: "0912345678", userId: "user1", lineUserId: "Uold", lineLinkStatus: "LINKED", identityLinks: [{ userId: "user1", lineUserId: "Uold" }] }, ...overrides }; }

describe("LINE rebind dry-run security", () => {
  beforeEach(() => { vi.clearAllMocks(); process.env.LINE_REBIND_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64url"); h.findUnique.mockResolvedValue(request()); h.customers.mockResolvedValue([]); h.links.mockResolvedValue([]); h.accounts.mockResolvedValue([]); h.config.mockReturnValue({ accessToken: "test", expectedBasicId: "@ok" }); vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockResolvedValueOnce(new Response("{}", { status: 200 }))); });
  it("returns READY_FOR_REBIND when all checks pass", async () => { const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("READY_FOR_REBIND"); expect(r.checks.lineProfile).toMatchObject({ status: "PASS" }); expect(r.candidateMaskedUserId).not.toBe(uid); });
  it("rejects a missing request", async () => { h.findUnique.mockResolvedValue(null); await expect(runLineRebindDryRun("none")).rejects.toThrow("LINE_REBIND_REQUEST_NOT_FOUND"); });
  it("fails when candidate is missing", async () => { h.findUnique.mockResolvedValue(request({ candidate: null })); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.candidateIntegrity.code).toBe("CANDIDATE_MISSING"); });
  it("returns EXPIRED before other failures", async () => { h.findUnique.mockResolvedValue(request({ expiresAt: new Date(Date.now() - 1) })); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("EXPIRED"); });
  it("prioritizes EXPIRED over retry and validation failures", async () => { const r0 = request({ expiresAt: new Date(Date.now() - 1), oldUserIdHash: hash("wrong") }); h.findUnique.mockResolvedValue(r0); vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new DOMException("aborted", "AbortError"))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("EXPIRED"); });
  it("fails closed for an oldUserIdHash mismatch", async () => { h.findUnique.mockResolvedValue(request({ oldUserIdHash: hash("other") })); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.oldBindingConsistency.code).toBe("OLD_BINDING_INCONSISTENT"); });
  it("fails closed when expectedBasicId is absent", async () => { h.config.mockReturnValue({ accessToken: "test", expectedBasicId: null }); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.lineBot.code).toBe("LINE_BOT_EXPECTED_ID_MISSING"); });
  it("fails when Bot Info basicId mismatches", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ basicId: "@wrong" }), { status: 200 }))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.lineBot.code).toBe("LINE_BOT_MISMATCH"); });
  it("returns RETRY_REQUIRED when LINE profile is rate limited", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockResolvedValueOnce(new Response("{}", { status: 429 }))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("RETRY_REQUIRED"); expect(r.checks.lineProfile.code).toBe("LINE_RATE_LIMITED"); });
  it("fails for a request outside captured status", async () => { h.findUnique.mockResolvedValue(request({ status: "PENDING_CAPTURE" })); const r = await runLineRebindDryRun("r1"); expect(r.checks.candidateIntegrity.code).toBe("REQUEST_NOT_CAPTURED"); expect(r.overall).toBe("NOT_READY"); });
  it("fails for missing ciphertext", async () => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, candidate: { ...r0.candidate, ciphertext: Buffer.alloc(0) } }); const r = await runLineRebindDryRun("r1"); expect(r.checks.candidateIntegrity.code).toBe("CANDIDATE_MISSING"); });
  it.each(["iv", "authTag"])("fails for missing %s", async (field) => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, candidate: { ...r0.candidate, [field]: Buffer.alloc(0) } }); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.candidateIntegrity.code).toBe("CANDIDATE_MISSING"); });
  it("fails for a candidate hash mismatch", async () => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, candidate: { ...r0.candidate, userIdHash: hash("wrong") } }); const r = await runLineRebindDryRun("r1"); expect(r.checks.candidateIntegrity.code).toBe("CANDIDATE_HASH_MISMATCH"); });
  it("fails closed on AES-GCM authentication failure without calling LINE", async () => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, candidate: { ...r0.candidate, authTag: Buffer.alloc(16, 1) } }); const r = await runLineRebindDryRun("r1"); expect(r.checks.candidateIntegrity.code).toBe("CANDIDATE_DECRYPT_FAILED"); expect(fetch).not.toHaveBeenCalled(); });
  it("fails for an unlinked customer", async () => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, customer: { ...r0.customer, lineLinkStatus: "UNLINKED" } }); const r = await runLineRebindDryRun("r1"); expect(r.checks.oldBindingConsistency.code).toBe("OLD_BINDING_INCONSISTENT"); });
  it.each([{ identityLinks: [] }, { identityLinks: [{ userId: "user1", lineUserId: "Uold" }, { userId: "user1", lineUserId: "Uold" }] }])("fails for invalid identity-link cardinality", async ({ identityLinks }) => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, customer: { ...r0.customer, identityLinks } }); const r = await runLineRebindDryRun("r1"); expect(r.checks.identityLinkConsistency.code).toBe("IDENTITY_LINK_INCONSISTENT"); });
  it("fails when identity-link LINE ID differs from customer", async () => { const r0 = request(); h.findUnique.mockResolvedValue({ ...r0, customer: { ...r0.customer, identityLinks: [{ userId: "user1", lineUserId: "Udifferent" }] } }); const r = await runLineRebindDryRun("r1"); expect(r.checks.identityLinkConsistency.code).toBe("IDENTITY_LINK_INCONSISTENT"); });
  it("returns NOT_READY for profile 404", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockResolvedValueOnce(new Response("{}", { status: 404 }))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.lineProfile.code).toBe("LINE_PROFILE_NOT_FOUND"); });
  it("returns RETRY_REQUIRED for profile 5xx", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockResolvedValueOnce(new Response("{}", { status: 500 }))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("RETRY_REQUIRED"); expect(r.checks.lineProfile.code).toBe("LINE_UPSTREAM_ERROR"); });
  it.each([401, 403])("returns NOT_READY for profile %i", async (status) => { vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockResolvedValueOnce(new Response("{}", { status }))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); });
  it("returns RETRY_REQUIRED for profile timeout", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockRejectedValueOnce(new DOMException("aborted", "AbortError"))); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("RETRY_REQUIRED"); expect(r.checks.lineProfile.code).toBe("LINE_TIMEOUT"); });
  it("prioritizes RETRY_REQUIRED over a customer conflict", async () => { h.customers.mockResolvedValue([{ id: "foreign", userId: "other" }]); vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ basicId: "@ok" }), { status: 200 })).mockRejectedValueOnce(new DOMException("aborted", "AbortError"))); const r = await runLineRebindDryRun("r1"); expect(r.checks.customerConflict.status).toBe("FAIL"); expect(r.checks.lineProfile.status).toBe("RETRY"); expect(r.overall).toBe("RETRY_REQUIRED"); });
  it("fails when a foreign customer owns the candidate", async () => { h.customers.mockResolvedValue([{ id: "foreign", userId: "other" }]); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.customerConflict.code).toBe("CANDIDATE_USED_BY_OTHER_CUSTOMER"); });
  it("fails when a foreign customer without a user owns the candidate", async () => { h.customers.mockResolvedValue([{ id: "foreign", userId: null }]); const r = await runLineRebindDryRun("r1"); expect(r.overall).toBe("NOT_READY"); expect(r.checks.customerConflict.code).toBe("CANDIDATE_USED_BY_OTHER_CUSTOMER"); });
  it("does not treat the target customer as a candidate conflict", async () => { h.customers.mockResolvedValue([{ id: "c1", userId: "user1" }]); const r = await runLineRebindDryRun("r1"); expect(r.checks.customerConflict).toMatchObject({ status: "PASS", code: "NO_CONFLICT" }); expect(r.overall).toBe("READY_FOR_REBIND"); });
  it("scopes Customer and IdentityLink conflicts to the request store", async () => { await runLineRebindDryRun("r1"); expect(h.customers).toHaveBeenCalledWith({ where: { storeId: "store-hsinchu", lineUserId: uid }, select: { id: true, userId: true } }); expect(h.links).toHaveBeenCalledWith({ where: { storeId: "store-hsinchu", OR: [{ lineUserId: uid }, { provider: "line", providerAccountId: uid }] }, select: { customerId: true, userId: true } }); expect(h.accounts).toHaveBeenCalledWith({ where: { provider: "line", providerAccountId: uid }, select: { userId: true } }); });
  it("fails when a foreign identity link owns the candidate", async () => { h.links.mockResolvedValue([{ customerId: "foreign", userId: "other" }]); const r = await runLineRebindDryRun("r1"); expect(r.checks.customerConflict.code).toBe("CANDIDATE_USED_BY_OTHER_CUSTOMER"); });
});
