import { describe, expect, it } from "vitest";
import { AUDIT_MIGRATION, PAYMENT_MIGRATION, hasExactSchema, hasResolveLedger, parseArgs, prismaCliEnv, repairVerified, repositoryChecksum, safeRls, verifiedDirectUrl } from "../../scripts/production-migration-reconciliation";

const snapshot = { columns: [
  ["id","text","text",false,null],["storeId","text","text",false,null],["requestedByUserId","text","text",false,null],["createdAt","timestamp without time zone","timestamp",false,"CURRENT_TIMESTAMP"],["completedAt","timestamp without time zone","timestamp",true,null],["status","USER-DEFINED","MessengerAuditStatus",false,"'RUNNING'::\"MessengerAuditStatus\""],["appValidated","boolean","bool",true,null],["pageTokenMatches","boolean","bool",true,null],["callbackMatches","boolean","bool",true,null],["configuredFields","ARRAY","_text",false,"ARRAY[]::TEXT[]"],["missingFields","ARRAY","_text",false,"ARRAY[]::TEXT[]"],["pageAttached","boolean","bool",true,null],["callsSafeSummary","jsonb","jsonb",true,null],["errorCode","text","text",true,null],
].map(([name,dataType,udt,nullable,defaultValue])=>({name:name as string,dataType:dataType as string,udt:udt as string,nullable:nullable as boolean,defaultValue:defaultValue as string|null})), indexes:[['MessengerAuditRun_pkey',true,['id']],['MessengerAuditRun_storeId_createdAt_idx',false,['storeId','createdAt']],['MessengerAuditRun_requestedByUserId_createdAt_idx',false,['requestedByUserId','createdAt']]].map(([name,unique,columns])=>({name:name as string,unique:unique as boolean,columns:columns as string[]})), foreignKeys:[['MessengerAuditRun_storeId_fkey','storeId','public','Store','id','CASCADE','CASCADE'],['MessengerAuditRun_requestedByUserId_fkey','requestedByUserId','public','User','id','CASCADE','RESTRICT']].map(([name,column,schema,table,targetColumn,onUpdate,onDelete])=>({name:name as string,column:column as string,schema:schema as string,table:table as string,targetColumn:targetColumn as string,onUpdate:onUpdate as string,onDelete:onDelete as string})), rlsEnabled:true,rlsForced:true,policyCount:0,rowCount:0 };
describe("reconciliation fail-closed contract",()=>{
 it("rejects malformed CLI before any connection",()=>{ expect(()=>parseArgs(['--stage=repair-rls','--stage=resolve-audit-run','--apply','--confirm=x'])).toThrow(); expect(()=>parseArgs(['--stage=inspect','extra'])).toThrow(); expect(parseArgs(['--stage=inspect']).stage).toBe('inspect'); });
 it("uses only verified DIRECT_URL for Prisma CLI",()=>{const direct='postgresql://postgres.project:x@host:5432/db'; expect(verifiedDirectUrl({VERCEL_ENV:'production',DIRECT_URL:direct})).toContain('host'); expect(prismaCliEnv(direct).DATABASE_URL).toBe(direct);});
 it("rejects any schema drift",()=>{expect(hasExactSchema(snapshot)).toBe(true); expect(safeRls(snapshot)).toBe(true); expect(hasExactSchema({...snapshot,indexes:snapshot.indexes.map((x,i)=>i?x:{...x,columns:['storeId']})})).toBe(false); expect(safeRls({...snapshot,rlsForced:false})).toBe(false);});
 it("requires exact failed-ledger and status",()=>{const r={checksum:repositoryChecksum(),finishedAt:null,rolledBackAt:null,steps:0}; const s=`${AUDIT_MIGRATION} failed\n${PAYMENT_MIGRATION} pending`; expect(hasResolveLedger([r],s)).toBe(true); expect(hasResolveLedger([r],`${s}\n20260901090000_other pending`)).toBe(false);});
 it("requires a fresh post-write snapshot with unchanged rows and secured RLS",()=>{expect(repairVerified(snapshot,{...snapshot,rowCount:1})).toBe(false);expect(repairVerified(snapshot,{...snapshot,rlsEnabled:false})).toBe(false);expect(repairVerified(snapshot,{...snapshot,rlsForced:false})).toBe(false);expect(repairVerified(snapshot,{...snapshot,policyCount:1})).toBe(false);expect(repairVerified(snapshot,{...snapshot})).toBe(true);});
});
