import {beforeEach,describe,it,expect,vi} from "vitest";
const m=vi.hoisted(()=>({permission:vi.fn(),store:vi.fn(),installation:vi.fn(),tx:vi.fn(),booking:vi.fn(),receipt:vi.fn(),create:vi.fn(),update:vi.fn()}));
vi.mock("next/cache",()=>({revalidatePath:vi.fn()}));
vi.mock("@/lib/permissions",()=>({requirePermission:m.permission}));
vi.mock("@/server/actions/spa-resources",()=>({spaResourceStore:m.store}));
vi.mock("@/lib/db",()=>({prisma:{storeModuleInstallation:{findUnique:m.installation}}}));
vi.mock("@/lib/spa-db",()=>({spaPrisma:{$transaction:m.tx}}));
import {completeSpaBooking} from "@/server/actions/spa-checkout";
const date=new Date("2026-09-10T01:00:00.000Z"),input={bookingId:"B",expectedUpdatedAt:date.toISOString(),expectedAmount:1800,paymentMethod:"CASH" as const};
beforeEach(()=>{vi.clearAllMocks();m.permission.mockResolvedValue({id:"owner"});m.store.mockResolvedValue("test");m.installation.mockResolvedValue({status:"ACTIVE"});m.booking.mockResolvedValue({id:"B",status:"CONFIRMED",totalPriceSnapshot:1800,updatedAt:date});m.receipt.mockResolvedValue(null);m.create.mockResolvedValue({id:"R"});m.tx.mockImplementation(async fn=>fn({$executeRaw:vi.fn(),spaBooking:{findFirst:m.booking,update:m.update},spaReceipt:{findUnique:m.receipt,create:m.create}}));});
describe("isolated SPA checkout",()=>{
 it("records the stored amount and completes in one transaction",async()=>{expect(await completeSpaBooking(input)).toEqual({success:true,receiptId:"R"});expect(m.permission).toHaveBeenCalledWith("transaction.create");expect(m.store).toHaveBeenCalledWith("booking.update");expect(m.create).toHaveBeenCalledWith({data:{storeId:"test",bookingId:"B",amount:1800,paymentMethod:"CASH",recordedByUserId:"owner"}});expect(m.update).toHaveBeenCalledWith({where:{id_storeId:{id:"B",storeId:"test"}},data:{status:"COMPLETED"}});});
 it("returns the original receipt on an identical retry",async()=>{m.booking.mockResolvedValue({id:"B",status:"COMPLETED"});m.receipt.mockResolvedValue({id:"R",amount:1800,paymentMethod:"CASH"});expect((await completeSpaBooking(input)).success).toBe(true);expect(m.create).not.toHaveBeenCalled();expect(m.update).not.toHaveBeenCalled();});
 it("does not change an existing payment method",async()=>{m.booking.mockResolvedValue({id:"B",status:"COMPLETED"});m.receipt.mockResolvedValue({id:"R",amount:1800,paymentMethod:"CARD"});expect((await completeSpaBooking(input)).success).toBe(false);expect(m.create).not.toHaveBeenCalled();});
 it.each(["CANCELLED","NO_SHOW","COMPLETED"])("rejects %s without inserting a receipt",async status=>{m.booking.mockResolvedValue({id:"B",status,totalPriceSnapshot:1800,updatedAt:date});expect((await completeSpaBooking(input)).success).toBe(false);expect(m.create).not.toHaveBeenCalled();});
 it("rejects stale amount and stale version",async()=>{expect((await completeSpaBooking({...input,expectedAmount:1})).success).toBe(false);expect((await completeSpaBooking({...input,expectedUpdatedAt:"2026-09-09T00:00:00.000Z"})).success).toBe(false);expect(m.create).not.toHaveBeenCalled();});
 it("scopes lookup to the authorized store",async()=>{m.booking.mockResolvedValue(null);expect((await completeSpaBooking(input)).success).toBe(false);expect(m.booking).toHaveBeenCalledWith({where:{id:"B",storeId:"test"}});expect(m.create).not.toHaveBeenCalled();});
 it("denies missing permission before any transaction",async()=>{m.permission.mockRejectedValue(new Error("denied"));expect((await completeSpaBooking(input)).success).toBe(false);expect(m.tx).not.toHaveBeenCalled();});
 it("does not report success when completion fails after receipt insertion",async()=>{m.update.mockRejectedValueOnce(new Error("failure"));expect((await completeSpaBooking(input)).success).toBe(false);});
});
