/* eslint-disable @typescript-eslint/no-explicit-any -- Transaction adapter tests exercise real service decisions. */
import {beforeEach,describe,it,expect,vi} from "vitest";
import {Prisma} from "@prisma/client";
const m=vi.hoisted(()=>({tx:{} as any,permission:vi.fn(),lock:vi.fn(),audit:vi.fn(),replacement:vi.fn()}));
vi.mock("./inventory",()=>({inventoryContext:async(code:string)=>{await m.permission(code);return {storeId:"s",user:{id:"u",name:"店長",staffId:"staff"}};},inventoryTransaction:async(_c:unknown,f:any)=>f(m.tx),inventoryAudit:m.audit,hashInput:(v:unknown)=>JSON.stringify(v),assertReplay:(hash:string,v:unknown)=>{if(hash!==JSON.stringify(v))throw Error("衝突");},createInventoryPayment:m.replacement}));
vi.mock("./cash-day",()=>({lockCashDay:m.lock}));
import {settleInventory,correctInventoryPayment} from "./inventory-settlement";
const requestId="f53dbffe-b34c-4565-b4b0-b5f1189d2f65";
let order:any,product:any,payment:any,commands:any[],cash:any[];
const input=(v:any={})=>({requestId,orderId:"o",revision:1,kind:"RETURN",date:"2026-10-07",reason:"退貨",method:"現金",refund:100,freight:0,exchangeOrderId:"",lines:[{productId:"a",quantity:1,restock:true}],...v});
beforeEach(()=>{
 vi.clearAllMocks();order={id:"o",storeId:"s",partyId:"c",kind:"SALE",revision:1,date:new Date("2026-10-01"),total:200,paid:200,freight:0,voided:false,workOrder:null,settlements:[],lines:[{productId:"a",name:"商品",quantity:2,total:200,cost:80,pendingCostShares:{},unitPrice:100,discountMode:"NONE",discount:0,gift:false}]};product={id:"a",stock:8,averageCost:new Prisma.Decimal(40),pendingCosts:{}};payment={id:"p",kind:"SALE",storeId:"s",partyId:"c",date:new Date("2026-10-01"),total:200,method:"現金",allocations:[{orderId:"o",amount:200}],correction:null};commands=[];cash=[{id:"inventory:p:goods",amount:200,category:"零售-商品銷售",paymentMethod:"CASH"}];
 m.tx={inventoryCommand:{findUnique:async({where}:any)=>commands.find(c=>c.requestId===where.storeId_requestId.requestId),create:async({data}:any)=>{commands.push(data);return data;}},inventoryOrder:{findFirst:async({where}:any)=>where.id===order.id&&where.storeId===order.storeId?order:null,update:async({data}:any)=>{for(const [k,v] of Object.entries(data))order[k]=typeof v==="object"&&v&&"increment" in v?order[k]+(v as any).increment:typeof v==="object"&&v&&"decrement" in v?order[k]-(v as any).decrement:v;return order;}},inventoryProduct:{findFirst:async()=>product,update:async({data}:any)=>{product.stock+=data.stock.increment;return product;}},inventoryPayment:{findMany:async()=>[payment],findFirst:async()=>payment,update:async({data}:any)=>Object.assign(payment,data)},cashbookEntry:{findMany:async()=>cash.filter(e=>e.id.startsWith("inventory:p:")),create:async({data}:any)=>{cash.push(data);return data;}}};
 m.replacement.mockResolvedValue({id:"replacement"});
});
describe("inventory settlement service",()=>{
 it("denies payment correction before changing any financial records",async()=>{m.permission.mockRejectedValueOnce(Error("沒有收款更正權限"));await expect(correctInventoryPayment({requestId,paymentId:"p",date:"2026-10-07",reason:"權限驗收",method:"轉帳"})).rejects.toThrow("沒有收款更正權限");expect(m.permission).toHaveBeenCalledWith("inventory.payment.correct");expect(payment.correction).toBeNull();expect(order.paid).toBe(200);expect(product.stock).toBe(8);expect(cash).toHaveLength(1);expect(commands).toHaveLength(0);expect(m.replacement).not.toHaveBeenCalled();});
 it("writes linked refund, stock and debt once under request replay",async()=>{await settleInventory(input());await settleInventory(input());expect(product.stock).toBe(9);expect(order.total).toBe(100);expect(order.paid).toBe(100);expect(cash.filter(e=>e.category==="銷貨退款")).toHaveLength(1);expect(m.permission).toHaveBeenCalledWith("inventory.refund");expect(m.lock).toHaveBeenCalledTimes(1);});
 it("does not restock damaged goods or post unpaid refunds",async()=>{order.paid=0;await settleInventory(input({refund:0,lines:[{productId:"a",quantity:1,restock:false}]}));expect(product.stock).toBe(8);expect(order.total).toBe(100);expect(cash).toHaveLength(1);});
 it("rejects stale, foreign and unauthorized requests before mutation",async()=>{await expect(settleInventory(input({revision:2}))).rejects.toMatchObject({code:"CONFLICT"});await expect(settleInventory(input({orderId:"foreign"}))).rejects.toMatchObject({code:"NOT_FOUND"});m.permission.mockRejectedValueOnce(Error("拒絕"));await expect(settleInventory(input())).rejects.toThrow("拒絕");expect(product.stock).toBe(8);});
 it("rejects conflicting replay and excess refunds",async()=>{await settleInventory(input());await expect(settleInventory(input({reason:"更改"}))).rejects.toThrow("衝突");await expect(settleInventory(input({requestId:"18b9ce8b-eef0-47ed-9c54-11a4f634a24d",revision:2,refund:101}))).rejects.toMatchObject({code:"VALIDATION"});});
 it("blocks duplicate void and lets its pending refund be paid later",async()=>{await settleInventory(input({kind:"VOID",refund:0,lines:[{productId:"a",quantity:2,restock:true}]}));expect(order.voided).toBe(true);expect(order.paid).toBe(200);await settleInventory(input({requestId:"18b9ce8b-eef0-47ed-9c54-11a4f634a24d",revision:2,kind:"REFUND",lines:[],refund:200}));expect(order.paid).toBe(0);expect(product.stock).toBe(10);});
 it("corrects a method without changing stock, preserving replacement link",async()=>{await correctInventoryPayment({requestId,paymentId:"p",date:"2026-10-07",reason:"轉帳誤填",method:"轉帳"});expect(product.stock).toBe(8);expect(cash.at(-1).type).toBe("EXPENSE");expect(payment.correction.replacementId).toBe("replacement");expect(m.replacement).toHaveBeenCalledWith(expect.anything(),m.tx,expect.objectContaining({method:"轉帳",allocations:payment.allocations}));});
 it("voids every allocation and cannot undo a receipt twice",async()=>{await correctInventoryPayment({requestId,paymentId:"p",date:"2026-10-07",reason:"重複登錄"});expect(order.paid).toBe(0);expect(m.replacement).not.toHaveBeenCalled();await expect(correctInventoryPayment({requestId:"18b9ce8b-eef0-47ed-9c54-11a4f634a24d",paymentId:"p",date:"2026-10-07",reason:"再次"})).rejects.toMatchObject({code:"BUSINESS_RULE"});});
 it("does not correct receipts after a return or mixed work-order allocation",async()=>{order.settlements=[{date:"2026-10-07"}];await expect(correctInventoryPayment({requestId,paymentId:"p",date:"2026-10-07",reason:"錯誤"})).rejects.toMatchObject({code:"BUSINESS_RULE"});expect(cash).toHaveLength(1);});
});
