export const GUIDE_UI_PREVIEW_BRANCH: string;
export const GUIDE_UI_PREVIEW_DATABASE_URL: string;
export function isGuideUiPreview(env?: Record<string, string | undefined>): boolean;
export function createGuideUiDisabledClient(): unknown;
export const TRIAL_UI_PREVIEW_BRANCH: string;
export function isTrialUiPreview(env?: Record<string, string | undefined>): boolean;
export const HQ_USAGE_UI_PREVIEW_BRANCH: string;
export function isHqUsageUiPreview(env?: Record<string, string | undefined>): boolean;
export const SINGLE_PRICING_UI_PREVIEW_BRANCH: string;
export function isSinglePricingUiPreview(env?: Record<string, string | undefined>): boolean;
