import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import type { EncryptedDigitalButlerValue } from "@/lib/digital-butler-crypto";
import { assertDigitalButlerSubmittedAnswersSafe } from "@/lib/digital-butler-sensitive-json";

export class DigitalButlerScopeError extends Error {
  constructor() {
    super("DIGITAL_BUTLER_STORE_SCOPE_VIOLATION");
  }
}

// Prisma's generated Bytes type is a concrete ArrayBuffer-backed Uint8Array.
// Buffer may be SharedArrayBuffer-backed in newer Node typings, so copy it at
// the ORM boundary rather than weakening the sensitive-value type everywhere.
function prismaBytes(value: Uint8Array): Uint8Array<ArrayBuffer> {
  return Uint8Array.from(value);
}

export type CreateDigitalButlerDraftFlowInput = {
  storeId: string;
  name: string;
  draftDefinition: Prisma.InputJsonValue;
  sourceTemplateId?: string;
  sourceTemplateVersionId?: string;
};

export type UpsertDigitalButlerPhoneAnswerInput = {
  storeId: string;
  conversationId: string;
  stepId: string;
  encryptedPhone: EncryptedDigitalButlerValue;
  phoneHash: string;
};

export type CreateDigitalButlerLeadInput = {
  storeId: string;
  flowId: string;
  conversationId: string;
  completionActionKey: string;
  submittedAnswers: Prisma.InputJsonValue;
  encryptedPhone?: EncryptedDigitalButlerValue;
  phoneHash?: string;
};

export type PublishDigitalButlerFlowInput = {
  storeId: string;
  flowId: string;
  definition: Prisma.InputJsonValue;
  steps: Array<{
    stepKey: string;
    position: number;
    type: Prisma.DigitalButlerStepCreateWithoutFlowVersionInput["type"];
    config: Prisma.InputJsonValue;
    required: boolean;
  }>;
};

function publishedFlowVersionCreateData(
  input: PublishDigitalButlerFlowInput,
  version: number,
): Prisma.DigitalButlerFlowVersionUncheckedCreateInput {
  return {
    storeId: input.storeId,
    flowId: input.flowId,
    version,
    definition: input.definition,
    publishedAt: new Date(),
    steps: {
      create: input.steps.map((step): Prisma.DigitalButlerStepUncheckedCreateWithoutFlowVersionInput => ({
        stepKey: step.stepKey,
        position: step.position,
        type: step.type,
        config: step.config,
        required: step.required,
      })),
    },
  };
}

/**
 * Store-scoped persistence boundary. IDs from callers are never sufficient on
 * their own: each lookup constrains storeId before it can read or write.
 */
export class DigitalButlerRepository {
  async createDraftFlow(input: CreateDigitalButlerDraftFlowInput) {
    return prisma.storeDigitalButlerFlow.create({
      data: {
        storeId: input.storeId,
        name: input.name,
        draftDefinition: input.draftDefinition,
        sourceTemplateId: input.sourceTemplateId,
        sourceTemplateVersionId: input.sourceTemplateVersionId,
      },
      select: { id: true, storeId: true, status: true, enabled: true },
    });
  }

  async getFlow(storeId: string, flowId: string) {
    return prisma.storeDigitalButlerFlow.findFirst({
      where: { id: flowId, storeId },
      select: { id: true, storeId: true, status: true, enabled: true, draftDefinition: true },
    });
  }

  async listFlows(storeId: string) {
    return prisma.storeDigitalButlerFlow.findMany({
      where: { storeId, status: { not: "ARCHIVED" } },
      orderBy: { updatedAt: "desc" },
      select: {
        id: true,
        name: true,
        status: true,
        enabled: true,
        draftDefinition: true,
        currentPublishedVersionId: true,
        publishedVersion: {
          select: {
            id: true,
            version: true,
            publishedAt: true,
            steps: {
              orderBy: { position: "asc" },
              select: { stepKey: true, position: true, type: true, config: true },
            },
          },
        },
        updatedAt: true,
      },
    });
  }

  async updateDraft(
    storeId: string,
    flowId: string,
    input: { name: string; draftDefinition: Prisma.InputJsonValue },
  ) {
    const result = await prisma.storeDigitalButlerFlow.updateMany({
      where: { id: flowId, storeId, status: { not: "ARCHIVED" } },
      data: { name: input.name, draftDefinition: input.draftDefinition },
    });
    if (result.count !== 1) throw new DigitalButlerScopeError();
  }

  async publishFlow(input: PublishDigitalButlerFlowInput) {
    return prisma.$transaction(async (tx) => {
      // The version is allocated from the current maximum. Lock this scoped
      // flow row before reading it so concurrent publishers cannot both see
      // the same maximum and attempt to create the same next version.
      const lock = await tx.storeDigitalButlerFlow.updateMany({
        where: { id: input.flowId, storeId: input.storeId, status: { not: "ARCHIVED" } },
        data: { updatedAt: new Date() },
      });
      if (lock.count !== 1) throw new DigitalButlerScopeError();
      const latest = await tx.digitalButlerFlowVersion.aggregate({
        where: { flowId: input.flowId, storeId: input.storeId },
        _max: { version: true },
      });
      const version = await tx.digitalButlerFlowVersion.create({
        data: publishedFlowVersionCreateData(input, (latest._max.version ?? 0) + 1),
        select: {
          id: true,
          version: true,
          publishedAt: true,
          steps: {
            orderBy: { position: "asc" },
            select: { stepKey: true, position: true, type: true, config: true },
          },
        },
      });
      await tx.storeDigitalButlerFlow.update({
        where: { id_storeId: { id: input.flowId, storeId: input.storeId } },
        data: {
          status: "PUBLISHED",
          enabled: true,
          currentPublishedVersionId: version.id,
        },
      });
      return version;
    });
  }

  async setFlowEnabled(storeId: string, flowId: string, enabled: boolean) {
    const result = await prisma.storeDigitalButlerFlow.updateMany({
      where: {
        id: flowId,
        storeId,
        status: { in: ["PUBLISHED", "PAUSED"] },
        currentPublishedVersionId: { not: null },
      },
      data: { enabled, status: enabled ? "PUBLISHED" : "PAUSED" },
    });
    if (result.count !== 1) throw new DigitalButlerScopeError();
  }

  async upsertPhoneAnswer(input: UpsertDigitalButlerPhoneAnswerInput) {
    return prisma.$transaction(async (tx) => {
      const conversation = await tx.digitalButlerConversation.findFirst({
        where: { id: input.conversationId, storeId: input.storeId },
        select: { id: true, flowVersionId: true },
      });
      if (!conversation) throw new DigitalButlerScopeError();

      const step = await tx.digitalButlerStep.findFirst({
        where: {
          id: input.stepId,
          storeId: input.storeId,
          flowVersionId: conversation.flowVersionId,
        },
        select: { id: true },
      });
      if (!step) throw new DigitalButlerScopeError();

      return tx.digitalButlerAnswer.upsert({
        where: {
          conversationId_stepId: {
            conversationId: conversation.id,
            stepId: step.id,
          },
        },
        create: {
          storeId: input.storeId,
          conversationId: conversation.id,
          stepId: step.id,
          phoneCiphertext: prismaBytes(input.encryptedPhone.ciphertext),
          phoneIv: prismaBytes(input.encryptedPhone.iv),
          phoneAuthTag: prismaBytes(input.encryptedPhone.authTag),
          phoneHash: input.phoneHash,
        },
        update: {
          phoneCiphertext: prismaBytes(input.encryptedPhone.ciphertext),
          phoneIv: prismaBytes(input.encryptedPhone.iv),
          phoneAuthTag: prismaBytes(input.encryptedPhone.authTag),
          phoneHash: input.phoneHash,
        },
        select: { id: true },
      });
    });
  }

  async createLead(input: CreateDigitalButlerLeadInput) {
    assertDigitalButlerSubmittedAnswersSafe(input.submittedAnswers);
    return prisma.$transaction(async (tx) => {
      const conversation = await tx.digitalButlerConversation.findFirst({
        where: {
          id: input.conversationId,
          storeId: input.storeId,
          flowId: input.flowId,
        },
        select: { id: true },
      });
      if (!conversation) throw new DigitalButlerScopeError();

      return tx.digitalButlerLead.upsert({
        where: {
          storeId_conversationId_completionActionKey: {
            storeId: input.storeId,
            conversationId: conversation.id,
            completionActionKey: input.completionActionKey,
          },
        },
        create: {
          storeId: input.storeId,
          flowId: input.flowId,
          conversationId: conversation.id,
          completionActionKey: input.completionActionKey,
          submittedAnswers: input.submittedAnswers,
          phoneCiphertext: input.encryptedPhone
            ? prismaBytes(input.encryptedPhone.ciphertext)
            : undefined,
          phoneIv: input.encryptedPhone ? prismaBytes(input.encryptedPhone.iv) : undefined,
          phoneAuthTag: input.encryptedPhone
            ? prismaBytes(input.encryptedPhone.authTag)
            : undefined,
          phoneHash: input.phoneHash,
        },
        update: {},
        select: { id: true, storeId: true },
      });
    });
  }
}
