"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { RightSheet } from "@/components/admin/right-sheet";
import { updateSpaPerson } from "@/server/actions/spa-person";
export function EditSpaPerson({person,onSaved}:{person:{id:string;name:string;phone?:string;editable?:boolean;pendingBookings?:number};onSaved:()=>void}){
 const router=useRouter();const[draft,setDraft]=useState<{name:string;phone:string;deactivate:boolean}|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
 if(!person.editable)return null;
 return <><button className="rounded-lg border border-earth-200 px-3 py-2 text-sm" onClick={()=>{setError("");setDraft({name:person.name,phone:person.phone??"",deactivate:false});}}>編輯人員</button><RightSheet open={!!draft} onClose={()=>{if(!pending)setDraft(null);}} labelledById="spa-edit-person-title">{draft&&<form className="space-y-5 p-5" onSubmit={e=>{e.preventDefault();setError("");start(async()=>{try{const r=await updateSpaPerson({staffId:person.id,...draft});if(!r.success){setError(r.error);return;}setDraft(null);onSaved();router.refresh();}catch{setError("儲存失敗，內容已保留，請重試");}});}}><header className="flex justify-between"><h2 id="spa-edit-person-title" className="text-xl font-bold">編輯人員</h2><button type="button" disabled={pending} onClick={()=>setDraft(null)}>關閉</button></header><fieldset disabled={pending} className="space-y-5"><label className="block">姓名<input required maxLength={100} className="mt-2 w-full rounded-lg border border-earth-200 p-3" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="block">電話（選填）<input type="tel" maxLength={20} className="mt-2 w-full rounded-lg border border-earth-200 p-3" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><div className="rounded-lg bg-earth-50 p-4"><p className="mb-3 text-sm">未完成預約：{person.pendingBookings??0} 筆</p><label className="flex gap-2"><input type="checkbox" disabled={!!person.pendingBookings} checked={draft.deactivate} onChange={e=>setDraft({...draft,deactivate:e.target.checked})}/>停用此人員</label><p className="mt-2 text-sm text-earth-500">{person.pendingBookings?"請先改派或取消未完成預約，再停用人員。":"停用後不再接受新預約，既有歷史紀錄保留。"}</p></div></fieldset>{error&&<p role="alert" className="text-red-600">{error}</p>}<button disabled={pending} className="w-full rounded-lg bg-earth-800 p-3 text-white">{pending?"儲存中…":draft.deactivate?"儲存並停用":"儲存修改"}</button></form>}</RightSheet></>;
}
