"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { RightSheet } from "@/components/admin/right-sheet";
import { createSpaPerson } from "@/server/actions/spa-person";
const colors=["#6366f1","#0d9488","#e11d48","#d97706","#7c3aed","#2563eb"];
export function NewSpaPerson({onCreated}:{onCreated:(id:string)=>void}){
 const router=useRouter();const[draft,setDraft]=useState<{name:string;phone:string;colorCode:string;requestKey:string}|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
 return <><button type="button" className="rounded-lg bg-earth-800 px-4 py-3 text-sm font-medium text-white" onClick={()=>{setError("");setDraft({name:"",phone:"",colorCode:colors[0],requestKey:crypto.randomUUID()});}}>＋新增人員</button>
 <RightSheet open={!!draft} onClose={()=>{if(!pending)setDraft(null);}} labelledById="spa-new-person-title">{draft&&<><header className="flex items-center justify-between border-b border-earth-200 p-5"><div><h2 id="spa-new-person-title" className="text-xl font-bold">新增服務人員</h2><p className="mt-1 text-sm text-earth-500">先建立人員，再安排服務與班表。</p></div><button aria-label="關閉新增人員" disabled={pending} onClick={()=>setDraft(null)}>✕</button></header><form className="space-y-5 p-5" onSubmit={e=>{e.preventDefault();setError("");start(async()=>{try{const result=await createSpaPerson(draft);if(!result.success){setError(result.error);return;}onCreated(result.staffId);setDraft(null);router.refresh();}catch{setError("連線失敗，內容已保留，請重試");}});}}><fieldset disabled={pending} className="space-y-5"><label className="block font-medium">姓名<span className="ml-1 text-red-600">*</span><input autoFocus required maxLength={100} placeholder="例如：小美" className="mt-2 block w-full rounded-lg border border-earth-200 p-3" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="block font-medium">電話<span className="ml-2 text-sm font-normal text-earth-400">選填</span><input type="tel" maxLength={20} placeholder="聯絡電話" className="mt-2 block w-full rounded-lg border border-earth-200 p-3" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><fieldset><legend className="mb-2 font-medium">排程顏色</legend><div className="flex flex-wrap gap-3">{colors.map((color,i)=><label key={color} className="flex items-center gap-1"><input type="radio" name="personColor" aria-label={`顏色 ${i+1}`} checked={draft.colorCode===color} onChange={()=>setDraft({...draft,colorCode:color})}/><span className="h-7 w-7 rounded-full" style={{backgroundColor:color}}/></label>)}</div></fieldset></fieldset><p className="text-sm text-earth-500">此人員用於安排服務，不會開通後台登入權限。</p>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={pending} className="w-full rounded-lg bg-earth-800 p-3 font-medium text-white disabled:opacity-50">{pending?"新增中…":"新增人員"}</button></form></>}</RightSheet></>;
}
