"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {saveSpaStaffSchedule} from "@/server/actions/spa-resources";
type Person={id:string;name:string;skillIds:string[];shifts:{dayOfWeek:number;startTime:string;endTime:string}[]};
const weekdays=["日","一","二","三","四","五","六"];
export function StaffScheduleWorkspace({people,skills}:{people:Person[];skills:{id:string;name:string}[]}){
 const router=useRouter();const[draft,setDraft]=useState<{staffId:string;name:string;skillIds:string[];shifts:Person["shifts"]}|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
 return <main className="mx-auto max-w-6xl p-6"><h1 className="text-2xl font-bold">人員排班</h1><p className="my-3 text-earth-500">設定可提供的服務與固定班表，店主也能安排服務。</p><div className="grid gap-4 md:grid-cols-2">{people.map(p=><article key={p.id} className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">{p.name}</h2><p className="my-3">{skills.filter(s=>p.skillIds.includes(s.id)).map(s=>s.name).join("、")||"尚未設定專業項目"}</p>{p.shifts.map(s=><p key={s.dayOfWeek} className="text-sm text-earth-500">週{weekdays[s.dayOfWeek]} {s.startTime}–{s.endTime}</p>)}<button className="mt-4 rounded-lg border px-4 py-2" onClick={()=>{setError("");setDraft({staffId:p.id,name:p.name,skillIds:[...p.skillIds],shifts:p.shifts.map(s=>({...s}))});}}>設定技能與固定班表</button></article>)}</div>
 {draft&&<div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-label="人員排班設定" className="h-full w-full max-w-lg overflow-y-auto bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{draft.name}</h2><button disabled={pending} onClick={()=>setDraft(null)}>關閉</button></div><form className="mt-6 space-y-5" onSubmit={e=>{e.preventDefault();setError("");start(async()=>{try{const r=await saveSpaStaffSchedule(draft);if(!r.success){setError(r.error||"儲存失敗");return;}setDraft(null);router.refresh();}catch{setError("連線失敗，內容已保留");}});}}><fieldset><legend className="mb-3 font-semibold">專業項目</legend>{skills.map(s=><label key={s.id} className="mb-3 flex gap-2"><input type="checkbox" checked={draft.skillIds.includes(s.id)} onChange={e=>setDraft({...draft,skillIds:e.target.checked?[...draft.skillIds,s.id]:draft.skillIds.filter(id=>id!==s.id)})}/>{s.name}</label>)}</fieldset><fieldset><legend className="mb-3 font-semibold">每週固定班表</legend>{weekdays.map((name,day)=>{const shift=draft.shifts.find(s=>s.dayOfWeek===day);return <div key={day} className="mb-3 flex flex-wrap items-center gap-2"><label><input type="checkbox" checked={!!shift} onChange={e=>setDraft({...draft,shifts:e.target.checked?[...draft.shifts,{dayOfWeek:day,startTime:"10:00",endTime:"21:00"}]:draft.shifts.filter(s=>s.dayOfWeek!==day)})}/>週{name}</label>{shift&&<><input aria-label={`週${name}開始時間`} type="time" required className="rounded border p-2" value={shift.startTime} onChange={e=>setDraft({...draft,shifts:draft.shifts.map(s=>s.dayOfWeek===day?{...s,startTime:e.target.value}:s)})}/><span>至</span><input aria-label={`週${name}結束時間`} type="time" required className="rounded border p-2" value={shift.endTime} onChange={e=>setDraft({...draft,shifts:draft.shifts.map(s=>s.dayOfWeek===day?{...s,endTime:e.target.value}:s)})}/></>}</div>;})}</fieldset><p className="text-sm text-earth-500">更新固定班表不會自動更動既有預約。</p>{error&&<p role="alert" className="text-red-600">{error}</p>}<button disabled={pending} className="w-full rounded-xl bg-earth-800 p-3 text-white">{pending?"儲存中…":"儲存"}</button></form></section></div>}
 </main>;
}
