"use client";
import { DashboardLink as Link } from "@/components/dashboard-link";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {saveSpaStaffSchedule} from "@/server/actions/spa-resources";
type Person={id:string;name:string;skillIds:string[];shifts:{dayOfWeek:number;startTime:string;endTime:string}[]};
const weekdays=["日","一","二","三","四","五","六"];
export function StaffScheduleWorkspace({people,skills}:{people:Person[];skills:{id:string;name:string}[]}){
 const router=useRouter();const[draft,setDraft]=useState<{staffId:string;name:string;skillIds:string[];shifts:Person["shifts"]}|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
 return <main className="mx-auto max-w-[1440px] p-4 md:p-6"><header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">人員管理</h1><p className="mt-2 text-sm text-earth-500">管理專業項目與每週班表，各天可設定不同服務時段。</p></div><Link href="/dashboard/staff" className="rounded-lg border border-earth-200 bg-white px-4 py-2 text-sm">新增人員／管理人員資料</Link></header><div className="overflow-x-auto rounded-xl border border-earth-200 bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-earth-100 text-earth-600"><tr><th className="p-3">人員／專業項目</th>{[1,2,3,4,5,6,0].map(day=><th key={day} className="p-3 whitespace-nowrap">週{weekdays[day]}</th>)}<th className="p-3">操作</th></tr></thead><tbody>{people.map(p=><tr key={p.id} className="border-t border-earth-100"><td className="p-3"><strong>{p.name}</strong><p className="mt-1 max-w-48 text-xs text-earth-500">{skills.filter(s=>p.skillIds.includes(s.id)).map(s=>s.name).join("、")||"尚未設定專業項目"}</p></td>{[1,2,3,4,5,6,0].map(day=>{const shift=p.shifts.find(s=>s.dayOfWeek===day);return <td key={day} className="p-3 whitespace-nowrap text-xs">{shift?<>{shift.startTime}<br/>–{shift.endTime}</>:<span className="text-earth-400">休息</span>}</td>;})}<td className="p-3"><button className="whitespace-nowrap rounded-lg border border-earth-200 px-3 py-2" onClick={()=>{setError("");setDraft({staffId:p.id,name:p.name,skillIds:[...p.skillIds],shifts:p.shifts.map(s=>({...s}))});}}>編輯班表</button></td></tr>)}</tbody></table>{people.length===0&&<p className="p-6 text-earth-500">尚無啟用人員，請先新增人員。</p>}</div><p className="mt-3 text-xs text-earth-500">每人每天設定一段固定服務時間；修改後不會自動更動既有預約。</p>
 {draft&&<div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-label="人員排班設定" className="h-full w-full max-w-lg overflow-y-auto bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{draft.name}</h2><button disabled={pending} onClick={()=>setDraft(null)}>關閉</button></div><form className="mt-6 space-y-5" onSubmit={e=>{e.preventDefault();setError("");start(async()=>{try{const r=await saveSpaStaffSchedule(draft);if(!r.success){setError(r.error||"儲存失敗");return;}setDraft(null);router.refresh();}catch{setError("連線失敗，內容已保留");}});}}><fieldset><legend className="mb-3 font-semibold">專業項目</legend>{skills.map(s=><label key={s.id} className="mb-3 flex gap-2"><input type="checkbox" checked={draft.skillIds.includes(s.id)} onChange={e=>setDraft({...draft,skillIds:e.target.checked?[...draft.skillIds,s.id]:draft.skillIds.filter(id=>id!==s.id)})}/>{s.name}</label>)}</fieldset><fieldset><legend className="mb-3 font-semibold">每週固定班表</legend>{weekdays.map((name,day)=>{const shift=draft.shifts.find(s=>s.dayOfWeek===day);return <div key={day} className="mb-3 flex flex-wrap items-center gap-2"><label><input type="checkbox" checked={!!shift} onChange={e=>setDraft({...draft,shifts:e.target.checked?[...draft.shifts,{dayOfWeek:day,startTime:"10:00",endTime:"21:00"}]:draft.shifts.filter(s=>s.dayOfWeek!==day)})}/>週{name}</label>{shift&&<><input aria-label={`週${name}開始時間`} type="time" required className="rounded border p-2" value={shift.startTime} onChange={e=>setDraft({...draft,shifts:draft.shifts.map(s=>s.dayOfWeek===day?{...s,startTime:e.target.value}:s)})}/><span>至</span><input aria-label={`週${name}結束時間`} type="time" required className="rounded border p-2" value={shift.endTime} onChange={e=>setDraft({...draft,shifts:draft.shifts.map(s=>s.dayOfWeek===day?{...s,endTime:e.target.value}:s)})}/></>}</div>;})}</fieldset><p className="text-sm text-earth-500">更新固定班表不會自動更動既有預約。</p>{error&&<p role="alert" className="text-red-600">{error}</p>}<button disabled={pending} className="w-full rounded-xl bg-earth-800 p-3 text-white">{pending?"儲存中…":"儲存"}</button></form></section></div>}
 </main>;
}
