-- Phase B2: 擴充 PointType enum
ALTER TYPE "PointType" ADD VALUE 'REFERRAL_PARTNER';
ALTER TYPE "PointType" ADD VALUE 'SERVICE';
ALTER TYPE "PointType" ADD VALUE 'SERVICE_NOTE';
ALTER TYPE "PointType" ADD VALUE 'BECAME_FUTURE_OWNER';
ALTER TYPE "PointType" ADD VALUE 'MANUAL_ADJUSTMENT';
