"use client";
import { useRef, useState, type FormEvent } from "react";
import { ModalPanel } from "@/components/admin/modal-panel";
import { RosterToolbar } from "@/components/admin/roster-primitives";
import { CustomerInstantSearch } from "@/components/customer-instant-search";
import { OperationHistoryButton } from "@/components/operation-history-button";
import { toLocalDateStr } from "@/lib/date-utils";
import { LABOR_PRODUCT_ID, workOrderStatuses, workOrderPaymentLabel, type WorkOrderView, type WorkOrderDetails } from "@/lib/work-orders";
import type { WorkOrderData } from "@/server/services/work-orders";
import { loadWorkOrders, saveWorkOrderAction, collectWorkOrderAction, changeWorkOrderStatusAction } from "@/server/actions/work-orders";
import { createCustomer } from "@/server/actions/customer";
import { lineTotal, type LineInput } from "@/lib/inventory";

const control="min-h-11 min-w-0 rounded-md border border-earth-200 bg-white px-3 py-2 text-sm disabled:opacity-50";
const primary=`${control.replace("bg-white", "bg-primary-700")} text-white`;
const money=(value:number)=>`$${value.toLocaleString("zh-TW")}`;
type Editor={original:WorkOrderView|null;date:string;partyId:string;partyName:string;partyPhone:string;labor:number;details:WorkOrderDetails;lines:LineInput[]};
function editorTotal(editor:Editor|null):number|null{
  if(!editor)return 0;
  if(!Number.isSafeInteger(editor.labor)||editor.labor<0)return null;
  try{return editor.labor+editor.lines.reduce((sum,line)=>sum+lineTotal(line,"SALE"),0);}
  catch{return null;}
}

export function WorkOrderWorkspace({initial}:{initial:WorkOrderData}){
  const [data,setData]=useState(initial),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[payment,setPayment]=useState("all");
  const [editor,setEditor]=useState<Editor|null>(null),[selected,setSelected]=useState<WorkOrderView|null>(null),[collecting,setCollecting]=useState(false);
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState("");
  const [addingCustomer,setAddingCustomer]=useState(false);
  const [changedId,setChangedId]=useState("");
  const [amount,setAmount]=useState(0),[method,setMethod]=useState("現金"),[receiptDate,setReceiptDate]=useState(toLocalDateStr);
  const requestId=useRef(""),paymentId=useRef(""),statusId=useRef(""),baseline=useRef(""),locked=useRef(false),searchVersion=useRef(0);
  const rows=data.orders;
  async function search(page=1,nextStatus=status,nextPayment=payment){const version=++searchVersion.current;setSearching(true);setSearchError("");try{const result=await loadWorkOrders({query,page,status:nextStatus,payment:nextPayment});if(version!==searchVersion.current)return;if(result.success)setData(result.data);else setSearchError(result.error||"讀取失敗，請重試");}catch{if(version===searchVersion.current)setSearchError("讀取失敗，請重試");}finally{if(version===searchVersion.current)setSearching(false);}}
  function openEditor(order:WorkOrderView|null){
    const value:Editor={original:order,date:order?.date||toLocalDateStr(),partyId:order?.partyId||"",partyName:order?.partyName||"",partyPhone:order?.partyPhone||"",
      labor:order?.lines.find(l=>l.productId===LABOR_PRODUCT_ID)?.unitPrice||0,details:order?.workOrder||{status:"PROCESSING",item:"",serial:"",problem:"",work:"",note:""},
      lines:order?.lines.filter(l=>l.productId!==LABOR_PRODUCT_ID).map(l=>({productId:l.productId,quantity:l.quantity,unitPrice:l.unitPrice,discountMode:l.discountMode,discount:l.discount,gift:l.gift}))||[]};
    baseline.current=JSON.stringify(value);requestId.current=crypto.randomUUID();setError("");setAddingCustomer(false);setEditor(value);
  }
  function closeEditor(){if(busy)return;if(editor&&JSON.stringify(editor)!==baseline.current&&!window.confirm("尚有未儲存內容，確定關閉？"))return;setEditor(null);}
  async function mutate(run:()=>ReturnType<typeof saveWorkOrderAction>,done:()=>void|Promise<void>){
    if(locked.current)return;locked.current=true;setBusy(true);setError("");
    try{const result=await run();if(!result.success){setError(result.error||"操作失敗");return;}setChangedId(editor?.original?.id||selected?.id||result.data);await done();await search(data.page);}catch{setError("連線中斷，請重試；同一筆送出不會重複入帳");}finally{locked.current=false;setBusy(false);}
  }
  function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;
    void mutate(()=>saveWorkOrderAction({requestId:requestId.current,id:editor.original?.id,revision:editor.original?.revision,date:editor.date,partyId:editor.partyId,labor:editor.labor,lines:editor.lines,details:editor.details}),()=>{setEditor(null);setSelected(null);});
  }
  function openCollection(order:WorkOrderView){paymentId.current=crypto.randomUUID();setSelected(order);setAmount(order.total-order.paid);setMethod("現金");setReceiptDate(toLocalDateStr());setCollecting(true);setError("");}
  function collect(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;
    void mutate(()=>collectWorkOrderAction({requestId:paymentId.current,orderId:selected.id,date:receiptDate,method,amount}),async()=>{setCollecting(false);const result=await loadWorkOrders({query:selected.id,page:1,status:"all",payment:"all"});if(result.success)setSelected(result.data.orders.find(o=>o.id===selected.id)??null);else{setSelected(null);setError(result.error||"請重新開啟工單確認金額");}});
  }
  function changeStatus(order:WorkOrderView,next:WorkOrderDetails["status"]){statusId.current=crypto.randomUUID();void mutate(()=>changeWorkOrderStatusAction({requestId:statusId.current,id:order.id,revision:order.revision,status:next}),()=>setSelected(null));}
  async function addCustomer(){
    if(!editor || locked.current)return;locked.current=true;setBusy(true);setError("");
    try{const result=await createCustomer({name:editor.partyName,phone:editor.partyPhone});if(result.success){setEditor(old=>old?{...old,partyId:result.data.customerId}:old);setAddingCustomer(false);}else setError(result.error);}
    catch{setError("建立顧客失敗，請先搜尋電話確認是否已建立");}finally{locked.current=false;setBusy(false);}
  }
  const update=(patch:Partial<Editor>)=>setEditor(old=>old?{...old,...patch}:old);
  const updateDetails=(patch:Partial<WorkOrderDetails>)=>setEditor(old=>old?{...old,details:{...old.details,...patch}}:old);
  const total=editorTotal(editor);
  return <section className="min-w-0 space-y-3 text-sm text-earth-800">
    <div className="flex flex-wrap items-center justify-between gap-2"><h1 className="admin-page-title">工單</h1>{data.canWrite&&<button disabled={!data.canChooseCustomer} className={primary} onClick={()=>openEditor(null)}>新增工單</button>}</div>
    <form onSubmit={e=>{e.preventDefault();void search();}}><RosterToolbar label="工單搜尋與篩選"><input aria-label="搜尋姓名、電話或單號" placeholder="姓名／電話／單號" className={`${control} w-64 max-w-full`} value={query} onChange={e=>setQuery(e.target.value)}/><button className={control} disabled={searching}>{searching?"搜尋中…":"搜尋"}</button><select aria-label="工單進度篩選" className={control} value={status} onChange={e=>{setStatus(e.target.value);void search(1,e.target.value,payment);}}><option value="all">全部進度</option>{Object.entries(workOrderStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="付款狀態篩選" className={control} value={payment} onChange={e=>{setPayment(e.target.value);void search(1,status,e.target.value);}}><option value="all">全部付款</option><option value="unpaid">尚欠款</option><option value="paid">已付清</option></select></RosterToolbar></form>
    {searchError&&<p role="alert" className="text-red-700">{searchError}<button className={control} onClick={()=>void search(data.page)}>重試</button></p>}
    {!selected&&!editor&&error&&<p role="alert" className="text-red-700">{error}</p>}
    <div className="max-w-full overflow-x-auto rounded-md border border-earth-200"><table className="w-full min-w-[760px] border-collapse text-left"><thead className="bg-earth-50 text-earth-600"><tr>{["日期／單號","顧客","項目","進度","應收","尚欠","操作"].map(s=><th className="px-3 py-2 font-normal" key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} className={`border-t border-earth-100 hover:bg-earth-50 ${changedId===o.id?"bg-primary-50":""}`}><td className="px-3 py-1"><button className="min-h-11 text-left" onClick={()=>{setError("");setSelected(o);}}>{o.date}<span className="block break-all text-earth-500">{o.id.toUpperCase()}</span></button></td><td className="px-3 py-1">{o.partyName}<span className="block text-earth-500">{o.partyPhone}</span></td><td className="max-w-64 break-words px-3 py-1">{o.workOrder.item}</td><td className="whitespace-nowrap px-3 py-1">{workOrderStatuses[o.workOrder.status]}</td><td className="whitespace-nowrap px-3 py-1">{money(o.total)}</td><td className={`whitespace-nowrap px-3 py-1 ${o.paid<o.total?"text-amber-700":"text-green-700"}`}>{o.paid<o.total?`${workOrderPaymentLabel(o)}・${money(o.total-o.paid)}`:workOrderPaymentLabel(o)}</td><td className="px-3 py-1"><button className={control} onClick={()=>{setError("");setSelected(o);}}>{o.workOrder.status==="READY"?"取件": "查看"}</button>{data.canCollect&&o.paid<o.total&&<button className={control} onClick={()=>openCollection(o)}>收款</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-center text-earth-500">{data.count||query||status!=="all"||payment!=="all"?"沒有符合條件的資料":"尚未建立工單"}</p>}</div>
    <div className="flex flex-wrap items-center gap-2"><span>共 {data.count} 筆・第 {data.page} 頁</span><button className={control} disabled={searching||data.page<=1} onClick={()=>void search(data.page-1)}>上一頁</button><button className={control} disabled={searching||data.page*50>=data.count} onClick={()=>void search(data.page+1)}>下一頁</button></div>
    <ModalPanel open={!!editor} onClose={closeEditor} labelledById="work-order-edit" width={900} pending={busy}>
      {editor&&<form onSubmit={save} className="space-y-3 p-4"><h2 id="work-order-edit" className="admin-page-title">{editor.original?"編輯工單":"新增工單"}</h2><fieldset disabled={busy} className="space-y-3">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-4"><Field label="日期"><input type="date" required className={control} value={editor.date} onChange={e=>update({date:e.target.value})}/></Field>
        <div className="sm:col-span-3"><p className="mb-1">顧客</p>{editor.original?<p>{editor.partyName}・{editor.partyPhone}</p>:<>{addingCustomer?<div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><Field label="姓名"><input required className={control} value={editor.partyName} onChange={e=>update({partyName:e.target.value,partyId:""})}/></Field><Field label="電話"><input type="tel" required className={control} value={editor.partyPhone} onChange={e=>update({partyPhone:e.target.value,partyId:""})}/></Field><button type="button" className={control} onClick={()=>void addCustomer()}>建立顧客</button><button type="button" className={control} onClick={()=>setAddingCustomer(false)}>返回搜尋</button></div>:<CustomerInstantSearch storeId={data.store.id} value={editor.partyName} onChange={value=>update({partyName:value,partyId:"",partyPhone:""})} onSelect={customer=>update({partyId:customer.id,partyName:customer.name,partyPhone:customer.phone||""})} className={`${control} w-full`}/>} {!addingCustomer&&data.canCreateCustomer&&!editor.partyId&&<button type="button" className="min-h-11 px-2 text-primary-700" onClick={()=>setAddingCustomer(true)}>新增顧客</button>}{editor.partyId&&<p className="mt-1 text-primary-700">已選擇：{editor.partyName}・{editor.partyPhone}</p>}</>}</div></div>
        <Field label="施工／維修項目"><input required className={control} value={editor.details.item} onChange={e=>updateDetails({item:e.target.value})}/></Field>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="問題／需求"><textarea rows={2} className={control} value={editor.details.problem} onChange={e=>updateDetails({problem:e.target.value})}/></Field><Field label="處理內容"><textarea rows={2} className={control} value={editor.details.work} onChange={e=>updateDetails({work:e.target.value})}/></Field></div>
        <div className="grid grid-cols-2 items-end gap-3 sm:grid-cols-4"><Field label="工費"><input aria-label="工費" type="number" min={0} step={1} required className={control} value={editor.labor} onChange={e=>update({labor:Number(e.target.value)})}/></Field><p>應收<br/><b>{total===null?"請確認金額":money(total)}</b></p><p>已收<br/><b>{money(editor.original?.paid ?? 0)}</b></p><p>尚欠<br/><b>{total===null?"—":money(total-(editor.original?.paid ?? 0))}</b></p></div>
        {(data.canProducts||editor.lines.length>0)&&<details open={editor.lines.length>0}><summary className="min-h-11 cursor-pointer content-center">商品／材料（{editor.lines.length} 項）</summary><div className="space-y-2">{editor.lines.map((line,index)=><div key={line.productId} className="flex flex-wrap items-center gap-2"><span className="min-w-0 flex-1 break-words">{data.products.find(p=>p.id===line.productId)?.name||editor.original?.lines.find(p=>p.productId===line.productId)?.name||line.productId}</span><label className="flex items-center gap-2">數量<input aria-label={`商品 ${index+1} 數量`} type="number" min={1} step={1} required className={`${control} w-24`} value={line.quantity} onChange={e=>update({lines:editor.lines.map((l,i)=>i===index?{...l,quantity:Number(e.target.value)}:l)})}/></label><span>{money(line.unitPrice)}</span><button type="button" className={control} onClick={()=>update({lines:editor.lines.filter((_,i)=>i!==index)})}>移除</button></div>)}{data.canProducts&&<select aria-label="加入商品" className={`${control} w-full`} value="" onChange={e=>{const product=data.products.find(p=>p.id===e.target.value);if(product)update({lines:[...editor.lines,{productId:product.id,quantity:1,unitPrice:product.price,discountMode:"NONE",discount:0,gift:false}]});}}><option value="">加入商品／材料</option>{data.products.filter(p=>!editor.lines.some(l=>l.productId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}・庫存 {p.stock}・{money(p.price)}</option>)}</select>}</div></details>}
        <details><summary className="min-h-11 cursor-pointer content-center">更多資料{editor.details.serial||editor.details.note?"（已填寫）":""}</summary><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="型號／序號"><input className={control} value={editor.details.serial} onChange={e=>updateDetails({serial:e.target.value})}/></Field><Field label="顧客備註"><textarea rows={2} className={control} value={editor.details.note} onChange={e=>updateDetails({note:e.target.value})}/></Field></div></details>
        {!editor.original&&<p className="text-earth-500">未付款・取件時收款</p>}
        {error&&<p role="alert" className="text-red-700">{error}</p>}<div className="sticky bottom-0 flex flex-wrap justify-end gap-2 bg-white py-2"><button type="button" className={control} onClick={closeEditor}>取消</button><button className={primary} disabled={!editor.partyId||busy}>{busy?"儲存中…":"儲存"}</button></div>
      </fieldset></form>}
    </ModalPanel>
    <ModalPanel open={!!selected&&!editor} onClose={()=>{setSelected(null);setCollecting(false);}} labelledById="work-order-detail" width={800} pending={busy}>
      {selected&&<div className="space-y-3 p-4"><h2 id="work-order-detail" className="admin-page-title">工單・{selected.id.toUpperCase()}</h2><p>{selected.partyName}・{selected.partyPhone}</p><p>{selected.workOrder.item}・{workOrderStatuses[selected.workOrder.status]}</p><p>型號／序號：{selected.workOrder.serial||"—"}</p><p className="whitespace-pre-wrap break-words">{selected.workOrder.problem}</p><p className="whitespace-pre-wrap break-words">{selected.workOrder.work}</p><div className="overflow-x-auto"><table className="w-full text-left"><tbody>{selected.lines.map(l=><tr key={l.productId}><td className="py-1">{l.name} × {l.quantity}</td><td className="py-1 text-right">{money(l.total)}</td></tr>)}</tbody></table></div><p className="whitespace-pre-wrap break-words">{selected.workOrder.note}</p><p>應收 {money(selected.total)}・已收 {money(selected.paid)}・尚欠 {money(selected.total-selected.paid)}</p>
        {collecting?<form onSubmit={collect} className="space-y-3 rounded-md border border-earth-200 p-3"><fieldset disabled={busy} className="space-y-3"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Field label="收款日期"><input type="date" required className={control} value={receiptDate} onChange={e=>setReceiptDate(e.target.value)}/></Field><Field label="付款方式"><select className={control} value={method} onChange={e=>setMethod(e.target.value)}>{["現金","轉帳","其他"].map(m=><option key={m}>{m}</option>)}</select></Field><Field label="本次收款"><input type="number" min={1} max={selected.total-selected.paid} step={1} required className={control} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field></div>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex flex-wrap justify-end gap-2"><button type="button" className={control} onClick={()=>setCollecting(false)}>取消收款</button><button className={primary}>{busy?"收款中…":"確認收款"}</button></div></fieldset></form>:<><div className="flex flex-wrap gap-2">{data.canWrite&&selected.workOrder.status!=="COLLECTED"&&<button className={control} disabled={busy} onClick={()=>openEditor(selected)}>編輯</button>}{data.canCollect&&selected.paid<selected.total&&<button className={primary} disabled={busy} onClick={()=>openCollection(selected)}>收款</button>}{data.canWrite&&Object.entries(workOrderStatuses).filter(([k])=>k!==selected.workOrder.status).map(([k,v])=><button key={k} className={control} disabled={busy} onClick={()=>{if(k==="COLLECTED"&&selected.paid<selected.total&&!window.confirm(`尚欠 ${money(selected.total-selected.paid)}，確定先標記已取件？款項仍會保留未收。`))return;changeStatus(selected,k as WorkOrderDetails["status"]);}}>改為{v}</button>)}<a className={control} href={`work-orders/document?id=${encodeURIComponent(selected.id)}`} target="_blank" rel="noopener noreferrer">列印雙聯工單</a><OperationHistoryButton targetType="InventoryOrder" targetId={selected.id}/></div>{error&&<p role="alert" className="text-red-700">{error}</p>}</>}
        <button type="button" className={control} disabled={busy} onClick={()=>{setSelected(null);setCollecting(false);}}>關閉</button>
      </div>}
    </ModalPanel>
  </section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="flex min-w-0 flex-col gap-1"><span className="text-earth-600">{label}</span>{children}</label>;}
