"use client";
import { useRef, useState, type FormEvent } from "react";
import { ModalPanel } from "@/components/admin/modal-panel";
import { RosterToolbar } from "@/components/admin/roster-primitives";
import { CustomerLabels } from "@/components/customer-labels";
import { CustomerInstantSearch } from "@/components/customer-instant-search";
import { OperationHistoryButton } from "@/components/operation-history-button";
import { toLocalDateStr } from "@/lib/date-utils";
import { LABOR_PRODUCT_ID, workOrderNumber, workOrderContent, workOrderStatuses, workOrderPaymentLabel, workOrderProgressLabel, workOrderRefunded, type WorkOrderView, type WorkOrderDetails } from "@/lib/work-orders";
import type { WorkOrderData } from "@/server/services/work-orders";
import { loadWorkOrders, saveWorkOrderAction, collectWorkOrderAction, changeWorkOrderStatusAction } from "@/server/actions/work-orders";
import { WorkOrderSettlementPanel } from "./settlement-panel";
import { createCustomer } from "@/server/actions/customer";
import { categoryPrice, priceCategories, productSearch, lineTotal, type PriceCategory, type LineInput } from "@/lib/inventory";

const control="min-h-11 min-w-0 rounded-md border border-earth-200 bg-white px-3 py-2 text-sm disabled:opacity-50";
const primary=`${control.replace("bg-white", "bg-primary-700")} text-white`;
const money=(value:number)=>`$${value.toLocaleString("zh-TW")}`;
type Editor={original:WorkOrderView|null;date:string;partyId:string;partyName:string;partyPhone:string;priceCategory:PriceCategory;labor:number;details:WorkOrderDetails;lines:LineInput[]};
function editorTotal(editor:Editor|null):number|null{
  if(!editor)return 0;
  if(!Number.isSafeInteger(editor.labor)||editor.labor<0)return null;
  try{return editor.labor+editor.lines.reduce((sum,line)=>sum+lineTotal(line,"SALE"),0);}
  catch{return null;}
}

export function WorkOrderWorkspace({initial}:{initial:WorkOrderData}){
  const [data,setData]=useState(initial),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[payment,setPayment]=useState("all");
  const [editor,setEditor]=useState<Editor|null>(null),[selected,setSelected]=useState<WorkOrderView|null>(null),[collecting,setCollecting]=useState(false);
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState("");
  const [addingCustomer,setAddingCustomer]=useState(false);
  const [settlement,setSettlement]=useState<"CANCEL"|"REFUND"|null>(null);
  const [changedId,setChangedId]=useState("");
  const [productQuery,setProductQuery]=useState("");
  const [amount,setAmount]=useState(0),[method,setMethod]=useState("現金"),[receiptDate,setReceiptDate]=useState(toLocalDateStr);
  const requestId=useRef(""),paymentId=useRef(""),statusId=useRef(""),baseline=useRef(""),locked=useRef(false),searchVersion=useRef(0);
  const rows=data.orders;
  async function search(page=1,nextStatus=status,nextPayment=payment){const version=++searchVersion.current;setSearching(true);setSearchError("");try{const result=await loadWorkOrders({query,page,status:nextStatus,payment:nextPayment});if(version!==searchVersion.current)return;if(result.success)setData(result.data);else setSearchError(result.error||"讀取失敗，請重試");}catch{if(version===searchVersion.current)setSearchError("讀取失敗，請重試");}finally{if(version===searchVersion.current)setSearching(false);}}
  function openEditor(order:WorkOrderView|null){
    const value:Editor={original:order,date:order?.date||toLocalDateStr(),partyId:order?.partyId||"",partyName:order?.partyName||"",partyPhone:order?.partyPhone||"",
      priceCategory:order?.priceCategory||"GENERAL",labor:order?.lines.find(l=>l.productId===LABOR_PRODUCT_ID)?.unitPrice||0,details:order?{...order.workOrder,item:workOrderContent(order.workOrder),problem:"",work:""}:{status:"PROCESSING",cancelled:false,settlements:[],item:"",serial:"",problem:"",work:"",note:""},
      lines:order?.lines.filter(l=>l.productId!==LABOR_PRODUCT_ID).map(l=>({productId:l.productId,quantity:l.quantity,unitPrice:l.unitPrice,discountMode:l.discountMode,discount:l.discount,gift:l.gift}))||[]};
    baseline.current=JSON.stringify(value);requestId.current=crypto.randomUUID();setError("");setAddingCustomer(false);setProductQuery("");setEditor(value);
  }
  function closeEditor(){if(busy)return;if(editor&&JSON.stringify(editor)!==baseline.current&&!window.confirm("尚有未儲存內容，確定關閉？"))return;setEditor(null);}
  async function mutate(run:()=>ReturnType<typeof saveWorkOrderAction>,done:()=>void|Promise<void>){
    if(locked.current)return;locked.current=true;setBusy(true);setError("");
    try{const result=await run();if(!result.success){setError(result.error||"操作失敗");return;}setChangedId(editor?.original?.id||selected?.id||result.data);await done();await search(data.page);}catch{setError("連線中斷，請重試；同一筆送出不會重複入帳");}finally{locked.current=false;setBusy(false);}
  }
  function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor)return;
    void mutate(()=>saveWorkOrderAction({requestId:requestId.current,id:editor.original?.id,revision:editor.original?.revision,date:editor.date,partyId:editor.partyId,priceCategory:editor.priceCategory,labor:editor.labor,lines:editor.lines,details:editor.details}),()=>{setEditor(null);setSelected(null);});
  }
  function openCollection(order:WorkOrderView){paymentId.current=crypto.randomUUID();setSelected(order);setAmount(order.total-order.paid);setMethod("現金");setReceiptDate(toLocalDateStr());setCollecting(true);setError("");}
  function collect(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;
    void mutate(()=>collectWorkOrderAction({requestId:paymentId.current,orderId:selected.id,date:receiptDate,method,amount}),async()=>{setCollecting(false);const result=await loadWorkOrders({query:selected.id,page:1,status:"all",payment:"all"});if(result.success)setSelected(result.data.orders.find(o=>o.id===selected.id)??null);else{setSelected(null);setError(result.error||"請重新開啟工單確認金額");}});
  }
  function changeStatus(order:WorkOrderView,next:WorkOrderDetails["status"]){statusId.current=crypto.randomUUID();void mutate(()=>changeWorkOrderStatusAction({requestId:statusId.current,id:order.id,revision:order.revision,status:next}),()=>setSelected(null));}
  async function addCustomer(){
    if(!editor || locked.current)return;locked.current=true;setBusy(true);setError("");
    try{const result=await createCustomer({name:editor.partyName,phone:editor.partyPhone});if(result.success){setEditor(old=>old?{...old,partyId:result.data.customerId}:old);setAddingCustomer(false);}else setError(result.error);}
    catch{setError("建立顧客失敗，請先搜尋電話確認是否已建立");}finally{locked.current=false;setBusy(false);}
  }
  const update=(patch:Partial<Editor>)=>setEditor(old=>old?{...old,...patch}:old);
  const updateDetails=(patch:Partial<WorkOrderDetails>)=>setEditor(old=>old?{...old,details:{...old.details,...patch}}:old);
  const total=editorTotal(editor);
  return <section className="min-w-0 space-y-3 text-sm text-earth-800">
    <div className="flex flex-wrap items-center justify-between gap-2"><h1 className="admin-page-title">工單</h1>{data.canWrite&&<button disabled={!data.canChooseCustomer} className={primary} onClick={()=>openEditor(null)}>新增工單</button>}</div>
    <form onSubmit={e=>{e.preventDefault();void search();}}><RosterToolbar label="工單搜尋與篩選"><input aria-label="搜尋姓名、電話或單號" placeholder="姓名／電話／單號" className={`${control} w-64 max-w-full`} value={query} onChange={e=>setQuery(e.target.value)}/><button className={control} disabled={searching}>{searching?"搜尋中…":"搜尋"}</button><select aria-label="工單進度篩選" className={control} value={status} onChange={e=>{setStatus(e.target.value);void search(1,e.target.value,payment);}}><option value="all">全部進度</option>{Object.entries(workOrderStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="付款狀態篩選" className={control} value={payment} onChange={e=>{setPayment(e.target.value);void search(1,status,e.target.value);}}><option value="all">全部付款</option><option value="unpaid">尚欠款</option><option value="paid">已付清</option></select></RosterToolbar></form>
    {searchError&&<p role="alert" className="text-red-700">{searchError}<button className={control} onClick={()=>void search(data.page)}>重試</button></p>}
    {!selected&&!editor&&error&&<p role="alert" className="text-red-700">{error}</p>}
    <div className="max-w-full overflow-x-auto rounded-md border border-earth-200"><table className="w-full min-w-[760px] border-collapse text-left"><thead className="bg-earth-50 text-earth-600"><tr>{["日期／單號","顧客","項目","進度","應收","尚欠","操作"].map(s=><th className="px-3 py-2 font-normal" key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} className={`border-t border-earth-100 hover:bg-earth-50 ${changedId===o.id?"bg-primary-50":""}`}><td className="px-3 py-1"><button className="min-h-11 text-left" onClick={()=>{setError("");setSelected(o);}}>{o.date}<span className="block break-all text-earth-500">{workOrderNumber(o)}</span></button></td><td className="px-3 py-1">{o.partyName}<span className="block text-earth-500">{o.partyPhone}</span></td><td className="max-w-64 break-words px-3 py-1"><span className="text-earth-500">{o.workOrder.serial}</span><p className="line-clamp-2">{o.workOrder.item}</p></td><td className="whitespace-nowrap px-3 py-1">{workOrderProgressLabel(o.workOrder)}</td><td className="whitespace-nowrap px-3 py-1">{money(o.total)}</td><td className={`whitespace-nowrap px-3 py-1 ${o.paid<o.total?"text-amber-700":"text-green-700"}`}>{o.paid<o.total?`${workOrderPaymentLabel(o)}・${money(o.total-o.paid)}`:workOrderPaymentLabel(o)}</td><td className="px-3 py-1"><button className={control} onClick={()=>{setError("");setSelected(o);}}>{o.workOrder.status==="READY"?"取件": "查看"}</button>{data.canCollect&&o.paid<o.total&&<button className={control} onClick={()=>openCollection(o)}>收款</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-5 text-center text-earth-500">{data.count||query||status!=="all"||payment!=="all"?"沒有符合條件的資料":"尚未建立工單"}</p>}</div>
    <div className="flex flex-wrap items-center gap-2"><span>共 {data.count} 筆・第 {data.page} 頁</span><button className={control} disabled={searching||data.page<=1} onClick={()=>void search(data.page-1)}>上一頁</button><button className={control} disabled={searching||data.page*50>=data.count} onClick={()=>void search(data.page+1)}>下一頁</button></div>
    <ModalPanel open={!!editor} onClose={closeEditor} labelledById="work-order-edit" width={900} pending={busy}>
      {editor&&<form onSubmit={save} className="min-w-0 space-y-3 p-4"><h2 id="work-order-edit" className="admin-page-title">{editor.original?"編輯工單":"新增工單"}</h2><p className="text-earth-500">{editor.original?`單號 ${workOrderNumber(editor.original)}・${workOrderPaymentLabel(editor.original)}`:"單號儲存後自動產生・未付款"}</p><fieldset disabled={busy} className="min-w-0 space-y-3">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-4"><Field label="日期"><input type="date" required className={control} value={editor.date} onChange={e=>update({date:e.target.value})}/></Field>
        <div className="sm:col-span-3"><p className="mb-1">顧客</p>{editor.original?<p>{editor.partyName}・{editor.partyPhone}</p>:<>{addingCustomer?<div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><Field label="姓名"><input required className={control} value={editor.partyName} onChange={e=>update({partyName:e.target.value,partyId:""})}/></Field><Field label="電話"><input type="tel" required className={control} value={editor.partyPhone} onChange={e=>update({partyPhone:e.target.value,partyId:""})}/></Field><button type="button" className={control} onClick={()=>void addCustomer()}>建立顧客</button><button type="button" className={control} onClick={()=>setAddingCustomer(false)}>返回搜尋</button></div>:<CustomerInstantSearch storeId={data.store.id} value={editor.partyName} onChange={value=>update({partyName:value,partyId:"",partyPhone:""})} onSelect={customer=>update({partyId:customer.id,partyName:customer.name,partyPhone:customer.phone||""})} className={`${control} w-full`}/>} {!addingCustomer&&data.canCreateCustomer&&!editor.partyId&&<button type="button" className="min-h-11 px-2 text-primary-700" onClick={()=>setAddingCustomer(true)}>新增顧客</button>}{editor.partyId&&<p className="mt-1 text-primary-700">已選擇：{editor.partyName}・{editor.partyPhone}</p>}</>}{editor.partyId&&data.canChooseCustomer&&<CustomerLabels customerId={editor.partyId} displayOnly readOnly hideEmpty variant="badge" maxVisible={99}/>}</div></div>
        <Field label="種類／型號"><input list="work-order-types" className={control} placeholder="吉他／鋼琴／提琴，可填品牌型號" value={editor.details.serial} onChange={e=>updateDetails({serial:e.target.value})}/><datalist id="work-order-types">{["吉他","鋼琴","提琴"].map(type=><option key={type} value={type}/>)}</datalist></Field>
        <Field label="施工項目"><textarea rows={2} required maxLength={6000} className={control} placeholder="問題、需求與處理內容" value={editor.details.item} onChange={e=>updateDetails({item:e.target.value})}/></Field>
        {(data.canProducts||editor.lines.length>0)&&<section aria-label="商品材料" className="min-w-0 space-y-2">
          <div className="flex flex-wrap items-center justify-between gap-2"><p>商品／材料（{editor.lines.length} 項）</p><label className="flex items-center gap-2">價格身份<select aria-label="商品價格身份" className={control} value={editor.priceCategory} onChange={e=>{
            const value=e.target.value as PriceCategory;
            if(editor.lines.length&&!window.confirm("切換身份會重新帶入商品價格並清除目前折扣與贈品，是否繼續？"))return;
            update({priceCategory:value,lines:editor.lines.map(line=>{const product=data.products.find(p=>p.id===line.productId);return product?{...line,unitPrice:categoryPrice(product,value),discountMode:"NONE",discount:0,gift:false}:line;})});
          }}>{Object.entries(priceCategories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label></div>
          {data.canProducts&&<div className="relative"><input aria-label="即時篩選商品材料" type="search" className={`${control} w-full`} placeholder="搜尋商品名稱、品牌、型號、編號或條碼" value={productQuery} onChange={e=>setProductQuery(e.target.value)}/>{productQuery.trim()&&<div className="max-h-48 overflow-y-auto rounded-md border border-earth-200">{data.products.filter(p=>!editor.lines.some(l=>l.productId===p.id)&&productSearch(p,productQuery.trim())).slice(0,8).map(p=><button type="button" className="flex min-h-11 w-full items-center justify-between gap-2 px-3 text-left hover:bg-primary-50" key={p.id} onClick={()=>{update({lines:[...editor.lines,{productId:p.id,quantity:1,unitPrice:categoryPrice(p,editor.priceCategory),discountMode:"NONE",discount:0,gift:false}]});setProductQuery("");}}><span className="min-w-0 break-words">{[p.brand,p.name,p.specification].filter(Boolean).join("・")}</span><span className="shrink-0">庫存 {p.stock}・{money(categoryPrice(p,editor.priceCategory))}</span></button>)}{!data.products.some(p=>!editor.lines.some(l=>l.productId===p.id)&&productSearch(p,productQuery.trim()))&&<p className="p-3 text-earth-500">沒有符合的商品</p>}</div>}</div>}
          {editor.lines.length>0&&<div className="max-w-full overflow-x-auto rounded-md border border-earth-200"><table className="w-full min-w-[800px] text-left"><thead className="bg-earth-50"><tr>{["商品","數量","單價","折扣方式","折扣","贈品","小計",""].map((name,i)=><th className="px-2 py-1 font-normal" key={i}>{name}</th>)}</tr></thead><tbody>{editor.lines.map((line,index)=>{
            const product=data.products.find(p=>p.id===line.productId);const name=product?.name||editor.original?.lines.find(p=>p.productId===line.productId)?.name||line.productId;
            let subtotal:number|null=null;try{subtotal=lineTotal(line,"SALE");}catch{}
            const editLine=(patch:Partial<LineInput>)=>update({lines:editor.lines.map((l,i)=>i===index?{...l,...patch}:l)});
            return <tr className="border-t border-earth-100" key={line.productId}><td className="max-w-48 break-words px-2">{name}{product&&<span className="block text-earth-500">庫存 {product.stock}</span>}</td><td className="p-1"><input aria-label={`${name} 數量`} type="number" min={1} step={1} required className={`${control} w-20`} value={line.quantity} onChange={e=>editLine({quantity:Number(e.target.value)})}/></td><td className="p-1"><input aria-label={`${name} 單價`} type="number" min={0} step={1} required readOnly={!data.canPriceOverride} className={`${control} w-24`} value={line.unitPrice} onChange={e=>editLine({unitPrice:Number(e.target.value)})}/></td><td className="p-1"><select aria-label={`${name} 折扣方式`} disabled={line.gift||!data.canPriceOverride} className={control} value={line.discountMode} onChange={e=>editLine({discountMode:e.target.value as LineInput["discountMode"],discount:0})}><option value="NONE">無折扣</option><option value="AMOUNT">折抵金額</option><option value="PERCENT">折扣 %</option></select></td><td className="p-1"><input aria-label={`${name} 折扣`} type="number" min={0} max={line.discountMode==="PERCENT"?100:undefined} step={line.discountMode==="PERCENT"?0.01:1} required disabled={line.gift||line.discountMode==="NONE"||!data.canPriceOverride} className={`${control} w-20`} value={line.discount} onChange={e=>editLine({discount:Number(e.target.value)})}/></td><td className="p-1"><label className="flex min-h-11 min-w-11 items-center justify-center"><input aria-label={`${name} 贈品`} type="checkbox" disabled={!data.canPriceOverride} checked={line.gift} onChange={e=>editLine({gift:e.target.checked})}/></label></td><td className="whitespace-nowrap px-2">{subtotal===null?"請確認金額":money(subtotal)}</td><td className="p-1"><button type="button" className={control} onClick={()=>update({lines:editor.lines.filter((_,i)=>i!==index)})}>移除</button></td></tr>;
          })}</tbody></table></div>}
        </section>}
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Field label="工費"><input aria-label="工費" type="number" min={0} step={1} required className={control} value={editor.labor} onChange={e=>update({labor:Number(e.target.value)})}/></Field><div className="sm:col-span-2"><Field label="顧客備註"><textarea rows={1} maxLength={2000} className={control} value={editor.details.note} onChange={e=>updateDetails({note:e.target.value})}/></Field></div></div>
        <div className="grid grid-cols-3 gap-3 border-t border-earth-200 pt-3"><p>應收<br/><b>{total===null?"請確認金額":money(total)}</b></p><p>已收<br/><b>{money(editor.original?.paid ?? 0)}</b></p><p>尚欠<br/><b>{total===null?"—":money(total-(editor.original?.paid ?? 0))}</b></p></div>
        {error&&<p role="alert" className="text-red-700">{error}</p>}<div className="sticky bottom-0 flex flex-wrap justify-end gap-2 bg-white py-2"><button type="button" className={control} onClick={closeEditor}>取消</button><button className={primary} disabled={!editor.partyId||busy}>{busy?"儲存中…":"儲存"}</button></div>
      </fieldset></form>}
    </ModalPanel>
    <ModalPanel open={!!selected&&!editor} onClose={()=>{setSelected(null);setCollecting(false);}} labelledById="work-order-detail" width={800} pending={busy}>
      {selected&&<div className="min-w-0 space-y-4 p-5 text-sm text-earth-800">
        <header className="space-y-3 border-b border-earth-200 pb-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h2 id="work-order-detail" className="admin-page-title">工單・{workOrderNumber(selected)}</h2>
            <div className="flex flex-wrap gap-2"><span className="rounded-md bg-earth-100 px-2 py-1">{workOrderProgressLabel(selected.workOrder)}</span><span className={`rounded-md px-2 py-1 ${selected.paid<selected.total?"bg-amber-50 text-amber-800":"bg-primary-50 text-primary-800"}`}>{workOrderPaymentLabel(selected)}</span></div>
          </div>
          <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1"><p className="break-words text-base font-semibold">{selected.partyName}</p><p className="tabular-nums">{selected.partyPhone}</p></div>
          {data.canChooseCustomer&&<CustomerLabels customerId={selected.partyId} displayOnly readOnly hideEmpty variant="badge" maxVisible={99}/>}
          <dl className="flex min-w-0 gap-3"><dt className="shrink-0 text-earth-500">種類／型號</dt><dd className="min-w-0 break-words">{selected.workOrder.serial||"—"}</dd></dl>
        </header>
        <section aria-labelledby="work-order-content-heading" className="space-y-2">
          <h3 id="work-order-content-heading" className="font-semibold text-primary-900">施工項目</h3>
          <p className="whitespace-pre-wrap break-words rounded-md bg-earth-50 p-3 text-base leading-relaxed">{workOrderContent(selected.workOrder)}</p>
        </section>
        <section aria-labelledby="work-order-materials-heading" className="min-w-0 space-y-2">
          <h3 id="work-order-materials-heading" className="font-semibold text-primary-900">商品／材料與工費</h3>
          <div className="max-w-full overflow-x-auto rounded-md border border-earth-200"><table className="w-full table-fixed text-left"><thead className="bg-earth-50 text-earth-600"><tr><th className="px-3 py-2 font-normal">品項</th><th className="w-16 px-2 py-2 text-right font-normal">數量</th><th className="w-28 px-3 py-2 text-right font-normal">金額</th></tr></thead><tbody>{selected.lines.map(l=><tr key={l.productId} className="border-t border-earth-100"><td className="break-words px-3 py-2">{l.name}{(l.gift||l.discountMode!=="NONE")&&<span className="mt-1 block text-earth-500">{l.gift?"贈品":l.discountMode==="PERCENT"?`折扣 ${l.discount}%`:`折抵 ${money(l.discount)}`}</span>}</td><td className="px-2 py-2 text-right tabular-nums">{l.quantity}</td><td className="px-3 py-2 text-right tabular-nums">{money(l.total)}</td></tr>)}</tbody></table></div>
        </section>
        {selected.workOrder.note&&<section aria-labelledby="work-order-note-heading" className="space-y-1"><h3 id="work-order-note-heading" className="text-earth-500">顧客備註</h3><p className="whitespace-pre-wrap break-words leading-relaxed">{selected.workOrder.note}</p></section>}
        <dl aria-label="工單金額" className="grid grid-cols-3 divide-x divide-earth-200 rounded-md border border-earth-200 bg-earth-50 py-3">
          <div className="min-w-0 px-3"><dt className="text-earth-500">應收</dt><dd className="mt-1 break-words text-lg font-semibold tabular-nums">{money(selected.total)}</dd></div>
          <div className="min-w-0 px-3"><dt className="text-earth-500">{workOrderRefunded(selected.workOrder)>0?"淨已收":"已收"}</dt><dd className="mt-1 break-words text-lg font-semibold tabular-nums">{money(selected.paid)}</dd></div>
          <div className="min-w-0 px-3"><dt className="text-earth-500">尚欠</dt><dd className={`mt-1 break-words text-lg font-semibold tabular-nums ${selected.paid<selected.total?"text-amber-800":"text-primary-800"}`}>{money(selected.total-selected.paid)}</dd></div>
        </dl>
        {selected.workOrder.settlements.length>0&&<details className="border-t border-earth-200 pt-1"><summary className="min-h-11 cursor-pointer py-3 font-medium">取消／退款紀錄<span className="ml-3 inline-block font-normal text-earth-500">累計退款 {money(workOrderRefunded(selected.workOrder))}</span></summary><ul className="space-y-4 pb-2">{selected.workOrder.settlements.map(s=><li key={s.requestId} className="space-y-2 border-l-2 border-earth-200 pl-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{s.kind==="CANCEL"?"取消工單":"退款"}</p><p className="text-earth-500 tabular-nums">{s.date}</p></div><dl className="grid grid-cols-[5rem_minmax(0,1fr)] gap-x-3 gap-y-2 leading-relaxed"><dt className="text-earth-500">原因</dt><dd className="whitespace-pre-wrap break-words">{s.reason}</dd><dt className="text-earth-500">應收調整</dt><dd>{money(s.previousTotal)} → {money(s.total)}</dd><dt className="text-earth-500">退款</dt><dd className="font-medium">{money(s.refund)}{s.refund>0?`（${s.method}）`:""}</dd>{s.returned.length>0&&<><dt className="text-earth-500">退回庫存</dt><dd className="min-w-0"><ul className="space-y-1">{s.returned.map(l=><li key={l.productId} className="flex items-start justify-between gap-3"><span className="min-w-0 break-words">{l.name}</span><span className="shrink-0 tabular-nums">× {l.quantity}</span></li>)}</ul></dd></>}</dl></li>)}</ul></details>}
        {collecting?<form onSubmit={collect} className="space-y-3 rounded-md border border-earth-200 p-3"><fieldset disabled={busy} className="min-w-0 space-y-3"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Field label="收款日期"><input type="date" required className={control} value={receiptDate} onChange={e=>setReceiptDate(e.target.value)}/></Field><Field label="付款方式"><select className={control} value={method} onChange={e=>setMethod(e.target.value)}>{["現金","轉帳","其他"].map(m=><option key={m}>{m}</option>)}</select></Field><Field label="本次收款"><input type="number" min={1} max={selected.total-selected.paid} step={1} required className={control} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field></div>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex flex-wrap justify-end gap-2"><button type="button" className={control} onClick={()=>setCollecting(false)}>取消收款</button><button className={primary}>{busy?"收款中…":"確認收款"}</button></div></fieldset></form>:<>{((data.canWrite&&(!selected.workOrder.cancelled||selected.workOrder.status!=="COLLECTED"))||(data.canCollect&&selected.paid<selected.total))&&<div aria-label="工單操作" className="flex flex-wrap gap-2 border-t border-earth-200 pt-3">{data.canWrite&&selected.workOrder.status!=="COLLECTED"&&!selected.workOrder.cancelled&&<button className={control} disabled={busy} onClick={()=>openEditor(selected)}>編輯</button>}{data.canCollect&&selected.paid<selected.total&&<button className={primary} disabled={busy} onClick={()=>openCollection(selected)}>收款</button>}{data.canWrite&&Object.entries(workOrderStatuses).filter(([k])=>k!=="CANCELLED"&&k!==selected.workOrder.status&&(!selected.workOrder.cancelled||k==="COLLECTED")).map(([k,v])=><button key={k} className={control} disabled={busy} onClick={()=>{if(k==="COLLECTED"&&selected.paid<selected.total&&!window.confirm(`尚欠 ${money(selected.total-selected.paid)}，確定先標記已取件？款項仍會保留未收。`))return;changeStatus(selected,k as WorkOrderDetails["status"]);}}>改為{v}</button>)}{data.canWrite&&!selected.workOrder.cancelled&&<button className={control} disabled={busy} onClick={()=>{setError("");setSettlement("CANCEL");}}>取消／不維修</button>}</div>}{error&&<p role="alert" className="text-red-700">{error}</p>}</>}
        <footer className="sticky -bottom-5 -mx-5 -mb-5 flex flex-wrap items-center justify-between gap-3 border-t border-earth-200 bg-white px-5 py-3">
          <div className="flex flex-wrap items-center gap-2">{!collecting&&data.canCollect&&selected.paid>0&&<button className={control} disabled={busy} onClick={()=>{setError("");setSettlement("REFUND");}}>退款</button>}<a className={control} href={`work-orders/document?id=${encodeURIComponent(selected.id)}`} target="_blank" rel="noopener noreferrer">列印雙聯工單</a><div className="[&_button]:min-h-11 [&_button]:px-2"><OperationHistoryButton targetType="InventoryOrder" targetId={selected.id}/></div></div>
          <button type="button" className={control} disabled={busy} onClick={()=>{setSelected(null);setCollecting(false);}}>關閉</button>
        </footer>
      </div>}
    </ModalPanel>
    {selected&&settlement&&<WorkOrderSettlementPanel initial={selected} kind={settlement} storeId={data.store.id} onClose={()=>setSettlement(null)} onSaved={async()=>{const result=await loadWorkOrders({query:selected.id,page:1,status:"all",payment:"all"});if(!result.success)throw new Error("請重新開啟工單");setSelected(result.data.orders.find(o=>o.id===selected.id)??null);setChangedId(selected.id);setSettlement(null);await search(data.page);}}/>}
  </section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="flex min-w-0 flex-col gap-1"><span className="text-earth-600">{label}</span>{children}</label>;}
