"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {RightSheet} from "@/components/admin/right-sheet";
import {saveSpaPackage} from "@/server/actions/spa-commerce";
type Package={id:string;name:string;treatmentId:string;price:number;uses:number;validityDays:number;isActive:boolean};
export function SpaPackagesManager({packages,services,canManage}:{packages:Package[];services:{id:string;name:string}[];canManage:boolean}){
 const router=useRouter(),[editing,setEditing]=useState<Partial<Package>|null>(null),[error,setError]=useState(""),[pending,start]=useTransition();
 return <section className="mt-8 space-y-4"><header className="flex justify-between"><div><h2 className="text-xl font-bold">次數方案</h2><p className="text-sm text-earth-500">設定售價、堂數與期限；到顧客管理替顧客購買。</p></div>{canManage&&<button onClick={()=>{setError("");setEditing({name:"",treatmentId:services[0]?.id??"",price:0,uses:10,validityDays:180,isActive:true});}} className="rounded-lg bg-earth-800 p-3 text-white">新增方案</button>}</header><div className="divide-y rounded-xl border">{packages.map(p=><div key={p.id} className="flex items-center justify-between gap-3 p-4"><div><strong>{p.name}</strong><p>{services.find(s=>s.id===p.treatmentId)?.name} · {p.uses} 次 · {p.validityDays} 天 · NT${p.price.toLocaleString()} · {p.isActive?"上架":"下架"}</p></div>{canManage&&<button onClick={()=>{setError("");setEditing(p);}} className="rounded-lg border p-2">編輯</button>}</div>)}{!packages.length&&<p className="p-4">尚未建立次數方案</p>}</div>{editing&&<RightSheet open onClose={()=>{if(!pending)setEditing(null);}} width={520} labelledById="package-title"><form className="space-y-4 p-5" onSubmit={e=>{e.preventDefault();setError("");start(async()=>{try{const r=await saveSpaPackage(editing as Package);if(!r.success){setError(r.error);return;}setEditing(null);router.refresh();}catch{setError("儲存失敗，請重試。");}});}}><h2 id="package-title" className="text-xl font-bold">{editing.id?"編輯方案":"新增方案"}</h2><fieldset disabled={pending} className="space-y-4"><label className="block">方案名稱<input required maxLength={80} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} className="mt-1 w-full rounded border p-3"/></label><label className="block">適用服務<select required value={editing.treatmentId} onChange={e=>setEditing({...editing,treatmentId:e.target.value})} className="mt-1 w-full rounded border p-3">{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{([['price','售價',0,9999999],['uses','堂數',1,999],['validityDays','有效天數（含購買日）',1,3650]] as const).map(([key,label,min,max])=><label key={key} className="block">{label}<input required type="number" step={1} min={min} max={max} value={editing[key]} onChange={e=>setEditing({...editing,[key]:Number(e.target.value)})} className="mt-1 w-full rounded border p-3"/></label>)}<label className="flex gap-2"><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/>上架</label><p className="text-sm">修改只影響之後的購買，既有顧客的堂數、金額及期限保持原紀錄。</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<button className="rounded-lg bg-earth-800 p-3 text-white">{pending?"儲存中…":"儲存方案"}</button><button type="button" className="ml-3" onClick={()=>setEditing(null)}>返回</button></fieldset></form></RightSheet>}</section>;
}
