"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveSpaServiceProviders } from "@/server/actions/spa-service-staff";
type Service={id:string;name:string;isActive:boolean;staffIds:string[]};
export function SpaSkillsManager({services,people,canManage}:{services:Service[];people:{id:string;name:string}[];canManage:boolean}){
 const router=useRouter();const[draft,setDraft]=useState<Service|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
 return <section className="my-5 rounded-xl border border-earth-200 bg-white p-5"><h2 className="text-lg font-semibold">服務與人員</h2><p className="mt-1 text-sm text-earth-500">設定誰能提供這項服務，預約時會再依排班與空檔篩選。</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-earth-200"><th className="py-3">服務</th><th>可服務人員</th><th>操作</th></tr></thead><tbody>{services.map(s=><tr key={s.id} className="border-b border-earth-100"><td className="py-3">{s.name}{!s.isActive&&<span className="ml-2 text-earth-400">已停用</span>}</td><td>{people.filter(p=>s.staffIds.includes(p.id)).map(p=>p.name).join("、")||"尚未安排人員"}</td><td>{canManage&&<button className="rounded border border-earth-200 px-3 py-2" onClick={()=>{setError("");setDraft({...s,staffIds:[...s.staffIds]});}}>設定人員</button>}</td></tr>)}</tbody></table></div>
 {draft&&<div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-label="可服務人員" className="h-full w-full max-w-lg overflow-y-auto bg-white p-6"><header className="mb-5 flex justify-between"><h3 className="text-xl font-semibold">{draft.name}</h3><button disabled={pending} onClick={()=>setDraft(null)}>關閉</button></header><form onSubmit={e=>{e.preventDefault();setError("");start(async()=>{try{const result=await saveSpaServiceProviders({treatmentId:draft.id,staffIds:draft.staffIds});if(!result.success){setError(result.error??"儲存失敗");return;}setDraft(null);router.refresh();}catch{setError("連線失敗，內容已保留");}});}}><p className="mb-4 text-sm text-earth-500">勾選可提供這項服務的人員，會同步顯示在人員管理。</p>{people.map(p=><label key={p.id} className="mb-3 flex gap-2"><input type="checkbox" checked={draft.staffIds.includes(p.id)} onChange={e=>setDraft({...draft,staffIds:e.target.checked?[...draft.staffIds,p.id]:draft.staffIds.filter(id=>id!==p.id)})}/>{p.name}</label>)}<p className="text-xs text-earth-500">全部取消勾選後，此服務不會有可預約人員。既有預約仍保留。</p>{error&&<p role="alert" className="mt-4 text-red-600">{error}</p>}<button disabled={pending} className="mt-5 rounded bg-earth-800 px-4 py-2 text-white">{pending?"儲存中…":"儲存"}</button></form></section></div>}
 </section>;
}
