"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { saveSpaSkill, saveSpaTreatmentSkills } from "@/server/actions/spa-resources";
export function SpaSkillsManager({skills,treatments,canManage}:{skills:{id:string;name:string}[];treatments:{id:string;name:string;skillIds:string[]}[];canManage:boolean}){
 const router=useRouter();const[draft,setDraft]=useState<{id?:string;name:string}|null>(null);const[treatment,setTreatment]=useState<(typeof treatments)[number]|null>(null);const[error,setError]=useState("");const[pending,start]=useTransition();
 function run(action:()=>Promise<{success:boolean;error?:string}>){setError("");start(async()=>{try{const r=await action();if(!r.success){setError(r.error??"儲存失敗");return;}setDraft(null);setTreatment(null);router.refresh();}catch{setError("連線失敗，內容已保留");}});}
 return <section className="my-5 rounded-xl border border-earth-200 bg-white p-5"><header className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">專業項目</h2><p className="mt-1 text-sm text-earth-500">設定服務需要的專業，再到人員管理指派具備該專業的人員。</p></div>{canManage&&<button className="rounded-lg border border-earth-200 px-3 py-2" onClick={()=>{setError("");setDraft({name:""});}}>＋新增項目</button>}</header><div className="flex flex-wrap gap-2">{skills.map(s=><button disabled={!canManage} key={s.id} className="rounded-lg bg-earth-100 px-3 py-2 text-sm" onClick={()=>{setError("");setDraft(s);}}>{s.name}{canManage?" · 編輯":""}</button>)}{skills.length===0&&<p className="text-sm text-earth-500">尚未建立專業項目。</p>}</div>
 <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-earth-200"><th className="py-3">服務／療程</th><th>所需專業</th><th>操作</th></tr></thead><tbody>{treatments.map(t=><tr key={t.id} className="border-b border-earth-100"><td className="py-3">{t.name}</td><td>{skills.filter(s=>t.skillIds.includes(s.id)).map(s=>s.name).join("、")||"未指定"}</td><td>{canManage&&<button className="rounded border border-earth-200 px-2 py-1" onClick={()=>{setError("");setTreatment({...t,skillIds:[...t.skillIds]});}}>設定專業</button>}</td></tr>)}</tbody></table></div>
 {(draft||treatment)&&<div className="fixed inset-0 z-50 flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-label="專業項目設定" className="h-full w-full max-w-lg overflow-y-auto bg-white p-6"><header className="mb-5 flex justify-between"><h3 className="text-xl font-semibold">{treatment?treatment.name:draft?.id?"編輯專業項目":"新增專業項目"}</h3><button disabled={pending} onClick={()=>{setDraft(null);setTreatment(null);}}>關閉</button></header>{draft?<form onSubmit={e=>{e.preventDefault();run(()=>saveSpaSkill(draft));}}><label>名稱<input autoFocus required maxLength={60} className="mt-2 block w-full rounded border border-earth-200 p-3" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><button disabled={pending} className="mt-5 rounded bg-earth-800 px-4 py-2 text-white">{pending?"儲存中…":"儲存"}</button>{draft.id&&<button type="button" disabled={pending} className="ml-4 text-red-600" onClick={()=>run(()=>saveSpaSkill({...draft,remove:true}))}>移除項目</button>}<p className="mt-4 text-sm text-earth-500">仍被療程使用的項目無法移除，請先調整下方療程的所需專業。</p></form>:treatment&&<form onSubmit={e=>{e.preventDefault();run(()=>saveSpaTreatmentSkills({treatmentId:treatment.id,skillIds:treatment.skillIds}));}}>{skills.map(s=><label key={s.id} className="mb-3 flex gap-2"><input type="checkbox" checked={treatment.skillIds.includes(s.id)} onChange={e=>setTreatment({...treatment,skillIds:e.target.checked?[...treatment.skillIds,s.id]:treatment.skillIds.filter(id=>id!==s.id)})}/>{s.name}</label>)}<button disabled={pending} className="mt-5 rounded bg-earth-800 px-4 py-2 text-white">{pending?"儲存中…":"儲存"}</button></form>}{error&&<p role="alert" className="mt-4 text-red-600">{error}</p>}</section></div>}
 </section>;
}
